/* drag_file.c generated by valac 0.34.4, the Vala compiler
 * generated from drag_file.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * drag_file.vala
 * Copyright (C) 2015 Kyle Agronick <agronick@gmail.com>
     *
 * Relay is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
     * 
 * Relay is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>


#define TYPE_DRAG_FILE (drag_file_get_type ())
#define DRAG_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_DRAG_FILE, DragFile))
#define DRAG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_DRAG_FILE, DragFileClass))
#define IS_DRAG_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_DRAG_FILE))
#define IS_DRAG_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_DRAG_FILE))
#define DRAG_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_DRAG_FILE, DragFileClass))

typedef struct _DragFile DragFile;
typedef struct _DragFileClass DragFileClass;
typedef struct _DragFilePrivate DragFilePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block19Data Block19Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block20Data Block20Data;
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_thread_unref0(var) ((var == NULL) ? NULL : (var = (g_thread_unref (var), NULL)))

struct _DragFile {
	GObject parent_instance;
	DragFilePrivate * priv;
};

struct _DragFileClass {
	GObjectClass parent_class;
};

struct _DragFilePrivate {
	GtkButton* paste;
	GtkSpinner* spinner;
};

struct _Block19Data {
	int _ref_count_;
	DragFile* self;
	gchar* uri;
};

struct _Block20Data {
	int _ref_count_;
	Block19Data * _data19_;
	gchar* json;
};


static gpointer drag_file_parent_class = NULL;
extern GtkButton* main_window_paste;

GType drag_file_get_type (void) G_GNUC_CONST;
#define DRAG_FILE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_DRAG_FILE, DragFilePrivate))
enum  {
	DRAG_FILE_DUMMY_PROPERTY
};
#define DRAG_FILE_HASTEBIN_HOST "hastebin.com"
void drag_file_attach_spinner (DragFile* self, GtkBox* box);
void drag_file_attach_button (DragFile* self, GtkButton* _paste);
void drag_file_reset_ui (DragFile* self);
static gboolean __lambda6_ (DragFile* self);
static gboolean ___lambda6__gsource_func (gpointer self);
void drag_file_drop_file (DragFile* self, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint info, guint time_);
static Block19Data* block19_data_ref (Block19Data* _data19_);
static void block19_data_unref (void * _userdata_);
static gint ____lambda7_ (Block19Data* _data19_);
static Block20Data* block20_data_ref (Block20Data* _data20_);
static void block20_data_unref (void * _userdata_);
void relay_show_error_window (const gchar* error_msg);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
static gboolean ___lambda8_ (Block20Data* _data20_);
static gboolean ____lambda8__gsource_func (gpointer self);
static gpointer _____lambda7__gthread_func (gpointer self);
DragFile* drag_file_new (void);
DragFile* drag_file_construct (GType object_type);
static void drag_file_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

const GtkTargetEntry DRAG_FILE_TARGETS[1] = {{"text/uri-list", (guint) 0, (guint) 0}};

void drag_file_attach_spinner (DragFile* self, GtkBox* box) {
	GtkSpinner* _tmp0_ = NULL;
	GtkSpinner* _tmp1_ = NULL;
	GtkSpinner* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GtkSpinner* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (box != NULL);
	_tmp0_ = (GtkSpinner*) gtk_spinner_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->spinner);
	self->priv->spinner = _tmp0_;
	_tmp1_ = self->priv->spinner;
	g_object_set (_tmp1_, "active", TRUE, NULL);
	_tmp2_ = self->priv->spinner;
	gtk_widget_hide ((GtkWidget*) _tmp2_);
	_tmp3_ = box;
	_tmp4_ = self->priv->spinner;
	gtk_box_pack_start (_tmp3_, (GtkWidget*) _tmp4_, TRUE, TRUE, (guint) 0);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void drag_file_attach_button (DragFile* self, GtkButton* _paste) {
	GtkButton* _tmp0_ = NULL;
	GtkButton* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (_paste != NULL);
	_tmp0_ = _paste;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->paste);
	self->priv->paste = _tmp1_;
}


static gboolean __lambda6_ (DragFile* self) {
	gboolean result = FALSE;
	GtkButton* _tmp0_ = NULL;
	GtkSpinner* _tmp1_ = NULL;
	_tmp0_ = self->priv->paste;
	gtk_widget_show ((GtkWidget*) _tmp0_);
	_tmp1_ = self->priv->spinner;
	gtk_widget_hide ((GtkWidget*) _tmp1_);
	result = FALSE;
	return result;
}


static gboolean ___lambda6__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda6_ ((DragFile*) self);
	return result;
}


void drag_file_reset_ui (DragFile* self) {
	g_return_if_fail (self != NULL);
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda6__gsource_func, g_object_ref (self), g_object_unref);
}


static Block19Data* block19_data_ref (Block19Data* _data19_) {
	g_atomic_int_inc (&_data19_->_ref_count_);
	return _data19_;
}


static void block19_data_unref (void * _userdata_) {
	Block19Data* _data19_;
	_data19_ = (Block19Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data19_->_ref_count_)) {
		DragFile* self;
		self = _data19_->self;
		_g_free0 (_data19_->uri);
		_g_object_unref0 (self);
		g_slice_free (Block19Data, _data19_);
	}
}


static Block20Data* block20_data_ref (Block20Data* _data20_) {
	g_atomic_int_inc (&_data20_->_ref_count_);
	return _data20_;
}


static void block20_data_unref (void * _userdata_) {
	Block20Data* _data20_;
	_data20_ = (Block20Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data20_->_ref_count_)) {
		DragFile* self;
		self = _data20_->_data19_->self;
		_g_free0 (_data20_->json);
		block19_data_unref (_data20_->_data19_);
		_data20_->_data19_ = NULL;
		g_slice_free (Block20Data, _data20_);
	}
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	g_return_val_if_fail (_tmp8_, NULL);
	_tmp13_ = end;
	if (_tmp13_ >= ((glong) 0)) {
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
		_tmp14_ = end;
		_tmp15_ = string_length;
		_tmp12_ = _tmp14_ <= _tmp15_;
	} else {
		_tmp12_ = FALSE;
	}
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp16_ = start;
	_tmp17_ = end;
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	_tmp20_ = start;
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
	result = _tmp21_;
	return result;
}


static gboolean ___lambda8_ (Block20Data* _data20_) {
	Block19Data* _data19_;
	DragFile* self;
	gboolean result = FALSE;
	GtkButton* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_data19_ = _data20_->_data19_;
	self = _data19_->self;
	_tmp0_ = main_window_paste;
	gtk_widget_show ((GtkWidget*) _tmp0_);
	_tmp1_ = _data20_->json;
	_tmp2_ = g_strconcat ("http://" DRAG_FILE_HASTEBIN_HOST "/", _tmp1_, NULL);
	_tmp3_ = _tmp2_;
	g_signal_emit_by_name (self, "file-uploaded", _tmp3_);
	_g_free0 (_tmp3_);
	drag_file_reset_ui (self);
	result = FALSE;
	return result;
}


static gboolean ____lambda8__gsource_func (gpointer self) {
	gboolean result;
	result = ___lambda8_ (self);
	return result;
}


static gint ____lambda7_ (Block19Data* _data19_) {
	DragFile* self;
	gint result = 0;
	GError * _inner_error_ = NULL;
	self = _data19_->self;
	{
		Block20Data* _data20_;
		gchar* contents = NULL;
		gchar* _tmp0_ = NULL;
		GFile* path = NULL;
		const gchar* _tmp1_ = NULL;
		GFile* _tmp2_ = NULL;
		GFileInfo* _tmp3_ = NULL;
		GFile* _tmp4_ = NULL;
		GFileInfo* _tmp5_ = NULL;
		gint64 file_size = 0LL;
		GFileInfo* _tmp6_ = NULL;
		GFileInfo* _tmp7_ = NULL;
		gint64 _tmp8_ = 0LL;
		gint64 _tmp9_ = 0LL;
		gint64 _tmp10_ = 0LL;
		GFileInputStream* _tmp17_ = NULL;
		GFile* _tmp18_ = NULL;
		GFileInputStream* _tmp19_ = NULL;
		GDataInputStream* dis = NULL;
		GDataInputStream* _tmp20_ = NULL;
		gchar* line = NULL;
		GSocketClient* client = NULL;
		GSocketClient* _tmp31_ = NULL;
		GResolver* resolver = NULL;
		GResolver* _tmp32_ = NULL;
		GList* addresses = NULL;
		GResolver* _tmp33_ = NULL;
		GList* _tmp34_ = NULL;
		GInetAddress* address = NULL;
		GList* _tmp35_ = NULL;
		gconstpointer _tmp36_ = NULL;
		GInetAddress* _tmp37_ = NULL;
		GSocketConnection* conn = NULL;
		GSocketClient* _tmp38_ = NULL;
		GInetAddress* _tmp39_ = NULL;
		GInetSocketAddress* _tmp40_ = NULL;
		GInetSocketAddress* _tmp41_ = NULL;
		GSocketConnection* _tmp42_ = NULL;
		GSocketConnection* _tmp43_ = NULL;
		GDataInputStream* input_stream = NULL;
		GSocketConnection* _tmp44_ = NULL;
		GInputStream* _tmp45_ = NULL;
		GInputStream* _tmp46_ = NULL;
		GDataInputStream* _tmp47_ = NULL;
		GDataOutputStream* output_stream = NULL;
		GSocketConnection* _tmp48_ = NULL;
		GOutputStream* _tmp49_ = NULL;
		GOutputStream* _tmp50_ = NULL;
		GDataOutputStream* _tmp51_ = NULL;
		GDataOutputStream* _tmp52_ = NULL;
		GDataOutputStream* _tmp53_ = NULL;
		GDataOutputStream* _tmp54_ = NULL;
		GDataOutputStream* _tmp55_ = NULL;
		const gchar* _tmp56_ = NULL;
		gint _tmp57_ = 0;
		gint _tmp58_ = 0;
		gchar* _tmp59_ = NULL;
		gchar* _tmp60_ = NULL;
		gchar* _tmp61_ = NULL;
		gchar* _tmp62_ = NULL;
		gchar* _tmp63_ = NULL;
		gchar* _tmp64_ = NULL;
		GDataOutputStream* _tmp65_ = NULL;
		GDataOutputStream* _tmp66_ = NULL;
		GDataOutputStream* _tmp67_ = NULL;
		const gchar* _tmp68_ = NULL;
		GDataOutputStream* _tmp69_ = NULL;
		gsize length = 0UL;
		gchar* output = NULL;
		gchar* _tmp70_ = NULL;
		gchar* _tmp71_ = NULL;
		gchar** parts = NULL;
		const gchar* _tmp91_ = NULL;
		gchar** _tmp92_ = NULL;
		gchar** _tmp93_ = NULL;
		gint parts_length1 = 0;
		gint _parts_size_ = 0;
		gboolean _tmp94_ = FALSE;
		gchar** _tmp95_ = NULL;
		gint _tmp95__length1 = 0;
		_data20_ = g_slice_new0 (Block20Data);
		_data20_->_ref_count_ = 1;
		_data20_->_data19_ = block19_data_ref (_data19_);
		_tmp0_ = g_strdup ("");
		contents = _tmp0_;
		_tmp1_ = _data19_->uri;
		_tmp2_ = g_file_new_for_uri (_tmp1_);
		path = _tmp2_;
		_tmp4_ = path;
		_tmp5_ = g_file_query_info (_tmp4_, "*", G_FILE_QUERY_INFO_NONE, NULL, &_inner_error_);
		_tmp3_ = _tmp5_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp6_ = _tmp3_;
		_tmp3_ = NULL;
		_tmp7_ = _tmp6_;
		_tmp8_ = g_file_info_get_size (_tmp7_);
		_tmp9_ = _tmp8_;
		_g_object_unref0 (_tmp7_);
		file_size = _tmp9_;
		_tmp10_ = file_size;
		if (_tmp10_ > ((gint64) 500000)) {
			const gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
			gchar* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			const gchar* _tmp16_ = NULL;
			_tmp11_ = _data19_->uri;
			_tmp12_ = g_strconcat ("The file ", _tmp11_, NULL);
			_tmp13_ = _tmp12_;
			_tmp14_ = g_strconcat (_tmp13_, " is too large", NULL);
			_tmp15_ = _tmp14_;
			_tmp16_ = _ (_tmp15_);
			relay_show_error_window (_tmp16_);
			_g_free0 (_tmp15_);
			_g_free0 (_tmp13_);
			result = 1;
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			return result;
		}
		_tmp18_ = path;
		_tmp19_ = g_file_read (_tmp18_, NULL, &_inner_error_);
		_tmp17_ = _tmp19_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp20_ = g_data_input_stream_new ((GInputStream*) _tmp17_);
		dis = _tmp20_;
		while (TRUE) {
			gchar* _tmp21_ = NULL;
			GDataInputStream* _tmp22_ = NULL;
			gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			const gchar* _tmp25_ = NULL;
			const gchar* _tmp26_ = NULL;
			const gchar* _tmp27_ = NULL;
			gchar* _tmp28_ = NULL;
			gchar* _tmp29_ = NULL;
			gchar* _tmp30_ = NULL;
			_tmp22_ = dis;
			_tmp23_ = g_data_input_stream_read_line (_tmp22_, NULL, NULL, &_inner_error_);
			_tmp21_ = _tmp23_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				_g_free0 (line);
				_g_object_unref0 (dis);
				_g_object_unref0 (_tmp17_);
				_g_object_unref0 (_tmp3_);
				_g_object_unref0 (path);
				_g_free0 (contents);
				block20_data_unref (_data20_);
				_data20_ = NULL;
				goto __catch15_g_error;
			}
			_tmp24_ = _tmp21_;
			_tmp21_ = NULL;
			_g_free0 (line);
			line = _tmp24_;
			_tmp25_ = line;
			if (!(_tmp25_ != NULL)) {
				_g_free0 (_tmp21_);
				break;
			}
			_tmp26_ = contents;
			_tmp27_ = line;
			_tmp28_ = g_strconcat (_tmp27_, "\n", NULL);
			_tmp29_ = _tmp28_;
			_tmp30_ = g_strconcat (_tmp26_, _tmp29_, NULL);
			_g_free0 (contents);
			contents = _tmp30_;
			_g_free0 (_tmp29_);
			_g_free0 (_tmp21_);
		}
		_tmp31_ = g_socket_client_new ();
		client = _tmp31_;
		_tmp32_ = g_resolver_get_default ();
		resolver = _tmp32_;
		_tmp33_ = resolver;
		_tmp34_ = g_resolver_lookup_by_name (_tmp33_, DRAG_FILE_HASTEBIN_HOST, NULL, &_inner_error_);
		addresses = _tmp34_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp35_ = addresses;
		_tmp36_ = g_list_nth_data (_tmp35_, (guint) 0);
		_tmp37_ = _g_object_ref0 ((GInetAddress*) _tmp36_);
		address = _tmp37_;
		_tmp38_ = client;
		_tmp39_ = address;
		_tmp40_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp39_, (guint16) 80);
		_tmp41_ = _tmp40_;
		_tmp42_ = g_socket_client_connect (_tmp38_, (GSocketConnectable*) _tmp41_, NULL, &_inner_error_);
		_tmp43_ = _tmp42_;
		_g_object_unref0 (_tmp41_);
		conn = _tmp43_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp44_ = conn;
		_tmp45_ = g_io_stream_get_input_stream ((GIOStream*) _tmp44_);
		_tmp46_ = _tmp45_;
		_tmp47_ = g_data_input_stream_new (_tmp46_);
		input_stream = _tmp47_;
		_tmp48_ = conn;
		_tmp49_ = g_io_stream_get_output_stream ((GIOStream*) _tmp48_);
		_tmp50_ = _tmp49_;
		_tmp51_ = g_data_output_stream_new (_tmp50_);
		output_stream = _tmp51_;
		_tmp52_ = output_stream;
		g_data_output_stream_put_string (_tmp52_, "POST /documents HTTP/1.0\r\n", NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp53_ = output_stream;
		g_data_output_stream_put_string (_tmp53_, "Host: hastebin.com\r\n", NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp54_ = output_stream;
		g_data_output_stream_put_string (_tmp54_, "Accept: */*\r\n", NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp55_ = output_stream;
		_tmp56_ = contents;
		_tmp57_ = strlen (_tmp56_);
		_tmp58_ = _tmp57_;
		_tmp59_ = g_strdup_printf ("%i", _tmp58_);
		_tmp60_ = _tmp59_;
		_tmp61_ = g_strconcat ("Content-Length: ", _tmp60_, NULL);
		_tmp62_ = _tmp61_;
		_tmp63_ = g_strconcat (_tmp62_, "\r\n", NULL);
		_tmp64_ = _tmp63_;
		g_data_output_stream_put_string (_tmp55_, _tmp64_, NULL, &_inner_error_);
		_g_free0 (_tmp64_);
		_g_free0 (_tmp62_);
		_g_free0 (_tmp60_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp65_ = output_stream;
		g_data_output_stream_put_string (_tmp65_, "Content-Type: application/x-www-form-urlencoded\r\n", NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp66_ = output_stream;
		g_data_output_stream_put_string (_tmp66_, "\r\n", NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp67_ = output_stream;
		_tmp68_ = contents;
		g_data_output_stream_put_string (_tmp67_, _tmp68_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp69_ = output_stream;
		g_output_stream_flush ((GOutputStream*) _tmp69_, NULL, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			goto __catch15_g_error;
		}
		_tmp70_ = g_strdup ("");
		output = _tmp70_;
		_tmp71_ = g_strdup ("");
		_data20_->json = _tmp71_;
		{
			gboolean _tmp72_ = FALSE;
			_tmp72_ = TRUE;
			while (TRUE) {
				gchar* _tmp74_ = NULL;
				GDataInputStream* _tmp75_ = NULL;
				gsize _tmp76_ = 0UL;
				gchar* _tmp77_ = NULL;
				gchar* _tmp78_ = NULL;
				gboolean _tmp79_ = FALSE;
				gboolean _tmp80_ = FALSE;
				const gchar* _tmp81_ = NULL;
				if (!_tmp72_) {
					const gchar* _tmp73_ = NULL;
					_tmp73_ = output;
					if (!(_tmp73_ != NULL)) {
						break;
					}
				}
				_tmp72_ = FALSE;
				_tmp75_ = input_stream;
				_tmp77_ = g_data_input_stream_read_line (_tmp75_, &_tmp76_, NULL, &_inner_error_);
				length = _tmp76_;
				_tmp74_ = _tmp77_;
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_free0 (output);
					_g_object_unref0 (output_stream);
					_g_object_unref0 (input_stream);
					_g_object_unref0 (conn);
					_g_object_unref0 (address);
					__g_list_free__g_object_unref0_0 (addresses);
					_g_object_unref0 (resolver);
					_g_object_unref0 (client);
					_g_free0 (line);
					_g_object_unref0 (dis);
					_g_object_unref0 (_tmp17_);
					_g_object_unref0 (_tmp3_);
					_g_object_unref0 (path);
					_g_free0 (contents);
					block20_data_unref (_data20_);
					_data20_ = NULL;
					goto __catch15_g_error;
				}
				_tmp78_ = _tmp74_;
				_tmp74_ = NULL;
				_g_free0 (output);
				output = _tmp78_;
				_tmp81_ = output;
				if (_tmp81_ != NULL) {
					const gchar* _tmp82_ = NULL;
					gchar _tmp83_ = '\0';
					_tmp82_ = output;
					_tmp83_ = string_get (_tmp82_, (glong) 0);
					_tmp80_ = _tmp83_ == '{';
				} else {
					_tmp80_ = FALSE;
				}
				if (_tmp80_) {
					const gchar* _tmp84_ = NULL;
					const gchar* _tmp85_ = NULL;
					gint _tmp86_ = 0;
					gint _tmp87_ = 0;
					gchar _tmp88_ = '\0';
					_tmp84_ = output;
					_tmp85_ = output;
					_tmp86_ = strlen (_tmp85_);
					_tmp87_ = _tmp86_;
					_tmp88_ = string_get (_tmp84_, (glong) (_tmp87_ - 1));
					_tmp79_ = _tmp88_ == '}';
				} else {
					_tmp79_ = FALSE;
				}
				if (_tmp79_) {
					const gchar* _tmp89_ = NULL;
					gchar* _tmp90_ = NULL;
					_tmp89_ = output;
					_tmp90_ = g_strdup (_tmp89_);
					_g_free0 (_data20_->json);
					_data20_->json = _tmp90_;
				}
				_g_free0 (_tmp74_);
			}
		}
		_tmp91_ = _data20_->json;
		_tmp93_ = _tmp92_ = g_strsplit (_tmp91_, ":", 0);
		parts = _tmp93_;
		parts_length1 = _vala_array_length (_tmp92_);
		_parts_size_ = parts_length1;
		_tmp95_ = parts;
		_tmp95__length1 = parts_length1;
		if (_tmp95_ != NULL) {
			gchar** _tmp96_ = NULL;
			gint _tmp96__length1 = 0;
			_tmp96_ = parts;
			_tmp96__length1 = parts_length1;
			_tmp94_ = _tmp96__length1 > 1;
		} else {
			_tmp94_ = FALSE;
		}
		if (_tmp94_) {
			gchar** _tmp97_ = NULL;
			gint _tmp97__length1 = 0;
			const gchar* _tmp98_ = NULL;
			gchar** _tmp99_ = NULL;
			gint _tmp99__length1 = 0;
			const gchar* _tmp100_ = NULL;
			gint _tmp101_ = 0;
			gint _tmp102_ = 0;
			gchar* _tmp103_ = NULL;
			_tmp97_ = parts;
			_tmp97__length1 = parts_length1;
			_tmp98_ = _tmp97_[1];
			_tmp99_ = parts;
			_tmp99__length1 = parts_length1;
			_tmp100_ = _tmp99_[1];
			_tmp101_ = strlen (_tmp100_);
			_tmp102_ = _tmp101_;
			_tmp103_ = string_slice (_tmp98_, (glong) 1, (glong) (_tmp102_ - 2));
			_g_free0 (_data20_->json);
			_data20_->json = _tmp103_;
		} else {
			const gchar* _tmp104_ = NULL;
			_tmp104_ = _ ("The message returned was not formed correctly.");
			relay_show_error_window (_tmp104_);
			result = 1;
			parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
			_g_free0 (output);
			_g_object_unref0 (output_stream);
			_g_object_unref0 (input_stream);
			_g_object_unref0 (conn);
			_g_object_unref0 (address);
			__g_list_free__g_object_unref0_0 (addresses);
			_g_object_unref0 (resolver);
			_g_object_unref0 (client);
			_g_free0 (line);
			_g_object_unref0 (dis);
			_g_object_unref0 (_tmp17_);
			_g_object_unref0 (_tmp3_);
			_g_object_unref0 (path);
			_g_free0 (contents);
			block20_data_unref (_data20_);
			_data20_ = NULL;
			return result;
		}
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ____lambda8__gsource_func, block20_data_ref (_data20_), block20_data_unref);
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (output);
		_g_object_unref0 (output_stream);
		_g_object_unref0 (input_stream);
		_g_object_unref0 (conn);
		_g_object_unref0 (address);
		__g_list_free__g_object_unref0_0 (addresses);
		_g_object_unref0 (resolver);
		_g_object_unref0 (client);
		_g_free0 (line);
		_g_object_unref0 (dis);
		_g_object_unref0 (_tmp17_);
		_g_object_unref0 (_tmp3_);
		_g_object_unref0 (path);
		_g_free0 (contents);
		block20_data_unref (_data20_);
		_data20_ = NULL;
	}
	goto __finally15;
	__catch15_g_error:
	{
		GError* e = NULL;
		GError* _tmp105_ = NULL;
		const gchar* _tmp106_ = NULL;
		GError* _tmp107_ = NULL;
		const gchar* _tmp108_ = NULL;
		gchar* _tmp109_ = NULL;
		gchar* _tmp110_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		drag_file_reset_ui (self);
		_tmp105_ = e;
		_tmp106_ = _tmp105_->message;
		relay_show_error_window (_tmp106_);
		_tmp107_ = e;
		_tmp108_ = _tmp107_->message;
		_tmp109_ = g_strconcat ("Could not upload ", _tmp108_, NULL);
		_tmp110_ = _tmp109_;
		g_warning ("drag_file.vala:126: %s", _tmp110_);
		_g_free0 (_tmp110_);
		_g_error_free0 (e);
	}
	__finally15:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	return result;
}


static gpointer _____lambda7__gthread_func (gpointer self) {
	gpointer result;
	result = (gpointer) ((gintptr) ____lambda7_ (self));
	block19_data_unref (self);
	return result;
}


void drag_file_drop_file (DragFile* self, GdkDragContext* context, gint x, gint y, GtkSelectionData* selection_data, guint info, guint time_) {
	GtkButton* _tmp0_ = NULL;
	GtkSpinner* _tmp1_ = NULL;
	GtkSelectionData* _tmp2_ = NULL;
	gchar** _tmp3_ = NULL;
	gchar** _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (context != NULL);
	g_return_if_fail (selection_data != NULL);
	_tmp0_ = self->priv->paste;
	gtk_widget_hide ((GtkWidget*) _tmp0_);
	_tmp1_ = self->priv->spinner;
	gtk_widget_show ((GtkWidget*) _tmp1_);
	_tmp2_ = selection_data;
	_tmp4_ = _tmp3_ = gtk_selection_data_get_uris (_tmp2_);
	{
		gchar** uri_collection = NULL;
		gint uri_collection_length1 = 0;
		gint _uri_collection_size_ = 0;
		gint uri_it = 0;
		uri_collection = _tmp4_;
		uri_collection_length1 = _vala_array_length (_tmp3_);
		for (uri_it = 0; uri_it < _vala_array_length (_tmp3_); uri_it = uri_it + 1) {
			gchar* _tmp5_ = NULL;
			gchar* uri = NULL;
			_tmp5_ = g_strdup (uri_collection[uri_it]);
			uri = _tmp5_;
			{
				Block19Data* _data19_;
				GThread* _tmp6_ = NULL;
				GThread* _tmp7_ = NULL;
				_data19_ = g_slice_new0 (Block19Data);
				_data19_->_ref_count_ = 1;
				_data19_->self = g_object_ref (self);
				_data19_->uri = uri;
				_tmp6_ = g_thread_new ("Pastebin post", _____lambda7__gthread_func, block19_data_ref (_data19_));
				_tmp7_ = _tmp6_;
				_g_thread_unref0 (_tmp7_);
				block19_data_unref (_data19_);
				_data19_ = NULL;
			}
		}
		uri_collection = (_vala_array_free (uri_collection, uri_collection_length1, (GDestroyNotify) g_free), NULL);
	}
}


DragFile* drag_file_construct (GType object_type) {
	DragFile * self = NULL;
	self = (DragFile*) g_object_new (object_type, NULL);
	return self;
}


DragFile* drag_file_new (void) {
	return drag_file_construct (TYPE_DRAG_FILE);
}


static void drag_file_class_init (DragFileClass * klass) {
	drag_file_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (DragFilePrivate));
	G_OBJECT_CLASS (klass)->finalize = drag_file_finalize;
	g_signal_new ("file_uploaded", TYPE_DRAG_FILE, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
}


static void drag_file_instance_init (DragFile * self) {
	self->priv = DRAG_FILE_GET_PRIVATE (self);
}


static void drag_file_finalize (GObject* obj) {
	DragFile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_DRAG_FILE, DragFile);
	_g_object_unref0 (self->priv->paste);
	_g_object_unref0 (self->priv->spinner);
	G_OBJECT_CLASS (drag_file_parent_class)->finalize (obj);
}


GType drag_file_get_type (void) {
	static volatile gsize drag_file_type_id__volatile = 0;
	if (g_once_init_enter (&drag_file_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DragFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) drag_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DragFile), 0, (GInstanceInitFunc) drag_file_instance_init, NULL };
		GType drag_file_type_id;
		drag_file_type_id = g_type_register_static (G_TYPE_OBJECT, "DragFile", &g_define_type_info, 0);
		g_once_init_leave (&drag_file_type_id__volatile, drag_file_type_id);
	}
	return drag_file_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



