/* irc.c generated by valac 0.34.4, the Vala compiler
 * generated from irc.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * irc.vala
 * Copyright (C) 2015 Kyle Agronick <agronick@gmail.com>
 *
 * KyRC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KyRC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_IRC (irc_get_type ())
#define IRC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_IRC, IRC))
#define IRC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_IRC, IRCClass))
#define IS_IRC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_IRC))
#define IS_IRC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_IRC))
#define IRC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_IRC, IRCClass))

typedef struct _IRC IRC;
typedef struct _IRCClass IRCClass;
typedef struct _IRCPrivate IRCPrivate;
typedef struct _ParamSpecIRC ParamSpecIRC;

struct _IRC {
	GTypeInstance parent_instance;
	volatile int ref_count;
	IRCPrivate * priv;
};

struct _IRCClass {
	GTypeClass parent_class;
	void (*finalize) (IRC *self);
};

struct _ParamSpecIRC {
	GParamSpec parent_instance;
};


static gpointer irc_parent_class = NULL;

gpointer irc_ref (gpointer instance);
void irc_unref (gpointer instance);
GParamSpec* param_spec_irc (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_irc (GValue* value, gpointer v_object);
void value_take_irc (GValue* value, gpointer v_object);
gpointer value_get_irc (const GValue* value);
GType irc_get_type (void) G_GNUC_CONST;
enum  {
	IRC_DUMMY_PROPERTY
};
#define IRC_DEFAULT_PORT ((guint16) 6667)
#define IRC_USER_LENGTH 18
#define IRC_USER_WIDTH 126
#define IRC_user_prefixes "~&@%+"
#define IRC_spacers " ,:/\\{}[];$#@!)(*&^\n\t\r"
#define IRC_RPL_WELCOME "001"
#define IRC_RPL_YOURHOST "002"
#define IRC_RPL_CREATED "003"
#define IRC_RPL_MYINFO "004"
#define IRC_RPL_BOUNCE "005"
#define IRC_RPL_AWAY "301"
#define IRC_RPL_UNAWAY "305"
#define IRC_RPL_NOWAWAY "306"
#define IRC_RPL_WHOISUSER "311"
#define IRC_RPL_WHOISSERVER "312"
#define IRC_RPL_WHOISOPERATOR "313"
#define IRC_RPL_WHOISCHANNELS "319"
#define IRC_RPL_WHOISIDLE "317"
#define IRC_RPL_ENDOFWHOIS "318"
#define IRC_RPL_LIST "322"
#define IRC_RPL_LISTEND "323"
#define IRC_RPL_CHANNELMODEIS "324"
#define IRC_RPL_CHANNEL_URL "328"
#define IRC_RPL_AUTHEDAS "330"
#define IRC_RPL_NOTOPIC "331"
#define IRC_RPL_TOPIC "332"
#define IRC_RPL_VERSION "351"
#define IRC_RPL_NAMREPLY "353"
#define IRC_RPL_ENDOFNAMES "366"
#define IRC_RPL_MOTD "372"
#define IRC_RPL_MOTDSTART "375"
#define IRC_RPL_ENDOFMOTD "376"
#define IRC_RPL_LUSEROP "252"
#define IRC_RPL_UMODEIS "221"
#define IRC_RPL_SERVLIST "234"
#define IRC_RPL_ENDOFSTATS "219"
#define IRC_RPL_STATSCOMMANDS "212"
#define IRC_RPL_STATSLINKINFO "211"
#define IRC_RPL_LUSERUNKNOWN "253"
#define IRC_RPL_LUSERCHANNELS "254"
#define IRC_RPL_LUSERME "255"
#define IRC_RPL_LUSERCLIENT "251"
#define IRC_PRIVATE_MESSAGE "PRIVMSG"
#define IRC_USER_NAME_CHANGED "NICK"
#define IRC_QUIT_MSG "QUIT"
#define IRC_JOIN_MSG "JOIN"
#define IRC_PART_MSG "PART"
#define IRC_ERR_NOSUCHNICK "401"
#define IRC_ERR_NOSUCHCHANNEL "403"
#define IRC_ERR_WASNOSUCHNICK "406"
#define IRC_ERR_UNKNOWNCOMMAND "421"
#define IRC_ERR_NOMOTD "422"
#define IRC_ERR_NONICKNAMEGIVEN "431"
#define IRC_ERR_NICKNAMEINUSE "433"
#define IRC_ERR_USERNOTINCHANNEL "441"
#define IRC_ERR_NOTONCHANNEL "442"
#define IRC_ERR_NOTREGISTERED "451"
#define IRC_ERR_NEEDMOREPARAMS "461"
#define IRC_ERR_LINKCHANNEL "470"
#define IRC_ERR_UNKNOWNMODE "472"
#define IRC_ERR_ALREADYONCHANNEL "479"
#define IRC_ERR_CHANOPRIVSNEEDED "482"
#define IRC_ERR_NONONREG "486"
gchar* irc_remove_user_prefix (const gchar* name);
IRC* irc_new (void);
IRC* irc_construct (GType object_type);
static void irc_finalize (IRC* obj);


static gint string_index_of_char (const gchar* self, gunichar c, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	gunichar _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = c;
	_tmp2_ = g_utf8_strchr (((gchar*) self) + _tmp0_, (gssize) -1, _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


gchar* irc_remove_user_prefix (const gchar* name) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar _tmp1_ = '\0';
	gint _tmp2_ = 0;
	const gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = string_get (_tmp0_, (glong) 0);
	_tmp2_ = string_index_of_char (IRC_user_prefixes, (gunichar) _tmp1_, 0);
	if (_tmp2_ != -1) {
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		_tmp3_ = name;
		_tmp4_ = string_substring (_tmp3_, (glong) 1, (glong) -1);
		result = _tmp4_;
		return result;
	}
	_tmp5_ = name;
	_tmp6_ = g_strdup (_tmp5_);
	result = _tmp6_;
	return result;
}


IRC* irc_construct (GType object_type) {
	IRC* self = NULL;
	self = (IRC*) g_type_create_instance (object_type);
	return self;
}


IRC* irc_new (void) {
	return irc_construct (TYPE_IRC);
}


static void value_irc_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_irc_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		irc_unref (value->data[0].v_pointer);
	}
}


static void value_irc_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = irc_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_irc_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_irc_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		IRC* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = irc_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_irc_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	IRC** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = irc_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_irc (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecIRC* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_IRC), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_irc (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_IRC), NULL);
	return value->data[0].v_pointer;
}


void value_set_irc (GValue* value, gpointer v_object) {
	IRC* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_IRC));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_IRC));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		irc_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		irc_unref (old);
	}
}


void value_take_irc (GValue* value, gpointer v_object) {
	IRC* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_IRC));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_IRC));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		irc_unref (old);
	}
}


static void irc_class_init (IRCClass * klass) {
	irc_parent_class = g_type_class_peek_parent (klass);
	((IRCClass *) klass)->finalize = irc_finalize;
}


static void irc_instance_init (IRC * self) {
	self->ref_count = 1;
}


static void irc_finalize (IRC* obj) {
	IRC * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_IRC, IRC);
	g_signal_handlers_destroy (self);
}


GType irc_get_type (void) {
	static volatile gsize irc_type_id__volatile = 0;
	if (g_once_init_enter (&irc_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_irc_init, value_irc_free_value, value_irc_copy_value, value_irc_peek_pointer, "p", value_irc_collect_value, "p", value_irc_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (IRCClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) irc_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IRC), 0, (GInstanceInitFunc) irc_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType irc_type_id;
		irc_type_id = g_type_register_fundamental (g_type_fundamental_next (), "IRC", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&irc_type_id__volatile, irc_type_id);
	}
	return irc_type_id__volatile;
}


gpointer irc_ref (gpointer instance) {
	IRC* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void irc_unref (gpointer instance) {
	IRC* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		IRC_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



