/* message.c generated by valac 0.34.4, the Vala compiler
 * generated from message.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * message.vala
 * Copyright (C) 2015 Kyle Agronick <stack@kyle-ele>
     *
 * KyRC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
     *
 * KyRC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_MESSAGE (message_get_type ())
#define MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MESSAGE, Message))
#define MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MESSAGE, MessageClass))
#define IS_MESSAGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MESSAGE))
#define IS_MESSAGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MESSAGE))
#define MESSAGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MESSAGE, MessageClass))

typedef struct _Message Message;
typedef struct _MessageClass MessageClass;
typedef struct _MessagePrivate MessagePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Message {
	GObject parent_instance;
	MessagePrivate * priv;
	gchar* user_name;
	gboolean internal;
	gboolean usr_private_message;
};

struct _MessageClass {
	GObjectClass parent_class;
};

struct _MessagePrivate {
	gchar* _message;
	gchar* _prefix;
	gchar* _command;
	gchar** _parameters;
	gint _parameters_length1;
	gint __parameters_size_;
};


static gpointer message_parent_class = NULL;
static GRegex* message_regex;
static GRegex* message_regex = NULL;
static GRegex* message_fix_message;
static GRegex* message_fix_message = NULL;
static gchar* message_regex_string;
static gchar* message_regex_string = NULL;
static gchar* message_replace_string;
static gchar* message_replace_string = NULL;
extern gchar** message_user_cmds;
extern gint message_user_cmds_length1;
gchar** message_user_cmds = NULL;
gint message_user_cmds_length1 = 0;

GType message_get_type (void) G_GNUC_CONST;
#define MESSAGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MESSAGE, MessagePrivate))
enum  {
	MESSAGE_DUMMY_PROPERTY,
	MESSAGE_MESSAGE,
	MESSAGE_PREFIX,
	MESSAGE_COMMAND,
	MESSAGE_PARAMETERS
};
#define IRC_PRIVATE_MESSAGE "PRIVMSG"
#define IRC_JOIN_MSG "JOIN"
#define IRC_USER_NAME_CHANGED "NICK"
#define IRC_QUIT_MSG "QUIT"
#define IRC_PART_MSG "PART"
Message* message_new (const gchar* _message);
Message* message_construct (GType object_type, const gchar* _message);
void message_set_message (Message* self, const gchar* value);
void message_parse_regex (Message* self);
gchar* message_get_prefix_name (Message* self);
const gchar* message_get_prefix (Message* self);
const gchar* message_get_command (Message* self);
void message_user_name_set (Message* self, const gchar* name);
gchar* message_user_name_get (Message* self);
#define IRC_USER_LENGTH 18
gchar* message_get_msg_txt (Message* self);
const gchar* message_get_message (Message* self);
static gboolean ___lambda9_ (Message* self, GMatchInfo* mi, GString* s);
void message_set_prefix (Message* self, const gchar* value);
void message_set_command (Message* self, const gchar* value);
void message_set_parameters (Message* self, gchar** value, int value_length1);
static gboolean _vala_string_array_contains (gchar** stack, int stack_length, gchar* needle);
static gboolean ____lambda9__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self);
gchar** message_get_parameters (Message* self, int* result_length1);
static gchar** _vala_array_dup2 (gchar** self, int length);
static void message_finalize (GObject* obj);
static void _vala_message_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_message_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


Message* message_construct (GType object_type, const gchar* _message) {
	Message * self = NULL;
	GRegex* _tmp0_ = NULL;
	const gchar* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (_message != NULL, NULL);
	self = (Message*) g_object_new (object_type, NULL);
	_tmp0_ = message_regex;
	if (_tmp0_ == NULL) {
		{
			GRegex* _tmp1_ = NULL;
			const gchar* _tmp2_ = NULL;
			GRegex* _tmp3_ = NULL;
			GRegex* _tmp4_ = NULL;
			_tmp2_ = message_regex_string;
			_tmp3_ = g_regex_new (_tmp2_, G_REGEX_OPTIMIZE, 0, &_inner_error_);
			_tmp1_ = _tmp3_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				if (_inner_error_->domain == G_REGEX_ERROR) {
					goto __catch4_g_regex_error;
				}
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return NULL;
			}
			_tmp4_ = _tmp1_;
			_tmp1_ = NULL;
			_g_regex_unref0 (message_regex);
			message_regex = _tmp4_;
			_g_regex_unref0 (_tmp1_);
		}
		goto __finally4;
		__catch4_g_regex_error:
		{
			GError* e = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			g_error ("message.vala:44: There was a regex error that should never happen");
			_g_error_free0 (e);
		}
		__finally4:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	_tmp5_ = _message;
	_tmp6_ = strlen (_tmp5_);
	_tmp7_ = _tmp6_;
	if (_tmp7_ == 0) {
		return self;
	}
	{
		gchar* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		gboolean _tmp10_ = FALSE;
		_tmp9_ = _message;
		_tmp10_ = g_utf8_validate (_tmp9_, (gssize) -1, NULL);
		if (_tmp10_) {
			const gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
			_tmp11_ = _message;
			_tmp12_ = g_strdup (_tmp11_);
			_g_free0 (_tmp8_);
			_tmp8_ = _tmp12_;
		} else {
			const gchar* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			_tmp13_ = _message;
			_tmp14_ = g_strescape (_tmp13_, "\b\f\n\r\t\'");
			_g_free0 (_tmp8_);
			_tmp8_ = _tmp14_;
		}
		message_set_message (self, _tmp8_);
		_g_free0 (_tmp8_);
	}
	goto __finally5;
	__catch5_g_regex_error:
	{
		GError* e = NULL;
		const gchar* _tmp15_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp15_ = _message;
		message_set_message (self, _tmp15_);
		_g_error_free0 (e);
	}
	__finally5:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	message_parse_regex (self);
	return self;
}


Message* message_new (const gchar* _message) {
	return message_construct (TYPE_MESSAGE, _message);
}


static gint string_index_of_char (const gchar* self, gunichar c, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	gunichar _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = c;
	_tmp2_ = g_utf8_strchr (((gchar*) self) + _tmp0_, (gssize) -1, _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


gchar* message_get_prefix_name (Message* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_prefix;
	_tmp1_ = string_index_of_char (_tmp0_, (gunichar) '!', 0);
	if (_tmp1_ == -1) {
		gchar* _tmp2_ = NULL;
		_tmp2_ = g_strdup ("");
		result = _tmp2_;
		return result;
	}
	_tmp3_ = self->priv->_command;
	if (g_strcmp0 (_tmp3_, IRC_PRIVATE_MESSAGE) == 0) {
		self->usr_private_message = TRUE;
	}
	_tmp4_ = self->priv->_prefix;
	if (_tmp4_ != NULL) {
		const gchar* _tmp5_ = NULL;
		gchar** _tmp6_ = NULL;
		gchar** _tmp7_ = NULL;
		gchar** _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		const gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		_tmp5_ = self->priv->_prefix;
		_tmp7_ = _tmp6_ = g_strsplit (_tmp5_, "!", 0);
		_tmp8_ = _tmp7_;
		_tmp8__length1 = _vala_array_length (_tmp6_);
		_tmp9_ = _tmp8_[0];
		_tmp10_ = g_strdup (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
		result = _tmp11_;
		return result;
	}
	_tmp12_ = g_strdup ("");
	result = _tmp12_;
	return result;
}


void message_user_name_set (Message* self, const gchar* name) {
	const gchar* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = name;
	if (_tmp0_ != NULL) {
		const gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		_tmp1_ = name;
		_tmp2_ = g_strdup (_tmp1_);
		_g_free0 (self->user_name);
		self->user_name = _tmp2_;
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


gchar* message_user_name_get (Message* self) {
	gchar* result = NULL;
	gchar* name = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint length = 0;
	const gchar* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->user_name;
	_tmp1_ = g_strdup (_tmp0_);
	name = _tmp1_;
	_tmp2_ = name;
	_tmp3_ = strlen (_tmp2_);
	_tmp4_ = _tmp3_;
	if (_tmp4_ >= IRC_USER_LENGTH) {
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		_tmp5_ = self->user_name;
		_tmp6_ = string_substring (_tmp5_, (glong) 0, (glong) (IRC_USER_LENGTH - 3));
		_tmp7_ = _tmp6_;
		_tmp8_ = g_strconcat (_tmp7_, "...", NULL);
		_g_free0 (name);
		name = _tmp8_;
		_g_free0 (_tmp7_);
	}
	_tmp9_ = name;
	_tmp10_ = strlen (_tmp9_);
	_tmp11_ = _tmp10_;
	length = IRC_USER_LENGTH - _tmp11_;
	_tmp12_ = name;
	_tmp13_ = g_strnfill ((gsize) length, ' ');
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp12_, _tmp14_, NULL);
	_tmp16_ = _tmp15_;
	_tmp17_ = g_strconcat (_tmp16_, "\t", NULL);
	_tmp18_ = _tmp17_;
	_g_free0 (_tmp16_);
	_g_free0 (_tmp14_);
	result = _tmp18_;
	_g_free0 (name);
	return result;
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


gchar* message_get_msg_txt (Message* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = self->priv->_message;
	if (_tmp1_ == NULL) {
		gchar* _tmp2_ = NULL;
		_tmp2_ = g_strdup ("");
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp2_;
	} else {
		const gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		_tmp3_ = self->priv->_message;
		_tmp4_ = string_strip (_tmp3_);
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp4_;
	}
	result = _tmp0_;
	return result;
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch7_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp6_ = regex;
		_tmp7_ = replacement;
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) -1, 0, _tmp7_, 0, &_inner_error_);
		_tmp5_ = _tmp8_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch7_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp9_ = _tmp5_;
		_tmp5_ = NULL;
		result = _tmp9_;
		_g_free0 (_tmp5_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally7;
	__catch7_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally7:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gboolean _vala_string_array_contains (gchar** stack, int stack_length, gchar* needle) {
	int i;
	for (i = 0; i < stack_length; i++) {
		if (g_strcmp0 (stack[i], needle) == 0) {
			return TRUE;
		}
	}
	return FALSE;
}


static gboolean ___lambda9_ (Message* self, GMatchInfo* mi, GString* s) {
	gboolean result = FALSE;
	GMatchInfo* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	GMatchInfo* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	GMatchInfo* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	GMatchInfo* _tmp16_ = NULL;
	gchar* _tmp17_ = NULL;
	gchar* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	const gchar* _tmp23_ = NULL;
	g_return_val_if_fail (mi != NULL, FALSE);
	g_return_val_if_fail (s != NULL, FALSE);
	_tmp0_ = mi;
	_tmp1_ = g_match_info_fetch_named (_tmp0_, "prefix");
	_tmp2_ = _tmp1_;
	message_set_prefix (self, _tmp2_);
	_g_free0 (_tmp2_);
	_tmp3_ = mi;
	_tmp4_ = g_match_info_fetch_named (_tmp3_, "command");
	_tmp5_ = _tmp4_;
	message_set_command (self, _tmp5_);
	_g_free0 (_tmp5_);
	_tmp6_ = mi;
	_tmp7_ = g_match_info_fetch_named (_tmp6_, "params");
	_tmp8_ = _tmp7_;
	_tmp9_ = _tmp8_ != NULL;
	_g_free0 (_tmp8_);
	if (_tmp9_) {
		GMatchInfo* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar** _tmp13_ = NULL;
		gchar** _tmp14_ = NULL;
		gchar** _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		_tmp10_ = mi;
		_tmp11_ = g_match_info_fetch_named (_tmp10_, "params");
		_tmp12_ = _tmp11_;
		_tmp14_ = _tmp13_ = g_strsplit (_tmp12_, " ", 0);
		_tmp15_ = _tmp14_;
		_tmp15__length1 = _vala_array_length (_tmp13_);
		message_set_parameters (self, _tmp15_, _vala_array_length (_tmp13_));
		_tmp15_ = (_vala_array_free (_tmp15_, _tmp15__length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (_tmp12_);
	}
	_tmp16_ = mi;
	_tmp17_ = g_match_info_fetch_named (_tmp16_, "trail");
	_tmp18_ = _tmp17_;
	message_set_message (self, _tmp18_);
	_g_free0 (_tmp18_);
	_tmp19_ = self->priv->_message;
	if (_tmp19_ != NULL) {
		const gchar* _tmp20_ = NULL;
		gchar* _tmp21_ = NULL;
		gchar* _tmp22_ = NULL;
		_tmp20_ = self->priv->_message;
		_tmp21_ = string_replace (_tmp20_, "\t", "");
		_tmp22_ = _tmp21_;
		message_set_message (self, _tmp22_);
		_g_free0 (_tmp22_);
	}
	_tmp23_ = self->priv->_prefix;
	if (_tmp23_ != NULL) {
		const gchar* _tmp24_ = NULL;
		gchar** _tmp25_ = NULL;
		gint _tmp25__length1 = 0;
		_tmp24_ = self->priv->_command;
		_tmp25_ = message_user_cmds;
		_tmp25__length1 = message_user_cmds_length1;
		if (_vala_string_array_contains (_tmp25_, _tmp25__length1, _tmp24_)) {
			const gchar* _tmp26_ = NULL;
			gchar** _tmp27_ = NULL;
			gchar** _tmp28_ = NULL;
			gchar** _tmp29_ = NULL;
			gint _tmp29__length1 = 0;
			const gchar* _tmp30_ = NULL;
			_tmp26_ = self->priv->_prefix;
			_tmp28_ = _tmp27_ = g_strsplit (_tmp26_, "!", 0);
			_tmp29_ = _tmp28_;
			_tmp29__length1 = _vala_array_length (_tmp27_);
			_tmp30_ = _tmp29_[0];
			message_user_name_set (self, _tmp30_);
			_tmp29_ = (_vala_array_free (_tmp29_, _tmp29__length1, (GDestroyNotify) g_free), NULL);
		}
	}
	result = FALSE;
	return result;
}


static gboolean ____lambda9__gregex_eval_callback (GMatchInfo* match_info, GString* _result_, gpointer self) {
	gboolean result;
	result = ___lambda9_ ((Message*) self, match_info, _result_);
	return result;
}


void message_parse_regex (Message* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		const gchar* _tmp0_ = NULL;
		GRegex* _tmp1_ = NULL;
		const gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		_tmp0_ = self->priv->_message;
		if (_tmp0_ == NULL) {
			return;
		}
		_tmp1_ = message_regex;
		_tmp2_ = self->priv->_message;
		_tmp3_ = g_regex_replace_eval (_tmp1_, _tmp2_, (gssize) -1, 0, 0, ____lambda9__gregex_eval_callback, self, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp4_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally6;
	__catch6_g_regex_error:
	{
		GError* e = NULL;
		const gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = self->priv->_message;
		_tmp6_ = g_strconcat ("Regex error with ", _tmp5_, NULL);
		_tmp7_ = _tmp6_;
		g_warning ("message.vala:107: %s", _tmp7_);
		_g_free0 (_tmp7_);
		_g_error_free0 (e);
	}
	__finally6:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


const gchar* message_get_message (Message* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_message;
	result = _tmp0_;
	return result;
}


void message_set_message (Message* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_message);
	self->priv->_message = _tmp1_;
	g_object_notify ((GObject *) self, "message");
}


const gchar* message_get_prefix (Message* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_prefix;
	result = _tmp0_;
	return result;
}


void message_set_prefix (Message* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_prefix);
	self->priv->_prefix = _tmp1_;
	g_object_notify ((GObject *) self, "prefix");
}


const gchar* message_get_command (Message* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_command;
	result = _tmp0_;
	return result;
}


void message_set_command (Message* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_command);
	self->priv->_command = _tmp1_;
	g_object_notify ((GObject *) self, "command");
}


gchar** message_get_parameters (Message* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_parameters;
	_tmp0__length1 = self->priv->_parameters_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gchar** _vala_array_dup2 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void message_set_parameters (Message* self, gchar** value, int value_length1) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup2 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_parameters = (_vala_array_free (self->priv->_parameters, self->priv->_parameters_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_parameters = _tmp1_;
	self->priv->_parameters_length1 = _tmp1__length1;
	self->priv->__parameters_size_ = self->priv->_parameters_length1;
	g_object_notify ((GObject *) self, "parameters");
}


static void message_class_init (MessageClass * klass) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar** _tmp7_ = NULL;
	message_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MessagePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_message_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_message_set_property;
	G_OBJECT_CLASS (klass)->finalize = message_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), MESSAGE_MESSAGE, g_param_spec_string ("message", "message", "message", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MESSAGE_PREFIX, g_param_spec_string ("prefix", "prefix", "prefix", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MESSAGE_COMMAND, g_param_spec_string ("command", "command", "command", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), MESSAGE_PARAMETERS, g_param_spec_boxed ("parameters", "parameters", "parameters", G_TYPE_STRV, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	_tmp0_ = g_strdup ("^(:(?<prefix>\\S+) )?(?<command>\\S+)( (?!:)(?<params>.+?))?( :(?<trai" \
"l>.+))?$");
	message_regex_string = _tmp0_;
	_tmp1_ = g_strdup ("[\\x00-\\x1F\\x80-\\xFF]");
	message_replace_string = _tmp1_;
	_tmp2_ = g_strdup (IRC_PRIVATE_MESSAGE);
	_tmp3_ = g_strdup (IRC_JOIN_MSG);
	_tmp4_ = g_strdup (IRC_USER_NAME_CHANGED);
	_tmp5_ = g_strdup (IRC_QUIT_MSG);
	_tmp6_ = g_strdup (IRC_PART_MSG);
	_tmp7_ = g_new0 (gchar*, 5 + 1);
	_tmp7_[0] = _tmp2_;
	_tmp7_[1] = _tmp3_;
	_tmp7_[2] = _tmp4_;
	_tmp7_[3] = _tmp5_;
	_tmp7_[4] = _tmp6_;
	message_user_cmds = _tmp7_;
	message_user_cmds_length1 = 5;
}


static void message_instance_init (Message * self) {
	gchar* _tmp0_ = NULL;
	self->priv = MESSAGE_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("");
	self->user_name = _tmp0_;
	self->internal = FALSE;
	self->usr_private_message = FALSE;
}


static void message_finalize (GObject* obj) {
	Message * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MESSAGE, Message);
	_g_free0 (self->priv->_message);
	_g_free0 (self->priv->_prefix);
	_g_free0 (self->priv->_command);
	self->priv->_parameters = (_vala_array_free (self->priv->_parameters, self->priv->_parameters_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (self->user_name);
	G_OBJECT_CLASS (message_parent_class)->finalize (obj);
}


GType message_get_type (void) {
	static volatile gsize message_type_id__volatile = 0;
	if (g_once_init_enter (&message_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MessageClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) message_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Message), 0, (GInstanceInitFunc) message_instance_init, NULL };
		GType message_type_id;
		message_type_id = g_type_register_static (G_TYPE_OBJECT, "Message", &g_define_type_info, 0);
		g_once_init_leave (&message_type_id__volatile, message_type_id);
	}
	return message_type_id__volatile;
}


static void _vala_message_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Message * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MESSAGE, Message);
	switch (property_id) {
		case MESSAGE_MESSAGE:
		g_value_set_string (value, message_get_message (self));
		break;
		case MESSAGE_PREFIX:
		g_value_set_string (value, message_get_prefix (self));
		break;
		case MESSAGE_COMMAND:
		g_value_set_string (value, message_get_command (self));
		break;
		case MESSAGE_PARAMETERS:
		{
			int length;
			g_value_set_boxed (value, message_get_parameters (self, &length));
		}
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_message_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Message * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_MESSAGE, Message);
	switch (property_id) {
		case MESSAGE_MESSAGE:
		message_set_message (self, g_value_get_string (value));
		break;
		case MESSAGE_PREFIX:
		message_set_prefix (self, g_value_get_string (value));
		break;
		case MESSAGE_COMMAND:
		message_set_command (self, g_value_get_string (value));
		break;
		case MESSAGE_PARAMETERS:
		{
			gpointer boxed;
			boxed = g_value_get_boxed (value);
			message_set_parameters (self, boxed, (boxed == NULL) ? 0 : g_strv_length (boxed));
		}
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



