/* rich_text.c generated by valac 0.34.4, the Vala compiler
 * generated from rich_text.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: nil; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * rich_text.vala
 * Copyright (C) 2015 Kyle Agronick <agronick@gmail.com>
     *
 * relay is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
     * 
 * relay is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_RICH_TEXT (rich_text_get_type ())
#define RICH_TEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RICH_TEXT, RichText))
#define RICH_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RICH_TEXT, RichTextClass))
#define IS_RICH_TEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RICH_TEXT))
#define IS_RICH_TEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RICH_TEXT))
#define RICH_TEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RICH_TEXT, RichTextClass))

typedef struct _RichText RichText;
typedef struct _RichTextClass RichTextClass;
typedef struct _RichTextPrivate RichTextPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_match_info_unref0(var) ((var == NULL) ? NULL : (var = (g_match_info_unref (var), NULL)))

struct _RichText {
	GObject parent_instance;
	RichTextPrivate * priv;
	GeeLinkedList* link_locations_start;
	GeeLinkedList* link_locations_end;
	GeeLinkedList* name_location_start;
	GeeLinkedList* name_location_end;
	GeeLinkedList* names;
	gboolean has_links;
	gboolean has_names;
};

struct _RichTextClass {
	GObjectClass parent_class;
};

struct _RichTextPrivate {
	gchar* text;
};


static gpointer rich_text_parent_class = NULL;
static GRegex* rich_text_parse_url;
static GRegex* rich_text_parse_url = NULL;

GType rich_text_get_type (void) G_GNUC_CONST;
#define RICH_TEXT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_RICH_TEXT, RichTextPrivate))
enum  {
	RICH_TEXT_DUMMY_PROPERTY
};
#define RICH_TEXT_url_string "(http|https?|ftp):\\/\\/[^\\s\\/$.?#].[^\\s]*"
RichText* rich_text_new (const gchar* _text);
RichText* rich_text_construct (GType object_type, const gchar* _text);
void rich_text_parse_links (RichText* self);
void rich_text_parse_name (RichText* self, const gchar* name);
#define IRC_spacers " ,:/\\{}[];$#@!)(*&^\n\t\r"
static void rich_text_finalize (GObject* obj);


RichText* rich_text_construct (GType object_type, const gchar* _text) {
	RichText * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (_text != NULL, NULL);
	self = (RichText*) g_object_new (object_type, NULL);
	_tmp0_ = _text;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->text);
	self->priv->text = _tmp1_;
	{
		GRegex* _tmp2_ = NULL;
		_tmp2_ = rich_text_parse_url;
		if (_tmp2_ == NULL) {
			GRegex* _tmp3_ = NULL;
			GRegex* _tmp4_ = NULL;
			GRegex* _tmp5_ = NULL;
			_tmp4_ = g_regex_new (RICH_TEXT_url_string, G_REGEX_OPTIMIZE, 0, &_inner_error_);
			_tmp3_ = _tmp4_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				if (_inner_error_->domain == G_REGEX_ERROR) {
					goto __catch14_g_regex_error;
				}
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
				g_clear_error (&_inner_error_);
				return NULL;
			}
			_tmp5_ = _tmp3_;
			_tmp3_ = NULL;
			_g_regex_unref0 (rich_text_parse_url);
			rich_text_parse_url = _tmp5_;
			_g_regex_unref0 (_tmp3_);
		}
	}
	goto __finally14;
	__catch14_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_g_error_free0 (e);
	}
	__finally14:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	return self;
}


RichText* rich_text_new (const gchar* _text) {
	return rich_text_construct (TYPE_RICH_TEXT, _text);
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


void rich_text_parse_links (RichText* self) {
	GeeLinkedList* _tmp0_ = NULL;
	GeeLinkedList* _tmp1_ = NULL;
	GMatchInfo* match_info = NULL;
	gchar* lookup = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gint last_offset = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = gee_linked_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->link_locations_start);
	self->link_locations_start = _tmp0_;
	_tmp1_ = gee_linked_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->link_locations_end);
	self->link_locations_end = _tmp1_;
	_tmp2_ = self->priv->text;
	_tmp3_ = g_strdup (_tmp2_);
	lookup = _tmp3_;
	last_offset = 0;
	while (TRUE) {
		GRegex* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		GMatchInfo* _tmp6_ = NULL;
		gboolean _tmp7_ = FALSE;
		gint start = 0;
		gint end = 0;
		GMatchInfo* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		GeeLinkedList* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		gint _tmp15_ = 0;
		gint _tmp16_ = 0;
		GeeLinkedList* _tmp17_ = NULL;
		const gchar* _tmp18_ = NULL;
		gint _tmp19_ = 0;
		gint _tmp20_ = 0;
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		gint _tmp23_ = 0;
		gint _tmp24_ = 0;
		const gchar* _tmp25_ = NULL;
		gint _tmp26_ = 0;
		gchar* _tmp27_ = NULL;
		_tmp4_ = rich_text_parse_url;
		_tmp5_ = lookup;
		_tmp7_ = g_regex_match_all (_tmp4_, _tmp5_, 0, &_tmp6_);
		_g_match_info_unref0 (match_info);
		match_info = _tmp6_;
		if (!_tmp7_) {
			break;
		}
		_tmp8_ = match_info;
		g_match_info_fetch_pos (_tmp8_, 0, &_tmp9_, &_tmp10_);
		start = _tmp9_;
		end = _tmp10_;
		_tmp11_ = self->link_locations_start;
		_tmp12_ = self->priv->text;
		_tmp13_ = strlen (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = start;
		_tmp16_ = last_offset;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp11_, (gpointer) ((gintptr) (_tmp14_ - (_tmp15_ + _tmp16_))));
		_tmp17_ = self->link_locations_end;
		_tmp18_ = self->priv->text;
		_tmp19_ = strlen (_tmp18_);
		_tmp20_ = _tmp19_;
		_tmp21_ = end;
		_tmp22_ = last_offset;
		gee_abstract_collection_add ((GeeAbstractCollection*) _tmp17_, (gpointer) ((gintptr) (_tmp20_ - (_tmp21_ + _tmp22_))));
		_tmp23_ = last_offset;
		_tmp24_ = end;
		last_offset = _tmp23_ + _tmp24_;
		_tmp25_ = lookup;
		_tmp26_ = end;
		_tmp27_ = string_substring (_tmp25_, (glong) _tmp26_, (glong) -1);
		_g_free0 (lookup);
		lookup = _tmp27_;
		self->has_links = TRUE;
	}
	_g_free0 (lookup);
	_g_match_info_unref0 (match_info);
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static gint string_index_of_char (const gchar* self, gunichar c, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	gunichar _tmp1_ = 0U;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = c;
	_tmp2_ = g_utf8_strchr (((gchar*) self) + _tmp0_, (gssize) -1, _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static gunichar string_get_char (const gchar* self, glong index) {
	gunichar result = 0U;
	glong _tmp0_ = 0L;
	gunichar _tmp1_ = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = index;
	_tmp1_ = g_utf8_get_char (((gchar*) self) + _tmp0_);
	result = _tmp1_;
	return result;
}


void rich_text_parse_name (RichText* self, const gchar* name) {
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_ = NULL;
	gint location = 0;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	g_return_if_fail (self != NULL);
	return;
}


static void rich_text_class_init (RichTextClass * klass) {
	rich_text_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RichTextPrivate));
	G_OBJECT_CLASS (klass)->finalize = rich_text_finalize;
}


static void rich_text_instance_init (RichText * self) {
	GeeLinkedList* _tmp0_ = NULL;
	GeeLinkedList* _tmp1_ = NULL;
	GeeLinkedList* _tmp2_ = NULL;
	self->priv = RICH_TEXT_GET_PRIVATE (self);
	_tmp0_ = gee_linked_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	self->name_location_start = _tmp0_;
	_tmp1_ = gee_linked_list_new (G_TYPE_INT, NULL, NULL, NULL, NULL, NULL);
	self->name_location_end = _tmp1_;
	_tmp2_ = gee_linked_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	self->names = _tmp2_;
	self->has_links = FALSE;
	self->has_names = FALSE;
}


static void rich_text_finalize (GObject* obj) {
	RichText * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_RICH_TEXT, RichText);
	_g_free0 (self->priv->text);
	_g_object_unref0 (self->link_locations_start);
	_g_object_unref0 (self->link_locations_end);
	_g_object_unref0 (self->name_location_start);
	_g_object_unref0 (self->name_location_end);
	_g_object_unref0 (self->names);
	G_OBJECT_CLASS (rich_text_parent_class)->finalize (obj);
}


GType rich_text_get_type (void) {
	static volatile gsize rich_text_type_id__volatile = 0;
	if (g_once_init_enter (&rich_text_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RichTextClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rich_text_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RichText), 0, (GInstanceInitFunc) rich_text_instance_init, NULL };
		GType rich_text_type_id;
		rich_text_type_id = g_type_register_static (G_TYPE_OBJECT, "RichText", &g_define_type_info, 0);
		g_once_init_leave (&rich_text_type_id__volatile, rich_text_type_id);
	}
	return rich_text_type_id__volatile;
}



