/* server_manager.c generated by valac 0.34.4, the Vala compiler
 * generated from server_manager.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * server_manager.vala
 * Copyright (C) 2015 Kyle Agronick <stack@kyle-ele>
 *
 * KyRC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KyRC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>


#define TYPE_SERVER_MANAGER (server_manager_get_type ())
#define SERVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERVER_MANAGER, ServerManager))
#define SERVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERVER_MANAGER, ServerManagerClass))
#define IS_SERVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERVER_MANAGER))
#define IS_SERVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERVER_MANAGER))
#define SERVER_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERVER_MANAGER, ServerManagerClass))

typedef struct _ServerManager ServerManager;
typedef struct _ServerManagerClass ServerManagerClass;
typedef struct _ServerManagerPrivate ServerManagerPrivate;

#define TYPE_SQL_CLIENT (sql_client_get_type ())
#define SQL_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SQL_CLIENT, SqlClient))
#define SQL_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SQL_CLIENT, SqlClientClass))
#define IS_SQL_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SQL_CLIENT))
#define IS_SQL_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SQL_CLIENT))
#define SQL_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SQL_CLIENT, SqlClientClass))

typedef struct _SqlClient SqlClient;
typedef struct _SqlClientClass SqlClientClass;

#define SQL_CLIENT_TYPE_SERVER (sql_client_server_get_type ())
#define SQL_CLIENT_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SQL_CLIENT_TYPE_SERVER, SqlClientServer))
#define SQL_CLIENT_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SQL_CLIENT_TYPE_SERVER, SqlClientServerClass))
#define SQL_CLIENT_IS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SQL_CLIENT_TYPE_SERVER))
#define SQL_CLIENT_IS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SQL_CLIENT_TYPE_SERVER))
#define SQL_CLIENT_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SQL_CLIENT_TYPE_SERVER, SqlClientServerClass))

typedef struct _SqlClientServer SqlClientServer;
typedef struct _SqlClientServerClass SqlClientServerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _sql_client_server_unref0(var) ((var == NULL) ? NULL : (var = (sql_client_server_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _SqlClientServerPrivate SqlClientServerPrivate;

#define SQL_CLIENT_TYPE_CHANNEL (sql_client_channel_get_type ())
#define SQL_CLIENT_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannel))
#define SQL_CLIENT_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannelClass))
#define SQL_CLIENT_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SQL_CLIENT_TYPE_CHANNEL))
#define SQL_CLIENT_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SQL_CLIENT_TYPE_CHANNEL))
#define SQL_CLIENT_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannelClass))

typedef struct _SqlClientChannel SqlClientChannel;
typedef struct _SqlClientChannelClass SqlClientChannelClass;
typedef struct _Block11Data Block11Data;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _sql_client_channel_unref0(var) ((var == NULL) ? NULL : (var = (sql_client_channel_unref (var), NULL)))
typedef struct _SqlClientChannelPrivate SqlClientChannelPrivate;
typedef struct _Block12Data Block12Data;

struct _ServerManager {
	GObject parent_instance;
	ServerManagerPrivate * priv;
	GtkWindow* window;
	gchar* CHANNEL_CHAR;
	gint CHANNEL_CHAR_length1;
};

struct _ServerManagerClass {
	GObjectClass parent_class;
};

struct _ServerManagerPrivate {
	GtkEntry* new_channel;
	GtkListBox* channels;
	GtkListBox* servers;
	GtkListBoxRow* select_row;
	SqlClient* sqlclient;
	GtkButton* add_channel;
	GtkButton* cancel;
	GtkEntry* host;
	GtkSpinButton* port;
	GtkEntry* real;
	GtkEntry* user;
	GtkEntry* pass;
	GtkEntry* nick;
	GtkSwitch* encrypt;
	GtkTextView* connect_cmds;
	GtkGrid* form;
	SqlClientServer* current_server;
	gboolean none_selected;
};

struct _SqlClientServer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SqlClientServerPrivate * priv;
	gint id;
	gchar* host;
	gint port;
	gchar* nickname;
	gchar* realname;
	gchar* username;
	gchar* password;
	gchar* on_connect;
	gboolean encryption;
	gboolean autoconnect;
	gboolean validate_server;
	gchar* connect_cmds;
	GeeLinkedList* channels;
};

struct _SqlClientServerClass {
	GTypeClass parent_class;
	void (*finalize) (SqlClientServer *self);
};

struct _Block11Data {
	int _ref_count_;
	ServerManager* self;
	GtkMessageDialog* msg;
};

struct _SqlClientChannel {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SqlClientChannelPrivate * priv;
	gint id;
	gint server_id;
	gchar* channel;
	gboolean autoconnect;
};

struct _SqlClientChannelClass {
	GTypeClass parent_class;
	void (*finalize) (SqlClientChannel *self);
};

struct _Block12Data {
	int _ref_count_;
	ServerManager* self;
	GtkMessageDialog* msg;
};


static gpointer server_manager_parent_class = NULL;
static gchar* server_manager_CHANNEL_ERROR;
static gchar* server_manager_CHANNEL_ERROR = NULL;
extern GeeHashMap* sql_client_servers;

GType server_manager_get_type (void) G_GNUC_CONST;
GType sql_client_get_type (void) G_GNUC_CONST;
gpointer sql_client_server_ref (gpointer instance);
void sql_client_server_unref (gpointer instance);
GParamSpec* sql_client_param_spec_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sql_client_value_set_server (GValue* value, gpointer v_object);
void sql_client_value_take_server (GValue* value, gpointer v_object);
gpointer sql_client_value_get_server (const GValue* value);
GType sql_client_server_get_type (void) G_GNUC_CONST;
#define SERVER_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SERVER_MANAGER, ServerManagerPrivate))
enum  {
	SERVER_MANAGER_DUMMY_PROPERTY
};
SqlClient* sql_client_get_instance (void);
gboolean server_manager_open_window (ServerManager* self);
gchar* relay_get_asset_file (const gchar* name);
#define MAIN_WINDOW_UI_FILE_SERVERS "ui/server_window.ui"
void server_manager_save_changes (ServerManager* self, GtkListBoxRow* row);
static void _server_manager_save_changes_gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self);
void server_manager_populate_fields (ServerManager* self, GtkListBoxRow* row);
static void _server_manager_populate_fields_gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self);
static void server_manager_clear_row (ServerManager* self, GtkListBoxRow* row);
static void _server_manager_clear_row_gtk_list_box_row_selected (GtkListBox* _sender, GtkListBoxRow* row, gpointer self);
static gboolean server_manager_cancel_clicked (ServerManager* self, GdkEventButton* event);
static gboolean _server_manager_cancel_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean server_manager_add_channel_clicked (ServerManager* self, GdkEventButton* event);
static gboolean _server_manager_add_channel_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean server_manager_add_server_clicked (ServerManager* self, GdkEventButton* event);
static gboolean _server_manager_add_server_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean server_manager_remove_server_clicked (ServerManager* self, GdkEventButton* event);
static gboolean _server_manager_remove_server_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean server_manager_remove_channel_clicked (ServerManager* self, GdkEventButton* event);
static gboolean _server_manager_remove_channel_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static gboolean server_manager_host_text_changed (ServerManager* self, GdkEventFocus* event);
static gboolean _server_manager_host_text_changed_gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self);
static void server_manager_add_servers (ServerManager* self);
static void server_manager_set_forms_active (ServerManager* self, gboolean active);
static void __lambda28_ (ServerManager* self);
static void ___lambda28__gtk_widget_destroy (GtkWidget* _sender, gpointer self);
SqlClientServer* sql_client_get_server (SqlClient* self, const gchar* name);
gpointer sql_client_channel_ref (gpointer instance);
void sql_client_channel_unref (gpointer instance);
GParamSpec* sql_client_param_spec_channel (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sql_client_value_set_channel (GValue* value, gpointer v_object);
void sql_client_value_take_channel (GValue* value, gpointer v_object);
gpointer sql_client_value_get_channel (const GValue* value);
GType sql_client_channel_get_type (void) G_GNUC_CONST;
gint sql_client_server_update (SqlClientServer* self);
static GtkListBoxRow* server_manager_get_list_box_row (ServerManager* self, const gchar* name);
static Block11Data* block11_data_ref (Block11Data* _data11_);
static void block11_data_unref (void * _userdata_);
static void ___lambda27_ (Block11Data* _data11_, gint response_id);
static void ____lambda27__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
SqlClientServer* sql_client_server_new (void);
SqlClientServer* sql_client_server_construct (GType object_type);
static GtkListBoxRow* server_manager_get_channel_list_box_row (ServerManager* self, SqlClientChannel* channel);
gboolean sql_client_channel_update_autoconnect (SqlClientChannel* self, gboolean state);
static gboolean _sql_client_channel_update_autoconnect_gtk_switch_state_set (GtkSwitch* _sender, gboolean state, gpointer self);
SqlClientChannel* sql_client_server_find_channel_by_name (SqlClientServer* self, const gchar* name);
void sql_client_channel_delete_channel (SqlClientChannel* self);
static gboolean _vala_char_array_contains (gchar* stack, int stack_length, gchar needle);
static Block12Data* block12_data_ref (Block12Data* _data12_);
static void block12_data_unref (void * _userdata_);
static void ___lambda26_ (Block12Data* _data12_, gint response_id);
static void ____lambda26__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
SqlClientChannel* sql_client_channel_new (void);
SqlClientChannel* sql_client_channel_construct (GType object_type);
void sql_client_channel_add_channel (SqlClientChannel* self);
void sql_client_server_remove_server (SqlClientServer* self);
gint sql_client_server_add_server_empty (SqlClientServer* self);
#define CONNECTION_DEFAULT_PORT ((guint16) 6667)
ServerManager* server_manager_new (void);
ServerManager* server_manager_construct (GType object_type);
static void server_manager_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void _server_manager_save_changes_gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self) {
	server_manager_save_changes ((ServerManager*) self, row);
}


static void _server_manager_populate_fields_gtk_list_box_row_activated (GtkListBox* _sender, GtkListBoxRow* row, gpointer self) {
	server_manager_populate_fields ((ServerManager*) self, row);
}


static void _server_manager_clear_row_gtk_list_box_row_selected (GtkListBox* _sender, GtkListBoxRow* row, gpointer self) {
	server_manager_clear_row ((ServerManager*) self, row);
}


static gboolean _server_manager_cancel_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = server_manager_cancel_clicked ((ServerManager*) self, event);
	return result;
}


static gboolean _server_manager_add_channel_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = server_manager_add_channel_clicked ((ServerManager*) self, event);
	return result;
}


static gboolean _server_manager_add_server_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = server_manager_add_server_clicked ((ServerManager*) self, event);
	return result;
}


static gboolean _server_manager_remove_server_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = server_manager_remove_server_clicked ((ServerManager*) self, event);
	return result;
}


static gboolean _server_manager_remove_channel_clicked_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = server_manager_remove_channel_clicked ((ServerManager*) self, event);
	return result;
}


static gboolean _server_manager_host_text_changed_gtk_widget_focus_out_event (GtkWidget* _sender, GdkEventFocus* event, gpointer self) {
	gboolean result;
	result = server_manager_host_text_changed ((ServerManager*) self, event);
	return result;
}


static void __lambda28_ (ServerManager* self) {
	g_signal_emit_by_name (self, "close");
}


static void ___lambda28__gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	__lambda28_ ((ServerManager*) self);
}


gboolean server_manager_open_window (ServerManager* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GtkWindow* _tmp1_ = NULL;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp6_ = NULL;
	GtkBuilder* _tmp14_ = NULL;
	GObject* _tmp15_ = NULL;
	GtkWindow* _tmp16_ = NULL;
	GtkBox* box = NULL;
	GtkBuilder* _tmp17_ = NULL;
	GObject* _tmp18_ = NULL;
	GtkBox* _tmp19_ = NULL;
	GtkButton* remove_channel = NULL;
	GtkBuilder* _tmp20_ = NULL;
	GObject* _tmp21_ = NULL;
	GtkButton* _tmp22_ = NULL;
	GtkBox* server_btns = NULL;
	GtkBuilder* _tmp23_ = NULL;
	GObject* _tmp24_ = NULL;
	GtkBox* _tmp25_ = NULL;
	GtkBuilder* _tmp26_ = NULL;
	GObject* _tmp27_ = NULL;
	GtkButton* _tmp28_ = NULL;
	GtkBuilder* _tmp29_ = NULL;
	GObject* _tmp30_ = NULL;
	GtkButton* _tmp31_ = NULL;
	GtkBuilder* _tmp32_ = NULL;
	GObject* _tmp33_ = NULL;
	GtkEntry* _tmp34_ = NULL;
	GtkScrolledWindow* channels_wrapper = NULL;
	GtkBuilder* _tmp35_ = NULL;
	GObject* _tmp36_ = NULL;
	GtkScrolledWindow* _tmp37_ = NULL;
	GtkListBox* _tmp38_ = NULL;
	GtkScrolledWindow* _tmp39_ = NULL;
	GtkListBox* _tmp40_ = NULL;
	GtkBuilder* _tmp41_ = NULL;
	GObject* _tmp42_ = NULL;
	GtkListBox* _tmp43_ = NULL;
	GtkBuilder* _tmp44_ = NULL;
	GObject* _tmp45_ = NULL;
	GtkEntry* _tmp46_ = NULL;
	GtkBuilder* _tmp47_ = NULL;
	GObject* _tmp48_ = NULL;
	GtkEntry* _tmp49_ = NULL;
	GtkBuilder* _tmp50_ = NULL;
	GObject* _tmp51_ = NULL;
	GtkEntry* _tmp52_ = NULL;
	GtkBuilder* _tmp53_ = NULL;
	GObject* _tmp54_ = NULL;
	GtkEntry* _tmp55_ = NULL;
	GtkBuilder* _tmp56_ = NULL;
	GObject* _tmp57_ = NULL;
	GtkEntry* _tmp58_ = NULL;
	GtkBuilder* _tmp59_ = NULL;
	GObject* _tmp60_ = NULL;
	GtkTextView* _tmp61_ = NULL;
	GtkBuilder* _tmp62_ = NULL;
	GObject* _tmp63_ = NULL;
	GtkSwitch* _tmp64_ = NULL;
	GtkBuilder* _tmp65_ = NULL;
	GObject* _tmp66_ = NULL;
	GtkGrid* _tmp67_ = NULL;
	GtkLabel* channels_placeholder = NULL;
	const gchar* _tmp68_ = NULL;
	GtkLabel* _tmp69_ = NULL;
	GtkListBox* _tmp70_ = NULL;
	GtkLabel* _tmp71_ = NULL;
	GtkLabel* _tmp72_ = NULL;
	GtkListBox* _tmp73_ = NULL;
	GtkListBox* _tmp74_ = NULL;
	GtkListBox* _tmp75_ = NULL;
	GtkListBox* _tmp76_ = NULL;
	GtkButton* add_server = NULL;
	GtkButton* _tmp77_ = NULL;
	GtkButton* _tmp78_ = NULL;
	gchar* _tmp79_ = NULL;
	gchar* _tmp80_ = NULL;
	GtkImage* _tmp81_ = NULL;
	GtkImage* _tmp82_ = NULL;
	GtkButton* remove_server = NULL;
	GtkButton* _tmp83_ = NULL;
	GtkButton* _tmp84_ = NULL;
	gchar* _tmp85_ = NULL;
	gchar* _tmp86_ = NULL;
	GtkImage* _tmp87_ = NULL;
	GtkImage* _tmp88_ = NULL;
	GtkBox* _tmp89_ = NULL;
	GtkButton* _tmp90_ = NULL;
	GtkBox* _tmp91_ = NULL;
	GtkButton* _tmp92_ = NULL;
	GtkListBox* _tmp93_ = NULL;
	GtkListBox* _tmp94_ = NULL;
	GtkButton* _tmp95_ = NULL;
	GtkButton* _tmp96_ = NULL;
	GtkButton* _tmp97_ = NULL;
	GtkButton* _tmp98_ = NULL;
	GtkButton* _tmp99_ = NULL;
	GtkEntry* _tmp100_ = NULL;
	GtkAdjustment* chn_adj = NULL;
	GtkAdjustment* _tmp101_ = NULL;
	GtkListBox* _tmp102_ = NULL;
	GtkAdjustment* _tmp103_ = NULL;
	GtkSpinButton* _tmp104_ = NULL;
	GtkBox* _tmp105_ = NULL;
	GtkSpinButton* _tmp106_ = NULL;
	GtkWindow* _tmp107_ = NULL;
	GtkWindow* _tmp108_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp1_ = self->window;
	if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_widget_get_type ())) {
		GtkWindow* _tmp2_ = NULL;
		gboolean _tmp3_ = FALSE;
		gboolean _tmp4_ = FALSE;
		_tmp2_ = self->window;
		_tmp3_ = gtk_widget_get_visible ((GtkWidget*) _tmp2_);
		_tmp4_ = _tmp3_;
		_tmp0_ = _tmp4_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GtkWindow* _tmp5_ = NULL;
		_tmp5_ = self->window;
		gtk_window_present (_tmp5_);
		result = TRUE;
		return result;
	}
	_sql_client_server_unref0 (self->priv->current_server);
	self->priv->current_server = NULL;
	_tmp6_ = gtk_builder_new ();
	builder = _tmp6_;
	{
		GtkBuilder* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		_tmp7_ = builder;
		_tmp8_ = relay_get_asset_file (MAIN_WINDOW_UI_FILE_SERVERS);
		_tmp9_ = _tmp8_;
		gtk_builder_add_from_file (_tmp7_, _tmp9_, &_inner_error_);
		_g_free0 (_tmp9_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch3_g_error;
		}
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* e = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp10_ = relay_get_asset_file (MAIN_WINDOW_UI_FILE_SERVERS);
		_tmp11_ = _tmp10_;
		_tmp12_ = g_strconcat ("Unable to load UI file ", _tmp11_, NULL);
		_tmp13_ = _tmp12_;
		g_error ("server_manager.vala:61: %s", _tmp13_);
		_g_free0 (_tmp13_);
		_g_free0 (_tmp11_);
		_g_error_free0 (e);
	}
	__finally3:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (builder);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return FALSE;
	}
	_tmp14_ = builder;
	_tmp15_ = gtk_builder_get_object (_tmp14_, "window");
	_tmp16_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp15_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp15_) : NULL);
	_g_object_unref0 (self->window);
	self->window = _tmp16_;
	_tmp17_ = builder;
	_tmp18_ = gtk_builder_get_object (_tmp17_, "port_wrap");
	_tmp19_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp18_, gtk_box_get_type ()) ? ((GtkBox*) _tmp18_) : NULL);
	box = _tmp19_;
	_tmp20_ = builder;
	_tmp21_ = gtk_builder_get_object (_tmp20_, "remove_channel");
	_tmp22_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp21_, gtk_button_get_type ()) ? ((GtkButton*) _tmp21_) : NULL);
	remove_channel = _tmp22_;
	_tmp23_ = builder;
	_tmp24_ = gtk_builder_get_object (_tmp23_, "server_buttons");
	_tmp25_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp24_, gtk_box_get_type ()) ? ((GtkBox*) _tmp24_) : NULL);
	server_btns = _tmp25_;
	_tmp26_ = builder;
	_tmp27_ = gtk_builder_get_object (_tmp26_, "cancel");
	_tmp28_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp27_, gtk_button_get_type ()) ? ((GtkButton*) _tmp27_) : NULL);
	_g_object_unref0 (self->priv->cancel);
	self->priv->cancel = _tmp28_;
	_tmp29_ = builder;
	_tmp30_ = gtk_builder_get_object (_tmp29_, "add_channel");
	_tmp31_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp30_, gtk_button_get_type ()) ? ((GtkButton*) _tmp30_) : NULL);
	_g_object_unref0 (self->priv->add_channel);
	self->priv->add_channel = _tmp31_;
	_tmp32_ = builder;
	_tmp33_ = gtk_builder_get_object (_tmp32_, "channel_name");
	_tmp34_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp33_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp33_) : NULL);
	_g_object_unref0 (self->priv->new_channel);
	self->priv->new_channel = _tmp34_;
	_tmp35_ = builder;
	_tmp36_ = gtk_builder_get_object (_tmp35_, "channel_wrapper");
	_tmp37_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp36_, gtk_scrolled_window_get_type ()) ? ((GtkScrolledWindow*) _tmp36_) : NULL);
	channels_wrapper = _tmp37_;
	_tmp38_ = (GtkListBox*) gtk_list_box_new ();
	g_object_ref_sink (_tmp38_);
	_g_object_unref0 (self->priv->channels);
	self->priv->channels = _tmp38_;
	_tmp39_ = channels_wrapper;
	_tmp40_ = self->priv->channels;
	gtk_container_add ((GtkContainer*) _tmp39_, (GtkWidget*) _tmp40_);
	_tmp41_ = builder;
	_tmp42_ = gtk_builder_get_object (_tmp41_, "servers");
	_tmp43_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp42_, gtk_list_box_get_type ()) ? ((GtkListBox*) _tmp42_) : NULL);
	_g_object_unref0 (self->priv->servers);
	self->priv->servers = _tmp43_;
	_tmp44_ = builder;
	_tmp45_ = gtk_builder_get_object (_tmp44_, "host");
	_tmp46_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp45_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp45_) : NULL);
	_g_object_unref0 (self->priv->host);
	self->priv->host = _tmp46_;
	_tmp47_ = builder;
	_tmp48_ = gtk_builder_get_object (_tmp47_, "real");
	_tmp49_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp48_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp48_) : NULL);
	_g_object_unref0 (self->priv->real);
	self->priv->real = _tmp49_;
	_tmp50_ = builder;
	_tmp51_ = gtk_builder_get_object (_tmp50_, "user");
	_tmp52_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp51_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp51_) : NULL);
	_g_object_unref0 (self->priv->user);
	self->priv->user = _tmp52_;
	_tmp53_ = builder;
	_tmp54_ = gtk_builder_get_object (_tmp53_, "pass");
	_tmp55_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp54_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp54_) : NULL);
	_g_object_unref0 (self->priv->pass);
	self->priv->pass = _tmp55_;
	_tmp56_ = builder;
	_tmp57_ = gtk_builder_get_object (_tmp56_, "nick");
	_tmp58_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp57_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp57_) : NULL);
	_g_object_unref0 (self->priv->nick);
	self->priv->nick = _tmp58_;
	_tmp59_ = builder;
	_tmp60_ = gtk_builder_get_object (_tmp59_, "connect_cmds");
	_tmp61_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp60_, gtk_text_view_get_type ()) ? ((GtkTextView*) _tmp60_) : NULL);
	_g_object_unref0 (self->priv->connect_cmds);
	self->priv->connect_cmds = _tmp61_;
	_tmp62_ = builder;
	_tmp63_ = gtk_builder_get_object (_tmp62_, "encrypt");
	_tmp64_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp63_, gtk_switch_get_type ()) ? ((GtkSwitch*) _tmp63_) : NULL);
	_g_object_unref0 (self->priv->encrypt);
	self->priv->encrypt = _tmp64_;
	_tmp65_ = builder;
	_tmp66_ = gtk_builder_get_object (_tmp65_, "form");
	_tmp67_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp66_, gtk_grid_get_type ()) ? ((GtkGrid*) _tmp66_) : NULL);
	_g_object_unref0 (self->priv->form);
	self->priv->form = _tmp67_;
	_tmp68_ = _ ("No Channels");
	_tmp69_ = (GtkLabel*) gtk_label_new (_tmp68_);
	g_object_ref_sink (_tmp69_);
	channels_placeholder = _tmp69_;
	_tmp70_ = self->priv->channels;
	_tmp71_ = channels_placeholder;
	gtk_list_box_set_placeholder (_tmp70_, (GtkWidget*) _tmp71_);
	_tmp72_ = channels_placeholder;
	gtk_widget_show_all ((GtkWidget*) _tmp72_);
	_tmp73_ = self->priv->servers;
	gtk_list_box_set_selection_mode (_tmp73_, GTK_SELECTION_BROWSE);
	_tmp74_ = self->priv->servers;
	g_signal_connect_object (_tmp74_, "row-activated", (GCallback) _server_manager_save_changes_gtk_list_box_row_activated, self, 0);
	_tmp75_ = self->priv->servers;
	g_signal_connect_object (_tmp75_, "row-activated", (GCallback) _server_manager_populate_fields_gtk_list_box_row_activated, self, 0);
	_tmp76_ = self->priv->servers;
	g_signal_connect_object (_tmp76_, "row-selected", (GCallback) _server_manager_clear_row_gtk_list_box_row_selected, self, 0);
	_tmp77_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp77_);
	add_server = _tmp77_;
	_tmp78_ = add_server;
	_tmp79_ = relay_get_asset_file ("assets/list-add-symbolic.svg");
	_tmp80_ = _tmp79_;
	_tmp81_ = (GtkImage*) gtk_image_new_from_file (_tmp80_);
	g_object_ref_sink (_tmp81_);
	_tmp82_ = _tmp81_;
	gtk_button_set_image (_tmp78_, (GtkWidget*) _tmp82_);
	_g_object_unref0 (_tmp82_);
	_g_free0 (_tmp80_);
	_tmp83_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp83_);
	remove_server = _tmp83_;
	_tmp84_ = remove_server;
	_tmp85_ = relay_get_asset_file ("assets/list-remove-symbolic.svg");
	_tmp86_ = _tmp85_;
	_tmp87_ = (GtkImage*) gtk_image_new_from_file (_tmp86_);
	g_object_ref_sink (_tmp87_);
	_tmp88_ = _tmp87_;
	gtk_button_set_image (_tmp84_, (GtkWidget*) _tmp88_);
	_g_object_unref0 (_tmp88_);
	_g_free0 (_tmp86_);
	_tmp89_ = server_btns;
	_tmp90_ = add_server;
	gtk_box_pack_end (_tmp89_, (GtkWidget*) _tmp90_, FALSE, FALSE, (guint) 0);
	_tmp91_ = server_btns;
	_tmp92_ = remove_server;
	gtk_box_pack_end (_tmp91_, (GtkWidget*) _tmp92_, FALSE, FALSE, (guint) 0);
	_tmp93_ = self->priv->channels;
	gtk_list_box_set_selection_mode (_tmp93_, GTK_SELECTION_BROWSE);
	_tmp94_ = self->priv->servers;
	gtk_widget_set_size_request ((GtkWidget*) _tmp94_, 175, 50);
	_tmp95_ = self->priv->cancel;
	g_signal_connect_object ((GtkWidget*) _tmp95_, "button-release-event", (GCallback) _server_manager_cancel_clicked_gtk_widget_button_release_event, self, 0);
	_tmp96_ = self->priv->add_channel;
	g_signal_connect_object ((GtkWidget*) _tmp96_, "button-release-event", (GCallback) _server_manager_add_channel_clicked_gtk_widget_button_release_event, self, 0);
	_tmp97_ = add_server;
	g_signal_connect_object ((GtkWidget*) _tmp97_, "button-release-event", (GCallback) _server_manager_add_server_clicked_gtk_widget_button_release_event, self, 0);
	_tmp98_ = remove_server;
	g_signal_connect_object ((GtkWidget*) _tmp98_, "button-release-event", (GCallback) _server_manager_remove_server_clicked_gtk_widget_button_release_event, self, 0);
	_tmp99_ = remove_channel;
	g_signal_connect_object ((GtkWidget*) _tmp99_, "button-release-event", (GCallback) _server_manager_remove_channel_clicked_gtk_widget_button_release_event, self, 0);
	_tmp100_ = self->priv->host;
	g_signal_connect_object ((GtkWidget*) _tmp100_, "focus-out-event", (GCallback) _server_manager_host_text_changed_gtk_widget_focus_out_event, self, 0);
	_tmp101_ = gtk_adjustment_new ((gdouble) 1, (gdouble) 1, (gdouble) 500, (gdouble) 1, (gdouble) 2, (gdouble) 100);
	g_object_ref_sink (_tmp101_);
	chn_adj = _tmp101_;
	_tmp102_ = self->priv->channels;
	_tmp103_ = chn_adj;
	gtk_list_box_set_adjustment (_tmp102_, _tmp103_);
	_tmp104_ = (GtkSpinButton*) gtk_spin_button_new_with_range ((gdouble) 0, (gdouble) 65535, (gdouble) 1);
	g_object_ref_sink (_tmp104_);
	_g_object_unref0 (self->priv->port);
	self->priv->port = _tmp104_;
	_tmp105_ = box;
	_tmp106_ = self->priv->port;
	gtk_box_pack_start (_tmp105_, (GtkWidget*) _tmp106_, FALSE, FALSE, (guint) 0);
	server_manager_add_servers (self);
	_tmp107_ = self->window;
	gtk_widget_show_all ((GtkWidget*) _tmp107_);
	server_manager_set_forms_active (self, FALSE);
	_tmp108_ = self->window;
	g_signal_connect_object ((GtkWidget*) _tmp108_, "destroy", (GCallback) ___lambda28__gtk_widget_destroy, self, 0);
	result = FALSE;
	_g_object_unref0 (chn_adj);
	_g_object_unref0 (remove_server);
	_g_object_unref0 (add_server);
	_g_object_unref0 (channels_placeholder);
	_g_object_unref0 (channels_wrapper);
	_g_object_unref0 (server_btns);
	_g_object_unref0 (remove_channel);
	_g_object_unref0 (box);
	_g_object_unref0 (builder);
	return result;
}


static void server_manager_clear_row (ServerManager* self, GtkListBoxRow* row) {
	GtkListBoxRow* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = row;
	if (!G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, gtk_widget_get_type ())) {
		self->priv->none_selected = TRUE;
	} else {
		gboolean _tmp1_ = FALSE;
		_tmp1_ = self->priv->none_selected;
		if (_tmp1_) {
			_sql_client_server_unref0 (self->priv->current_server);
			self->priv->current_server = NULL;
			_g_object_unref0 (self->priv->select_row);
			self->priv->select_row = NULL;
			self->priv->none_selected = FALSE;
		}
	}
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


void server_manager_save_changes (ServerManager* self, GtkListBoxRow* row) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	SqlClientServer* _tmp2_ = NULL;
	gchar* hostname = NULL;
	GtkEntry* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	SqlClientServer* exists = NULL;
	SqlClient* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	SqlClientServer* _tmp11_ = NULL;
	gboolean _tmp12_ = FALSE;
	SqlClientServer* _tmp13_ = NULL;
	SqlClientServer* _tmp18_ = NULL;
	const gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	SqlClientServer* _tmp21_ = NULL;
	GtkEntry* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	SqlClientServer* _tmp25_ = NULL;
	GtkEntry* _tmp26_ = NULL;
	const gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	SqlClientServer* _tmp29_ = NULL;
	GtkEntry* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	SqlClientServer* _tmp33_ = NULL;
	GtkEntry* _tmp34_ = NULL;
	const gchar* _tmp35_ = NULL;
	gchar* _tmp36_ = NULL;
	SqlClientServer* _tmp37_ = NULL;
	GtkSpinButton* _tmp38_ = NULL;
	gint _tmp39_ = 0;
	SqlClientServer* _tmp40_ = NULL;
	GtkSwitch* _tmp41_ = NULL;
	gboolean _tmp42_ = FALSE;
	SqlClientServer* _tmp43_ = NULL;
	GtkTextView* _tmp44_ = NULL;
	GtkTextBuffer* _tmp45_ = NULL;
	GtkTextBuffer* _tmp46_ = NULL;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	SqlClientServer* _tmp49_ = NULL;
	GtkListBoxRow* _tmp50_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp2_ = self->priv->current_server;
	if (_tmp2_ == NULL) {
		_tmp1_ = TRUE;
	} else {
		GtkListBoxRow* _tmp3_ = NULL;
		_tmp3_ = self->priv->select_row;
		_tmp1_ = _tmp3_ == NULL;
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		GtkListBoxRow* _tmp4_ = NULL;
		_tmp4_ = row;
		_tmp0_ = _tmp4_ == NULL;
	}
	if (_tmp0_) {
		return;
	}
	_tmp5_ = self->priv->host;
	_tmp6_ = gtk_entry_get_text (_tmp5_);
	_tmp7_ = string_strip (_tmp6_);
	hostname = _tmp7_;
	_tmp8_ = hostname;
	if (g_strcmp0 (_tmp8_, "") == 0) {
		_g_free0 (hostname);
		return;
	}
	_tmp9_ = self->priv->sqlclient;
	_tmp10_ = hostname;
	_tmp11_ = sql_client_get_server (_tmp9_, _tmp10_);
	exists = _tmp11_;
	_tmp13_ = exists;
	if (_tmp13_ != NULL) {
		SqlClientServer* _tmp14_ = NULL;
		gint _tmp15_ = 0;
		SqlClientServer* _tmp16_ = NULL;
		gint _tmp17_ = 0;
		_tmp14_ = exists;
		_tmp15_ = _tmp14_->id;
		_tmp16_ = self->priv->current_server;
		_tmp17_ = _tmp16_->id;
		_tmp12_ = _tmp15_ != _tmp17_;
	} else {
		_tmp12_ = FALSE;
	}
	if (_tmp12_) {
		_sql_client_server_unref0 (exists);
		_g_free0 (hostname);
		return;
	}
	_tmp18_ = self->priv->current_server;
	_tmp19_ = hostname;
	_tmp20_ = g_strdup (_tmp19_);
	_g_free0 (_tmp18_->host);
	_tmp18_->host = _tmp20_;
	_tmp21_ = self->priv->current_server;
	_tmp22_ = self->priv->real;
	_tmp23_ = gtk_entry_get_text (_tmp22_);
	_tmp24_ = g_strdup (_tmp23_);
	_g_free0 (_tmp21_->realname);
	_tmp21_->realname = _tmp24_;
	_tmp25_ = self->priv->current_server;
	_tmp26_ = self->priv->user;
	_tmp27_ = gtk_entry_get_text (_tmp26_);
	_tmp28_ = g_strdup (_tmp27_);
	_g_free0 (_tmp25_->username);
	_tmp25_->username = _tmp28_;
	_tmp29_ = self->priv->current_server;
	_tmp30_ = self->priv->pass;
	_tmp31_ = gtk_entry_get_text (_tmp30_);
	_tmp32_ = g_strdup (_tmp31_);
	_g_free0 (_tmp29_->password);
	_tmp29_->password = _tmp32_;
	_tmp33_ = self->priv->current_server;
	_tmp34_ = self->priv->nick;
	_tmp35_ = gtk_entry_get_text (_tmp34_);
	_tmp36_ = g_strdup (_tmp35_);
	_g_free0 (_tmp33_->nickname);
	_tmp33_->nickname = _tmp36_;
	_tmp37_ = self->priv->current_server;
	_tmp38_ = self->priv->port;
	_tmp39_ = gtk_spin_button_get_value_as_int (_tmp38_);
	_tmp37_->port = _tmp39_;
	_tmp40_ = self->priv->current_server;
	_tmp41_ = self->priv->encrypt;
	_tmp42_ = gtk_switch_get_active (_tmp41_);
	_tmp40_->encryption = _tmp42_;
	_tmp43_ = self->priv->current_server;
	_tmp44_ = self->priv->connect_cmds;
	_tmp45_ = gtk_text_view_get_buffer (_tmp44_);
	_tmp46_ = _tmp45_;
	g_object_get (_tmp46_, "text", &_tmp47_, NULL);
	_tmp48_ = _tmp47_;
	_g_free0 (_tmp43_->connect_cmds);
	_tmp43_->connect_cmds = _tmp48_;
	_tmp49_ = self->priv->current_server;
	sql_client_server_update (_tmp49_);
	_tmp50_ = self->priv->select_row;
	if (_tmp50_ != NULL) {
		gint index = 0;
		GtkListBoxRow* _tmp51_ = NULL;
		gint _tmp52_ = 0;
		GtkListBoxRow* newrow = NULL;
		const gchar* _tmp53_ = NULL;
		GtkListBoxRow* _tmp54_ = NULL;
		GtkListBox* _tmp55_ = NULL;
		GtkListBoxRow* _tmp56_ = NULL;
		GtkListBox* _tmp57_ = NULL;
		GtkListBoxRow* _tmp58_ = NULL;
		gint _tmp59_ = 0;
		GtkListBox* _tmp60_ = NULL;
		_tmp51_ = self->priv->select_row;
		_tmp52_ = gtk_list_box_row_get_index (_tmp51_);
		index = _tmp52_;
		_tmp53_ = hostname;
		_tmp54_ = server_manager_get_list_box_row (self, _tmp53_);
		newrow = _tmp54_;
		_tmp55_ = self->priv->servers;
		_tmp56_ = self->priv->select_row;
		gtk_container_remove ((GtkContainer*) _tmp55_, (GtkWidget*) _tmp56_);
		_tmp57_ = self->priv->servers;
		_tmp58_ = newrow;
		_tmp59_ = index;
		gtk_list_box_insert (_tmp57_, (GtkWidget*) _tmp58_, _tmp59_);
		_tmp60_ = self->priv->servers;
		gtk_widget_show_all ((GtkWidget*) _tmp60_);
		_g_object_unref0 (newrow);
	}
	_sql_client_server_unref0 (exists);
	_g_free0 (hostname);
}


static Block11Data* block11_data_ref (Block11Data* _data11_) {
	g_atomic_int_inc (&_data11_->_ref_count_);
	return _data11_;
}


static void block11_data_unref (void * _userdata_) {
	Block11Data* _data11_;
	_data11_ = (Block11Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data11_->_ref_count_)) {
		ServerManager* self;
		self = _data11_->self;
		_g_object_unref0 (_data11_->msg);
		_g_object_unref0 (self);
		g_slice_free (Block11Data, _data11_);
	}
}


static void ___lambda27_ (Block11Data* _data11_, gint response_id) {
	ServerManager* self;
	GtkEntry* _tmp0_ = NULL;
	GtkMessageDialog* _tmp1_ = NULL;
	self = _data11_->self;
	_tmp0_ = self->priv->host;
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
	_tmp1_ = _data11_->msg;
	gtk_widget_destroy ((GtkWidget*) _tmp1_);
}


static void ____lambda27__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	___lambda27_ (self, response_id);
}


static gboolean server_manager_host_text_changed (ServerManager* self, GdkEventFocus* event) {
	gboolean result = FALSE;
	gchar* message = NULL;
	gchar* _tmp0_ = NULL;
	gchar* name = NULL;
	GtkEntry* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	SqlClientServer* exists = NULL;
	SqlClient* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	SqlClientServer* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	SqlClientServer* _tmp12_ = NULL;
	const gchar* _tmp18_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = g_strdup ("");
	message = _tmp0_;
	_tmp1_ = self->priv->host;
	_tmp2_ = gtk_entry_get_text (_tmp1_);
	_tmp3_ = string_strip (_tmp2_);
	name = _tmp3_;
	_tmp4_ = name;
	_tmp5_ = strlen (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ == 0) {
		gchar* _tmp7_ = NULL;
		_tmp7_ = g_strdup ("Host can not be empty. Your changes will not be saved.");
		_g_free0 (message);
		message = _tmp7_;
	}
	_tmp8_ = self->priv->sqlclient;
	_tmp9_ = name;
	_tmp10_ = sql_client_get_server (_tmp8_, _tmp9_);
	exists = _tmp10_;
	_tmp12_ = exists;
	if (_tmp12_ != NULL) {
		SqlClientServer* _tmp13_ = NULL;
		gint _tmp14_ = 0;
		SqlClientServer* _tmp15_ = NULL;
		gint _tmp16_ = 0;
		_tmp13_ = exists;
		_tmp14_ = _tmp13_->id;
		_tmp15_ = self->priv->current_server;
		_tmp16_ = _tmp15_->id;
		_tmp11_ = _tmp14_ != _tmp16_;
	} else {
		_tmp11_ = FALSE;
	}
	if (_tmp11_) {
		gchar* _tmp17_ = NULL;
		_tmp17_ = g_strdup ("A server with that host already exists. Your changes will not be saved" \
".");
		_g_free0 (message);
		message = _tmp17_;
	}
	_tmp18_ = message;
	if (g_strcmp0 (_tmp18_, "") != 0) {
		Block11Data* _data11_;
		GtkWindow* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		GtkMessageDialog* _tmp21_ = NULL;
		GtkMessageDialog* _tmp22_ = NULL;
		GtkMessageDialog* _tmp23_ = NULL;
		_data11_ = g_slice_new0 (Block11Data);
		_data11_->_ref_count_ = 1;
		_data11_->self = g_object_ref (self);
		_tmp19_ = self->window;
		_tmp20_ = message;
		_tmp21_ = (GtkMessageDialog*) gtk_message_dialog_new (_tmp19_, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK, "%s", _tmp20_);
		g_object_ref_sink (_tmp21_);
		_data11_->msg = _tmp21_;
		_tmp22_ = _data11_->msg;
		g_signal_connect_data ((GtkDialog*) _tmp22_, "response", (GCallback) ____lambda27__gtk_dialog_response, block11_data_ref (_data11_), (GClosureNotify) block11_data_unref, 0);
		_tmp23_ = _data11_->msg;
		gtk_widget_show ((GtkWidget*) _tmp23_);
		block11_data_unref (_data11_);
		_data11_ = NULL;
	}
	result = FALSE;
	_sql_client_server_unref0 (exists);
	_g_free0 (name);
	_g_free0 (message);
	return result;
}


static gpointer _sql_client_server_ref0 (gpointer self) {
	return self ? sql_client_server_ref (self) : NULL;
}


void server_manager_populate_fields (ServerManager* self, GtkListBoxRow* row) {
	GtkListBoxRow* _tmp0_ = NULL;
	GtkListBoxRow* _tmp1_ = NULL;
	GtkListBoxRow* _tmp2_ = NULL;
	SqlClientServer* svr = NULL;
	SqlClient* _tmp3_ = NULL;
	GtkListBoxRow* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	SqlClientServer* _tmp7_ = NULL;
	SqlClientServer* _tmp8_ = NULL;
	SqlClientServer* _tmp10_ = NULL;
	SqlClientServer* _tmp11_ = NULL;
	GtkEntry* _tmp12_ = NULL;
	SqlClientServer* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	GtkEntry* _tmp15_ = NULL;
	SqlClientServer* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	GtkEntry* _tmp18_ = NULL;
	SqlClientServer* _tmp19_ = NULL;
	const gchar* _tmp20_ = NULL;
	GtkEntry* _tmp21_ = NULL;
	SqlClientServer* _tmp22_ = NULL;
	const gchar* _tmp23_ = NULL;
	GtkSpinButton* _tmp24_ = NULL;
	SqlClientServer* _tmp25_ = NULL;
	gint _tmp26_ = 0;
	GtkEntry* _tmp27_ = NULL;
	SqlClientServer* _tmp28_ = NULL;
	const gchar* _tmp29_ = NULL;
	GtkSwitch* _tmp30_ = NULL;
	SqlClientServer* _tmp31_ = NULL;
	gboolean _tmp32_ = FALSE;
	gboolean _tmp33_ = FALSE;
	GtkTextView* _tmp34_ = NULL;
	GtkTextBuffer* _tmp35_ = NULL;
	GtkTextBuffer* _tmp36_ = NULL;
	SqlClientServer* _tmp37_ = NULL;
	const gchar* _tmp38_ = NULL;
	GtkListBox* _tmp39_ = NULL;
	GList* _tmp40_ = NULL;
	GtkListBox* _tmp60_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = row;
	if (_tmp0_ == NULL) {
		_sql_client_server_unref0 (self->priv->current_server);
		self->priv->current_server = NULL;
		_g_object_unref0 (self->priv->select_row);
		self->priv->select_row = NULL;
	}
	server_manager_set_forms_active (self, TRUE);
	_tmp1_ = row;
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_g_object_unref0 (self->priv->select_row);
	self->priv->select_row = _tmp2_;
	_tmp3_ = self->priv->sqlclient;
	_tmp4_ = row;
	_tmp5_ = gtk_widget_get_name ((GtkWidget*) _tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = sql_client_get_server (_tmp3_, _tmp6_);
	svr = _tmp7_;
	_tmp8_ = svr;
	if (_tmp8_ == NULL) {
		SqlClientServer* _tmp9_ = NULL;
		_tmp9_ = sql_client_server_new ();
		_sql_client_server_unref0 (svr);
		svr = _tmp9_;
	}
	_tmp10_ = svr;
	_tmp11_ = _sql_client_server_ref0 (_tmp10_);
	_sql_client_server_unref0 (self->priv->current_server);
	self->priv->current_server = _tmp11_;
	_tmp12_ = self->priv->host;
	_tmp13_ = svr;
	_tmp14_ = _tmp13_->host;
	gtk_entry_set_text (_tmp12_, _tmp14_);
	_tmp15_ = self->priv->user;
	_tmp16_ = svr;
	_tmp17_ = _tmp16_->username;
	gtk_entry_set_text (_tmp15_, _tmp17_);
	_tmp18_ = self->priv->real;
	_tmp19_ = svr;
	_tmp20_ = _tmp19_->realname;
	gtk_entry_set_text (_tmp18_, _tmp20_);
	_tmp21_ = self->priv->pass;
	_tmp22_ = svr;
	_tmp23_ = _tmp22_->password;
	gtk_entry_set_text (_tmp21_, _tmp23_);
	_tmp24_ = self->priv->port;
	_tmp25_ = svr;
	_tmp26_ = _tmp25_->port;
	gtk_spin_button_set_value (_tmp24_, (gdouble) _tmp26_);
	_tmp27_ = self->priv->nick;
	_tmp28_ = svr;
	_tmp29_ = _tmp28_->nickname;
	gtk_entry_set_text (_tmp27_, _tmp29_);
	_tmp30_ = self->priv->encrypt;
	_tmp31_ = svr;
	_tmp32_ = _tmp31_->encryption;
	g_signal_emit_by_name (_tmp30_, "state-set", _tmp32_, &_tmp33_);
	_tmp34_ = self->priv->connect_cmds;
	_tmp35_ = gtk_text_view_get_buffer (_tmp34_);
	_tmp36_ = _tmp35_;
	_tmp37_ = svr;
	_tmp38_ = _tmp37_->connect_cmds;
	g_object_set (_tmp36_, "text", _tmp38_, NULL);
	_tmp39_ = self->priv->channels;
	_tmp40_ = gtk_container_get_children ((GtkContainer*) _tmp39_);
	{
		GList* lbr_collection = NULL;
		GList* lbr_it = NULL;
		lbr_collection = _tmp40_;
		for (lbr_it = lbr_collection; lbr_it != NULL; lbr_it = lbr_it->next) {
			GtkWidget* _tmp41_ = NULL;
			GtkWidget* lbr = NULL;
			_tmp41_ = _g_object_ref0 ((GtkWidget*) lbr_it->data);
			lbr = _tmp41_;
			{
				GtkListBox* _tmp42_ = NULL;
				GtkWidget* _tmp43_ = NULL;
				_tmp42_ = self->priv->channels;
				_tmp43_ = lbr;
				gtk_container_remove ((GtkContainer*) _tmp42_, _tmp43_);
				_g_object_unref0 (lbr);
			}
		}
		_g_list_free0 (lbr_collection);
	}
	{
		GeeLinkedList* _chn_list = NULL;
		SqlClientServer* _tmp44_ = NULL;
		GeeLinkedList* _tmp45_ = NULL;
		GeeLinkedList* _tmp46_ = NULL;
		gint _chn_size = 0;
		GeeLinkedList* _tmp47_ = NULL;
		gint _tmp48_ = 0;
		gint _tmp49_ = 0;
		gint _chn_index = 0;
		_tmp44_ = svr;
		_tmp45_ = _tmp44_->channels;
		_tmp46_ = _g_object_ref0 (_tmp45_);
		_chn_list = _tmp46_;
		_tmp47_ = _chn_list;
		_tmp48_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp47_);
		_tmp49_ = _tmp48_;
		_chn_size = _tmp49_;
		_chn_index = -1;
		while (TRUE) {
			gint _tmp50_ = 0;
			gint _tmp51_ = 0;
			gint _tmp52_ = 0;
			SqlClientChannel* chn = NULL;
			GeeLinkedList* _tmp53_ = NULL;
			gint _tmp54_ = 0;
			gpointer _tmp55_ = NULL;
			GtkListBoxRow* lbr = NULL;
			SqlClientChannel* _tmp56_ = NULL;
			GtkListBoxRow* _tmp57_ = NULL;
			GtkListBox* _tmp58_ = NULL;
			GtkListBoxRow* _tmp59_ = NULL;
			_tmp50_ = _chn_index;
			_chn_index = _tmp50_ + 1;
			_tmp51_ = _chn_index;
			_tmp52_ = _chn_size;
			if (!(_tmp51_ < _tmp52_)) {
				break;
			}
			_tmp53_ = _chn_list;
			_tmp54_ = _chn_index;
			_tmp55_ = gee_abstract_list_get ((GeeAbstractList*) _tmp53_, _tmp54_);
			chn = (SqlClientChannel*) _tmp55_;
			_tmp56_ = chn;
			_tmp57_ = server_manager_get_channel_list_box_row (self, _tmp56_);
			lbr = _tmp57_;
			_tmp58_ = self->priv->channels;
			_tmp59_ = lbr;
			gtk_list_box_insert (_tmp58_, (GtkWidget*) _tmp59_, -1);
			_g_object_unref0 (lbr);
			_sql_client_channel_unref0 (chn);
		}
		_g_object_unref0 (_chn_list);
	}
	_tmp60_ = self->priv->channels;
	gtk_widget_show_all ((GtkWidget*) _tmp60_);
	_sql_client_server_unref0 (svr);
}


static gboolean _sql_client_channel_update_autoconnect_gtk_switch_state_set (GtkSwitch* _sender, gboolean state, gpointer self) {
	gboolean result;
	result = sql_client_channel_update_autoconnect ((SqlClientChannel*) self, state);
	return result;
}


static GtkListBoxRow* server_manager_get_channel_list_box_row (ServerManager* self, SqlClientChannel* channel) {
	GtkListBoxRow* result = NULL;
	GtkBox* box = NULL;
	GtkBox* _tmp0_ = NULL;
	GtkListBoxRow* lbr = NULL;
	GtkListBoxRow* _tmp1_ = NULL;
	GtkLabel* lbl = NULL;
	SqlClientChannel* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkSwitch* ac_switch = NULL;
	GtkSwitch* _tmp5_ = NULL;
	GtkBox* switch_box = NULL;
	GtkBox* _tmp6_ = NULL;
	SqlClientChannel* _tmp7_ = NULL;
	gboolean _tmp8_ = FALSE;
	SqlClientChannel* _tmp9_ = NULL;
	GtkSwitch* _tmp10_ = NULL;
	SqlClientChannel* _tmp11_ = NULL;
	const gchar* _tmp12_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (channel != NULL, NULL);
	_tmp0_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 1);
	g_object_ref_sink (_tmp0_);
	box = _tmp0_;
	_tmp1_ = (GtkListBoxRow*) gtk_list_box_row_new ();
	g_object_ref_sink (_tmp1_);
	lbr = _tmp1_;
	_tmp2_ = channel;
	_tmp3_ = _tmp2_->channel;
	_tmp4_ = (GtkLabel*) gtk_label_new (_tmp3_);
	g_object_ref_sink (_tmp4_);
	lbl = _tmp4_;
	_tmp5_ = (GtkSwitch*) gtk_switch_new ();
	g_object_ref_sink (_tmp5_);
	ac_switch = _tmp5_;
	_tmp6_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 1);
	g_object_ref_sink (_tmp6_);
	switch_box = _tmp6_;
	gtk_widget_set_halign ((GtkWidget*) lbl, GTK_ALIGN_START);
	gtk_box_pack_start (switch_box, (GtkWidget*) ac_switch, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start (box, (GtkWidget*) lbl, TRUE, TRUE, (guint) 0);
	gtk_box_pack_end (box, (GtkWidget*) switch_box, FALSE, FALSE, (guint) 0);
	_tmp7_ = channel;
	_tmp8_ = _tmp7_->autoconnect;
	gtk_switch_set_state (ac_switch, _tmp8_);
	_tmp9_ = channel;
	g_signal_connect (ac_switch, "state-set", (GCallback) _sql_client_channel_update_autoconnect_gtk_switch_state_set, _tmp9_);
	gtk_container_add ((GtkContainer*) lbr, (GtkWidget*) box);
	gtk_widget_show_all ((GtkWidget*) lbr);
	_tmp10_ = _g_object_ref0 (ac_switch);
	g_object_set_data_full ((GObject*) box, "ac_switch", _tmp10_, g_object_unref);
	_tmp11_ = channel;
	_tmp12_ = _tmp11_->channel;
	gtk_widget_set_name ((GtkWidget*) lbr, _tmp12_);
	result = lbr;
	_g_object_unref0 (switch_box);
	_g_object_unref0 (ac_switch);
	_g_object_unref0 (lbl);
	_g_object_unref0 (box);
	return result;
}


static GtkListBoxRow* server_manager_get_list_box_row (ServerManager* self, const gchar* name) {
	GtkListBoxRow* result = NULL;
	GtkListBoxRow* lbr = NULL;
	GtkListBoxRow* _tmp0_ = NULL;
	GtkLabel* lbl = NULL;
	const gchar* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = (GtkListBoxRow*) gtk_list_box_row_new ();
	g_object_ref_sink (_tmp0_);
	lbr = _tmp0_;
	_tmp1_ = name;
	_tmp2_ = (GtkLabel*) gtk_label_new (_tmp1_);
	g_object_ref_sink (_tmp2_);
	lbl = _tmp2_;
	gtk_container_add ((GtkContainer*) lbr, (GtkWidget*) lbl);
	gtk_widget_set_halign ((GtkWidget*) lbr, GTK_ALIGN_FILL);
	gtk_widget_set_halign ((GtkWidget*) lbl, GTK_ALIGN_START);
	_tmp3_ = name;
	gtk_widget_set_name ((GtkWidget*) lbr, _tmp3_);
	result = lbr;
	_g_object_unref0 (lbl);
	return result;
}


static void server_manager_add_servers (ServerManager* self) {
	GtkListBoxRow* first_row = NULL;
	g_return_if_fail (self != NULL);
	first_row = NULL;
	{
		GeeIterator* _svr_it = NULL;
		GeeHashMap* _tmp0_ = NULL;
		GeeSet* _tmp1_ = NULL;
		GeeSet* _tmp2_ = NULL;
		GeeSet* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		GeeIterator* _tmp5_ = NULL;
		_tmp0_ = sql_client_servers;
		_tmp1_ = gee_abstract_map_get_entries ((GeeMap*) _tmp0_);
		_tmp2_ = _tmp1_;
		_tmp3_ = _tmp2_;
		_tmp4_ = gee_iterable_iterator ((GeeIterable*) _tmp3_);
		_tmp5_ = _tmp4_;
		_g_object_unref0 (_tmp3_);
		_svr_it = _tmp5_;
		while (TRUE) {
			GeeIterator* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			GeeMapEntry* svr = NULL;
			GeeIterator* _tmp8_ = NULL;
			gpointer _tmp9_ = NULL;
			SqlClientServer* server = NULL;
			GeeMapEntry* _tmp10_ = NULL;
			gconstpointer _tmp11_ = NULL;
			SqlClientServer* _tmp12_ = NULL;
			SqlClientServer* _tmp13_ = NULL;
			GtkListBoxRow* lbr = NULL;
			SqlClientServer* _tmp14_ = NULL;
			const gchar* _tmp15_ = NULL;
			GtkListBoxRow* _tmp16_ = NULL;
			GtkListBox* _tmp17_ = NULL;
			GtkListBoxRow* _tmp18_ = NULL;
			GtkListBoxRow* _tmp19_ = NULL;
			_tmp6_ = _svr_it;
			_tmp7_ = gee_iterator_next (_tmp6_);
			if (!_tmp7_) {
				break;
			}
			_tmp8_ = _svr_it;
			_tmp9_ = gee_iterator_get (_tmp8_);
			svr = (GeeMapEntry*) _tmp9_;
			_tmp10_ = svr;
			_tmp11_ = gee_map_entry_get_value (_tmp10_);
			_tmp12_ = _tmp11_;
			_tmp13_ = _sql_client_server_ref0 ((SqlClientServer*) _tmp12_);
			server = _tmp13_;
			_tmp14_ = server;
			_tmp15_ = _tmp14_->host;
			_tmp16_ = server_manager_get_list_box_row (self, _tmp15_);
			lbr = _tmp16_;
			_tmp17_ = self->priv->servers;
			_tmp18_ = lbr;
			gtk_list_box_insert (_tmp17_, (GtkWidget*) _tmp18_, -1);
			_tmp19_ = first_row;
			if (_tmp19_ == NULL) {
				GtkListBoxRow* _tmp20_ = NULL;
				GtkListBoxRow* _tmp21_ = NULL;
				_tmp20_ = lbr;
				_tmp21_ = _g_object_ref0 (_tmp20_);
				_g_object_unref0 (first_row);
				first_row = _tmp21_;
			}
			_g_object_unref0 (lbr);
			_sql_client_server_unref0 (server);
			_g_object_unref0 (svr);
		}
		_g_object_unref0 (_svr_it);
	}
	_g_object_unref0 (first_row);
}


static gboolean server_manager_remove_channel_clicked (ServerManager* self, GdkEventButton* event) {
	gboolean result = FALSE;
	GtkListBoxRow* widget = NULL;
	GtkListBox* _tmp0_ = NULL;
	GtkListBoxRow* _tmp1_ = NULL;
	GtkListBoxRow* _tmp2_ = NULL;
	GtkListBox* _tmp3_ = NULL;
	GtkListBoxRow* _tmp4_ = NULL;
	SqlClientChannel* channel = NULL;
	SqlClientServer* _tmp5_ = NULL;
	GtkListBoxRow* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	SqlClientChannel* _tmp9_ = NULL;
	SqlClientChannel* _tmp10_ = NULL;
	SqlClientChannel* _tmp11_ = NULL;
	SqlClientServer* _tmp12_ = NULL;
	GeeHashMap* _tmp13_ = NULL;
	SqlClientServer* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	gpointer _tmp16_ = NULL;
	SqlClientServer* _tmp17_ = NULL;
	GeeLinkedList* _tmp18_ = NULL;
	GeeLinkedList* _tmp19_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->channels;
	_tmp1_ = gtk_list_box_get_selected_row (_tmp0_);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	widget = _tmp2_;
	_tmp3_ = self->priv->channels;
	_tmp4_ = widget;
	gtk_container_remove ((GtkContainer*) _tmp3_, (GtkWidget*) _tmp4_);
	_tmp5_ = self->priv->current_server;
	_tmp6_ = widget;
	_tmp7_ = gtk_widget_get_name ((GtkWidget*) _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = sql_client_server_find_channel_by_name (_tmp5_, _tmp8_);
	channel = _tmp9_;
	_tmp10_ = channel;
	if (_tmp10_ == NULL) {
		result = FALSE;
		_sql_client_channel_unref0 (channel);
		_g_object_unref0 (widget);
		return result;
	}
	_tmp11_ = channel;
	sql_client_channel_delete_channel (_tmp11_);
	_tmp12_ = self->priv->current_server;
	_tmp13_ = sql_client_servers;
	_tmp14_ = self->priv->current_server;
	_tmp15_ = _tmp14_->id;
	_tmp16_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp13_, (gpointer) ((gintptr) _tmp15_));
	_tmp17_ = (SqlClientServer*) _tmp16_;
	_tmp18_ = _tmp17_->channels;
	_tmp19_ = _g_object_ref0 (_tmp18_);
	_g_object_unref0 (_tmp12_->channels);
	_tmp12_->channels = _tmp19_;
	_sql_client_server_unref0 (_tmp17_);
	result = FALSE;
	_sql_client_channel_unref0 (channel);
	_g_object_unref0 (widget);
	return result;
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_ = 0L;
	gchar _tmp1_ = '\0';
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static gboolean _vala_char_array_contains (gchar* stack, int stack_length, gchar needle) {
	int i;
	for (i = 0; i < stack_length; i++) {
		if (needle == stack[i]) {
			return TRUE;
		}
	}
	return FALSE;
}


static Block12Data* block12_data_ref (Block12Data* _data12_) {
	g_atomic_int_inc (&_data12_->_ref_count_);
	return _data12_;
}


static void block12_data_unref (void * _userdata_) {
	Block12Data* _data12_;
	_data12_ = (Block12Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data12_->_ref_count_)) {
		ServerManager* self;
		self = _data12_->self;
		_g_object_unref0 (_data12_->msg);
		_g_object_unref0 (self);
		g_slice_free (Block12Data, _data12_);
	}
}


static void ___lambda26_ (Block12Data* _data12_, gint response_id) {
	ServerManager* self;
	GtkEntry* _tmp0_ = NULL;
	GtkMessageDialog* _tmp1_ = NULL;
	self = _data12_->self;
	_tmp0_ = self->priv->host;
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
	_tmp1_ = _data12_->msg;
	gtk_widget_destroy ((GtkWidget*) _tmp1_);
}


static void ____lambda26__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
	___lambda26_ (self, response_id);
}


static gboolean server_manager_add_channel_clicked (ServerManager* self, GdkEventButton* event) {
	gboolean result = FALSE;
	gchar* chan_name = NULL;
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	const gchar* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	const gchar* _tmp11_ = NULL;
	gchar _tmp12_ = '\0';
	gchar* _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	SqlClientChannel* channel = NULL;
	SqlClientChannel* _tmp27_ = NULL;
	SqlClientChannel* _tmp28_ = NULL;
	SqlClientServer* _tmp29_ = NULL;
	gint _tmp30_ = 0;
	SqlClientChannel* _tmp31_ = NULL;
	const gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	SqlClientChannel* _tmp34_ = NULL;
	GtkListBoxRow* lbr = NULL;
	SqlClientChannel* _tmp35_ = NULL;
	GtkListBoxRow* _tmp36_ = NULL;
	GtkEntry* _tmp37_ = NULL;
	GtkListBox* _tmp38_ = NULL;
	GtkListBoxRow* _tmp39_ = NULL;
	GtkListBox* _tmp40_ = NULL;
	SqlClientServer* _tmp41_ = NULL;
	GeeHashMap* _tmp42_ = NULL;
	SqlClientServer* _tmp43_ = NULL;
	gint _tmp44_ = 0;
	gpointer _tmp45_ = NULL;
	SqlClientServer* _tmp46_ = NULL;
	GeeLinkedList* _tmp47_ = NULL;
	GeeLinkedList* _tmp48_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->new_channel;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = string_strip (_tmp1_);
	chan_name = _tmp2_;
	_tmp4_ = chan_name;
	_tmp5_ = strlen (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ == 0) {
		_tmp3_ = TRUE;
	} else {
		SqlClientServer* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		SqlClientChannel* _tmp9_ = NULL;
		SqlClientChannel* _tmp10_ = NULL;
		_tmp7_ = self->priv->current_server;
		_tmp8_ = chan_name;
		_tmp9_ = sql_client_server_find_channel_by_name (_tmp7_, _tmp8_);
		_tmp10_ = _tmp9_;
		_tmp3_ = _tmp10_ != NULL;
		_sql_client_channel_unref0 (_tmp10_);
	}
	if (_tmp3_) {
		result = FALSE;
		_g_free0 (chan_name);
		return result;
	}
	_tmp11_ = chan_name;
	_tmp12_ = string_get (_tmp11_, (glong) 0);
	_tmp13_ = self->CHANNEL_CHAR;
	_tmp13__length1 = self->CHANNEL_CHAR_length1;
	if (!_vala_char_array_contains (_tmp13_, _tmp13__length1, _tmp12_)) {
		Block12Data* _data12_;
		GtkWindow* _tmp14_ = NULL;
		const gchar* _tmp15_ = NULL;
		gchar* _tmp16_ = NULL;
		gint _tmp16__length1 = 0;
		gchar _tmp17_ = '\0';
		gchar* _tmp18_ = NULL;
		gint _tmp18__length1 = 0;
		gchar _tmp19_ = '\0';
		gchar* _tmp20_ = NULL;
		gint _tmp20__length1 = 0;
		gchar _tmp21_ = '\0';
		gchar* _tmp22_ = NULL;
		gint _tmp22__length1 = 0;
		gchar _tmp23_ = '\0';
		GtkMessageDialog* _tmp24_ = NULL;
		GtkMessageDialog* _tmp25_ = NULL;
		GtkMessageDialog* _tmp26_ = NULL;
		_data12_ = g_slice_new0 (Block12Data);
		_data12_->_ref_count_ = 1;
		_data12_->self = g_object_ref (self);
		_tmp14_ = self->window;
		_tmp15_ = server_manager_CHANNEL_ERROR;
		_tmp16_ = self->CHANNEL_CHAR;
		_tmp16__length1 = self->CHANNEL_CHAR_length1;
		_tmp17_ = _tmp16_[0];
		_tmp18_ = self->CHANNEL_CHAR;
		_tmp18__length1 = self->CHANNEL_CHAR_length1;
		_tmp19_ = _tmp18_[1];
		_tmp20_ = self->CHANNEL_CHAR;
		_tmp20__length1 = self->CHANNEL_CHAR_length1;
		_tmp21_ = _tmp20_[2];
		_tmp22_ = self->CHANNEL_CHAR;
		_tmp22__length1 = self->CHANNEL_CHAR_length1;
		_tmp23_ = _tmp22_[3];
		_tmp24_ = (GtkMessageDialog*) gtk_message_dialog_new (_tmp14_, GTK_DIALOG_MODAL, GTK_MESSAGE_WARNING, GTK_BUTTONS_OK, _tmp15_, _tmp17_, _tmp19_, _tmp21_, _tmp23_);
		g_object_ref_sink (_tmp24_);
		_data12_->msg = _tmp24_;
		_tmp25_ = _data12_->msg;
		g_signal_connect_data ((GtkDialog*) _tmp25_, "response", (GCallback) ____lambda26__gtk_dialog_response, block12_data_ref (_data12_), (GClosureNotify) block12_data_unref, 0);
		_tmp26_ = _data12_->msg;
		gtk_widget_show ((GtkWidget*) _tmp26_);
		result = FALSE;
		block12_data_unref (_data12_);
		_data12_ = NULL;
		_g_free0 (chan_name);
		return result;
	}
	_tmp27_ = sql_client_channel_new ();
	channel = _tmp27_;
	_tmp28_ = channel;
	_tmp29_ = self->priv->current_server;
	_tmp30_ = _tmp29_->id;
	_tmp28_->server_id = _tmp30_;
	_tmp31_ = channel;
	_tmp32_ = chan_name;
	_tmp33_ = g_strdup (_tmp32_);
	_g_free0 (_tmp31_->channel);
	_tmp31_->channel = _tmp33_;
	_tmp34_ = channel;
	sql_client_channel_add_channel (_tmp34_);
	_tmp35_ = channel;
	_tmp36_ = server_manager_get_channel_list_box_row (self, _tmp35_);
	lbr = _tmp36_;
	_tmp37_ = self->priv->new_channel;
	gtk_entry_set_text (_tmp37_, "");
	_tmp38_ = self->priv->channels;
	_tmp39_ = lbr;
	gtk_container_add ((GtkContainer*) _tmp38_, (GtkWidget*) _tmp39_);
	_tmp40_ = self->priv->channels;
	gtk_widget_show_all ((GtkWidget*) _tmp40_);
	_tmp41_ = self->priv->current_server;
	_tmp42_ = sql_client_servers;
	_tmp43_ = self->priv->current_server;
	_tmp44_ = _tmp43_->id;
	_tmp45_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp42_, (gpointer) ((gintptr) _tmp44_));
	_tmp46_ = (SqlClientServer*) _tmp45_;
	_tmp47_ = _tmp46_->channels;
	_tmp48_ = _g_object_ref0 (_tmp47_);
	_g_object_unref0 (_tmp41_->channels);
	_tmp41_->channels = _tmp48_;
	_sql_client_server_unref0 (_tmp46_);
	result = FALSE;
	_g_object_unref0 (lbr);
	_sql_client_channel_unref0 (channel);
	_g_free0 (chan_name);
	return result;
}


static gboolean server_manager_remove_server_clicked (ServerManager* self, GdkEventButton* event) {
	gboolean result = FALSE;
	GtkListBoxRow* widget = NULL;
	GtkListBox* _tmp0_ = NULL;
	GtkListBoxRow* _tmp1_ = NULL;
	GtkListBoxRow* _tmp2_ = NULL;
	GtkListBoxRow* _tmp3_ = NULL;
	GtkListBox* _tmp4_ = NULL;
	GtkListBoxRow* _tmp5_ = NULL;
	SqlClientServer* _tmp6_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->servers;
	_tmp1_ = gtk_list_box_get_selected_row (_tmp0_);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	widget = _tmp2_;
	_tmp3_ = widget;
	if (_tmp3_ == NULL) {
		result = TRUE;
		_g_object_unref0 (widget);
		return result;
	}
	_tmp4_ = self->priv->servers;
	_tmp5_ = widget;
	gtk_container_remove ((GtkContainer*) _tmp4_, (GtkWidget*) _tmp5_);
	server_manager_set_forms_active (self, FALSE);
	_tmp6_ = self->priv->current_server;
	sql_client_server_remove_server (_tmp6_);
	_sql_client_server_unref0 (self->priv->current_server);
	self->priv->current_server = NULL;
	result = TRUE;
	_g_object_unref0 (widget);
	return result;
}


static void server_manager_set_forms_active (ServerManager* self, gboolean active) {
	GList* children = NULL;
	GtkGrid* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
	GList* _tmp2_ = NULL;
	GtkButton* _tmp5_ = NULL;
	GtkContainer* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->form;
	_tmp1_ = gtk_container_get_children ((GtkContainer*) _tmp0_);
	children = _tmp1_;
	_tmp2_ = children;
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
		child_collection = _tmp2_;
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
			GtkWidget* child = NULL;
			child = (GtkWidget*) child_it->data;
			{
				GtkWidget* _tmp3_ = NULL;
				gboolean _tmp4_ = FALSE;
				_tmp3_ = child;
				_tmp4_ = active;
				gtk_widget_set_sensitive (_tmp3_, _tmp4_);
			}
		}
	}
	_tmp5_ = self->priv->cancel;
	_tmp6_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) _tmp5_);
	gtk_widget_set_sensitive ((GtkWidget*) _tmp6_, TRUE);
	_g_list_free0 (children);
}


static gboolean server_manager_add_server_clicked (ServerManager* self, GdkEventButton* event) {
	gboolean result = FALSE;
	GtkListBoxRow* _tmp0_ = NULL;
	SqlClientServer* _tmp1_ = NULL;
	SqlClientServer* _tmp2_ = NULL;
	SqlClientServer* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gint id = 0;
	SqlClientServer* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	SqlClientServer* _tmp10_ = NULL;
	SqlClientServer* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	GtkListBoxRow* lbr = NULL;
	SqlClientServer* _tmp15_ = NULL;
	const gchar* _tmp16_ = NULL;
	GtkListBoxRow* _tmp17_ = NULL;
	GtkListBox* _tmp18_ = NULL;
	GtkListBox* _tmp19_ = NULL;
	GtkListBox* _tmp20_ = NULL;
	GtkEntry* _tmp21_ = NULL;
	GtkSpinButton* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->select_row;
	server_manager_save_changes (self, _tmp0_);
	_tmp1_ = sql_client_server_new ();
	_sql_client_server_unref0 (self->priv->current_server);
	self->priv->current_server = _tmp1_;
	_tmp2_ = self->priv->current_server;
	_tmp3_ = self->priv->current_server;
	_tmp4_ = g_get_user_name ();
	_tmp5_ = g_strdup (_tmp4_);
	_g_free0 (_tmp3_->nickname);
	_tmp3_->nickname = _tmp5_;
	_tmp6_ = _tmp3_->nickname;
	_tmp7_ = g_strdup (_tmp6_);
	_g_free0 (_tmp2_->username);
	_tmp2_->username = _tmp7_;
	_tmp8_ = self->priv->current_server;
	_tmp9_ = sql_client_server_add_server_empty (_tmp8_);
	id = _tmp9_;
	_tmp10_ = self->priv->current_server;
	_tmp10_->id = id;
	_tmp11_ = self->priv->current_server;
	_tmp12_ = g_strdup_printf ("%i", id);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat ("New Server ", _tmp13_, NULL);
	_g_free0 (_tmp11_->host);
	_tmp11_->host = _tmp14_;
	_g_free0 (_tmp13_);
	_tmp15_ = self->priv->current_server;
	_tmp16_ = _tmp15_->host;
	_tmp17_ = server_manager_get_list_box_row (self, _tmp16_);
	lbr = _tmp17_;
	_tmp18_ = self->priv->servers;
	gtk_list_box_insert (_tmp18_, (GtkWidget*) lbr, -1);
	_tmp19_ = self->priv->servers;
	gtk_list_box_select_row (_tmp19_, lbr);
	_tmp20_ = self->priv->servers;
	gtk_widget_show_all ((GtkWidget*) _tmp20_);
	server_manager_populate_fields (self, lbr);
	_tmp21_ = self->priv->host;
	gtk_widget_grab_focus ((GtkWidget*) _tmp21_);
	_tmp22_ = self->priv->port;
	gtk_spin_button_set_value (_tmp22_, (gdouble) ((gint) CONNECTION_DEFAULT_PORT));
	result = FALSE;
	_g_object_unref0 (lbr);
	return result;
}


static gboolean server_manager_cancel_clicked (ServerManager* self, GdkEventButton* event) {
	gboolean result = FALSE;
	GtkListBoxRow* _tmp0_ = NULL;
	GtkWindow* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->select_row;
	server_manager_save_changes (self, _tmp0_);
	_tmp1_ = self->window;
	gtk_window_close (_tmp1_);
	result = FALSE;
	return result;
}


ServerManager* server_manager_construct (GType object_type) {
	ServerManager * self = NULL;
	self = (ServerManager*) g_object_new (object_type, NULL);
	return self;
}


ServerManager* server_manager_new (void) {
	return server_manager_construct (TYPE_SERVER_MANAGER);
}


static void server_manager_class_init (ServerManagerClass * klass) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	server_manager_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (ServerManagerPrivate));
	G_OBJECT_CLASS (klass)->finalize = server_manager_finalize;
	g_signal_new ("close", TYPE_SERVER_MANAGER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	_tmp0_ = _ ("A channel name must begin with one of the following characters: %c, %c" \
", %c, %c.");
	_tmp1_ = g_strdup (_tmp0_);
	server_manager_CHANNEL_ERROR = _tmp1_;
}


static void server_manager_instance_init (ServerManager * self) {
	SqlClient* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	self->priv = SERVER_MANAGER_GET_PRIVATE (self);
	self->priv->select_row = NULL;
	_tmp0_ = sql_client_get_instance ();
	self->priv->sqlclient = _tmp0_;
	self->priv->current_server = NULL;
	self->priv->none_selected = FALSE;
	_tmp1_ = g_new0 (gchar, 4);
	_tmp1_[0] = '&';
	_tmp1_[1] = '#';
	_tmp1_[2] = '+';
	_tmp1_[3] = '!';
	self->CHANNEL_CHAR = _tmp1_;
	self->CHANNEL_CHAR_length1 = 4;
}


static void server_manager_finalize (GObject* obj) {
	ServerManager * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SERVER_MANAGER, ServerManager);
	_g_object_unref0 (self->window);
	_g_object_unref0 (self->priv->new_channel);
	_g_object_unref0 (self->priv->channels);
	_g_object_unref0 (self->priv->servers);
	_g_object_unref0 (self->priv->select_row);
	_g_object_unref0 (self->priv->sqlclient);
	_g_object_unref0 (self->priv->add_channel);
	_g_object_unref0 (self->priv->cancel);
	_g_object_unref0 (self->priv->host);
	_g_object_unref0 (self->priv->port);
	_g_object_unref0 (self->priv->real);
	_g_object_unref0 (self->priv->user);
	_g_object_unref0 (self->priv->pass);
	_g_object_unref0 (self->priv->nick);
	_g_object_unref0 (self->priv->encrypt);
	_g_object_unref0 (self->priv->connect_cmds);
	_g_object_unref0 (self->priv->form);
	_sql_client_server_unref0 (self->priv->current_server);
	self->CHANNEL_CHAR = (g_free (self->CHANNEL_CHAR), NULL);
	G_OBJECT_CLASS (server_manager_parent_class)->finalize (obj);
}


GType server_manager_get_type (void) {
	static volatile gsize server_manager_type_id__volatile = 0;
	if (g_once_init_enter (&server_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ServerManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) server_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ServerManager), 0, (GInstanceInitFunc) server_manager_instance_init, NULL };
		GType server_manager_type_id;
		server_manager_type_id = g_type_register_static (G_TYPE_OBJECT, "ServerManager", &g_define_type_info, 0);
		g_once_init_leave (&server_manager_type_id__volatile, server_manager_type_id);
	}
	return server_manager_type_id__volatile;
}



