/* sqlclient.c generated by valac 0.34.4, the Vala compiler
 * generated from sqlclient.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * sqlclient.vala
 * Copyright (C) 2015 Kyle Agronick <stack@kyle-ele>
 *
 * KyRC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * KyRC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <sqlite3.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define TYPE_SQL_CLIENT (sql_client_get_type ())
#define SQL_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SQL_CLIENT, SqlClient))
#define SQL_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SQL_CLIENT, SqlClientClass))
#define IS_SQL_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SQL_CLIENT))
#define IS_SQL_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SQL_CLIENT))
#define SQL_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SQL_CLIENT, SqlClientClass))

typedef struct _SqlClient SqlClient;
typedef struct _SqlClientClass SqlClientClass;
typedef struct _SqlClientPrivate SqlClientPrivate;

#define SQL_CLIENT_TYPE_SERVER (sql_client_server_get_type ())
#define SQL_CLIENT_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SQL_CLIENT_TYPE_SERVER, SqlClientServer))
#define SQL_CLIENT_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SQL_CLIENT_TYPE_SERVER, SqlClientServerClass))
#define SQL_CLIENT_IS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SQL_CLIENT_TYPE_SERVER))
#define SQL_CLIENT_IS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SQL_CLIENT_TYPE_SERVER))
#define SQL_CLIENT_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SQL_CLIENT_TYPE_SERVER, SqlClientServerClass))

typedef struct _SqlClientServer SqlClientServer;
typedef struct _SqlClientServerClass SqlClientServerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _sqlite3_close0(var) ((var == NULL) ? NULL : (var = (sqlite3_close (var), NULL)))
typedef struct _SqlClientServerPrivate SqlClientServerPrivate;

#define SQL_CLIENT_TYPE_CHANNEL (sql_client_channel_get_type ())
#define SQL_CLIENT_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannel))
#define SQL_CLIENT_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannelClass))
#define SQL_CLIENT_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SQL_CLIENT_TYPE_CHANNEL))
#define SQL_CLIENT_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SQL_CLIENT_TYPE_CHANNEL))
#define SQL_CLIENT_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannelClass))

typedef struct _SqlClientChannel SqlClientChannel;
typedef struct _SqlClientChannelClass SqlClientChannelClass;
typedef struct _SqlClientChannelPrivate SqlClientChannelPrivate;
#define _sql_client_channel_unref0(var) ((var == NULL) ? NULL : (var = (sql_client_channel_unref (var), NULL)))
#define _sql_client_server_unref0(var) ((var == NULL) ? NULL : (var = (sql_client_server_unref (var), NULL)))
typedef struct _Block9Data Block9Data;
#define _sqlite3_finalize0(var) ((var == NULL) ? NULL : (var = (sqlite3_finalize (var), NULL)))
typedef struct _SqlClientParamSpecServer SqlClientParamSpecServer;
typedef struct _SqlClientParamSpecChannel SqlClientParamSpecChannel;

struct _SqlClient {
	GObject parent_instance;
	SqlClientPrivate * priv;
};

struct _SqlClientClass {
	GObjectClass parent_class;
};

struct _SqlClientServer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SqlClientServerPrivate * priv;
	gint id;
	gchar* host;
	gint port;
	gchar* nickname;
	gchar* realname;
	gchar* username;
	gchar* password;
	gchar* on_connect;
	gboolean encryption;
	gboolean autoconnect;
	gboolean validate_server;
	gchar* connect_cmds;
	GeeLinkedList* channels;
};

struct _SqlClientServerClass {
	GTypeClass parent_class;
	void (*finalize) (SqlClientServer *self);
};

struct _SqlClientChannel {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SqlClientChannelPrivate * priv;
	gint id;
	gint server_id;
	gchar* channel;
	gboolean autoconnect;
};

struct _SqlClientChannelClass {
	GTypeClass parent_class;
	void (*finalize) (SqlClientChannel *self);
};

struct _Block9Data {
	int _ref_count_;
	SqlClientServer* self;
	gboolean exists;
};

struct _SqlClientParamSpecServer {
	GParamSpec parent_instance;
};

struct _SqlClientParamSpecChannel {
	GParamSpec parent_instance;
};


static gpointer sql_client_parent_class = NULL;
static SqlClient* sql_client_self;
static SqlClient* sql_client_self = NULL;
extern sqlite3* sql_client_db;
sqlite3* sql_client_db = NULL;
extern GeeHashMap* sql_client_servers;
GeeHashMap* sql_client_servers = NULL;
static gpointer sql_client_server_parent_class = NULL;
static gpointer sql_client_channel_parent_class = NULL;

GType sql_client_get_type (void) G_GNUC_CONST;
enum  {
	SQL_CLIENT_DUMMY_PROPERTY
};
gpointer sql_client_server_ref (gpointer instance);
void sql_client_server_unref (gpointer instance);
GParamSpec* sql_client_param_spec_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sql_client_value_set_server (GValue* value, gpointer v_object);
void sql_client_value_take_server (GValue* value, gpointer v_object);
gpointer sql_client_value_get_server (const GValue* value);
GType sql_client_server_get_type (void) G_GNUC_CONST;
#define SQL_CLIENT_DB_FILE "relay02.db"
static SqlClient* sql_client_new (void);
static SqlClient* sql_client_construct (GType object_type);
static void sql_client_init (SqlClient* self);
SqlClient* sql_client_get_instance (void);
GeeHashMap* sql_client_get_servers (SqlClient* self);
static void sql_client_add_tables (SqlClient* self);
void sql_client_refresh (SqlClient* self);
gint sql_client_refresh_callback (SqlClient* self, gint n_columns, gchar** values, int values_length1, gchar** column_names, int column_names_length1);
static gint _sql_client_refresh_callback_sqlite3_callback (gpointer self, gint n_columns, gchar** values, gchar** column_names);
gint sql_client_refresh_callback_channel (SqlClient* self, gint n_columns, gchar** values, int values_length1, gchar** column_names, int column_names_length1);
static gint _sql_client_refresh_callback_channel_sqlite3_callback (gpointer self, gint n_columns, gchar** values, gchar** column_names);
SqlClientServer* sql_client_get_server (SqlClient* self, const gchar* name);
gpointer sql_client_channel_ref (gpointer instance);
void sql_client_channel_unref (gpointer instance);
GParamSpec* sql_client_param_spec_channel (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sql_client_value_set_channel (GValue* value, gpointer v_object);
void sql_client_value_take_channel (GValue* value, gpointer v_object);
gpointer sql_client_value_get_channel (const GValue* value);
GType sql_client_channel_get_type (void) G_GNUC_CONST;
SqlClientServer* sql_client_get_server_id (SqlClient* self, gint id);
SqlClientChannel* sql_client_find_channel (SqlClientServer* current_server, const gchar* name);
SqlClientServer* sql_client_server_new (void);
SqlClientServer* sql_client_server_construct (GType object_type);
gboolean sql_client_to_bool (const gchar* input);
SqlClientChannel* sql_client_channel_new (void);
SqlClientChannel* sql_client_channel_construct (GType object_type);
gint sql_client_bool_to (gboolean b);
enum  {
	SQL_CLIENT_SERVER_DUMMY_PROPERTY
};
#define CONNECTION_DEFAULT_PORT ((guint16) 6667)
gint sql_client_server_add_server_empty (SqlClientServer* self);
gint sql_client_server_add_server (SqlClientServer* self);
gint sql_client_server_update (SqlClientServer* self);
SqlClientChannel* sql_client_server_find_channel_by_name (SqlClientServer* self, const gchar* name);
GeeLinkedList* sql_client_server_get_autoconnect_channels (SqlClientServer* self);
static Block9Data* block9_data_ref (Block9Data* _data9_);
static void block9_data_unref (void * _userdata_);
static gint __lambda25_ (Block9Data* _data9_, gint n_columns, gchar** values, int values_length1, gchar** column_names, int column_names_length1);
static gint ___lambda25__sqlite3_callback (gpointer self, gint n_columns, gchar** values, gchar** column_names);
void sql_client_server_remove_server (SqlClientServer* self);
static void sql_client_server_finalize (SqlClientServer* obj);
enum  {
	SQL_CLIENT_CHANNEL_DUMMY_PROPERTY
};
void sql_client_channel_delete_channel (SqlClientChannel* self);
static void sql_client_channel_channel_query (SqlClientChannel* self, const gchar* sql);
void sql_client_channel_add_channel (SqlClientChannel* self);
gboolean sql_client_channel_update_autoconnect (SqlClientChannel* self, gboolean state);
static void sql_client_channel_finalize (SqlClientChannel* obj);
static void sql_client_finalize (GObject* obj);

const gchar* SQL_CLIENT_SERVER_keys[11] = {"host", "port", "nickname", "realname", "username", "password", "on_connect", "encryption", "validate_server", "autoconnect", "connect_cmds"};

static SqlClient* sql_client_construct (GType object_type) {
	SqlClient * self = NULL;
	self = (SqlClient*) g_object_new (object_type, NULL);
	sql_client_init (self);
	return self;
}


static SqlClient* sql_client_new (void) {
	return sql_client_construct (TYPE_SQL_CLIENT);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


SqlClient* sql_client_get_instance (void) {
	SqlClient* result = NULL;
	SqlClient* _tmp0_ = NULL;
	SqlClient* _tmp2_ = NULL;
	SqlClient* _tmp3_ = NULL;
	_tmp0_ = sql_client_self;
	if (_tmp0_ == NULL) {
		SqlClient* _tmp1_ = NULL;
		_tmp1_ = sql_client_new ();
		_g_object_unref0 (sql_client_self);
		sql_client_self = _tmp1_;
	}
	_tmp2_ = sql_client_self;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}


GeeHashMap* sql_client_get_servers (SqlClient* self) {
	GeeHashMap* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = sql_client_servers;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


static void sql_client_init (SqlClient* self) {
	gchar* confbase = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GFile* dir = NULL;
	const gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	gchar* conffile = NULL;
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	gint ec = 0;
	const gchar* _tmp17_ = NULL;
	sqlite3* _tmp18_ = NULL;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_get_user_config_dir ();
	_tmp1_ = g_strconcat (_tmp0_, "/relay", NULL);
	confbase = _tmp1_;
	_tmp2_ = confbase;
	_tmp3_ = g_file_new_for_path (_tmp2_);
	dir = _tmp3_;
	{
		GFile* _tmp4_ = NULL;
		gboolean _tmp5_ = FALSE;
		_tmp4_ = dir;
		_tmp5_ = g_file_query_exists (_tmp4_, NULL);
		if (!_tmp5_) {
			GFile* _tmp6_ = NULL;
			_tmp6_ = dir;
			g_file_make_directory (_tmp6_, NULL, &_inner_error_);
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch2_g_error;
			}
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp7_ = confbase;
		_tmp8_ = g_strconcat ("Unable to create database. Can not write to ", _tmp7_, NULL);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strconcat (_tmp9_, ". Program will not function.", NULL);
		_tmp11_ = _tmp10_;
		g_error ("sqlclient.vala:55: %s", _tmp11_);
		_g_free0 (_tmp11_);
		_g_free0 (_tmp9_);
		_g_error_free0 (e);
	}
	__finally2:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (dir);
		_g_free0 (confbase);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp12_ = confbase;
	_tmp13_ = g_strconcat (_tmp12_, "/", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp14_, SQL_CLIENT_DB_FILE, NULL);
	_tmp16_ = _tmp15_;
	_g_free0 (_tmp14_);
	conffile = _tmp16_;
	_tmp17_ = conffile;
	_tmp19_ = sqlite3_open_v2 (_tmp17_, &_tmp18_, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL);
	_sqlite3_close0 (sql_client_db);
	sql_client_db = _tmp18_;
	ec = _tmp19_;
	_tmp20_ = ec;
	if (_tmp20_ != SQLITE_OK) {
		FILE* _tmp21_ = NULL;
		sqlite3* _tmp22_ = NULL;
		gint _tmp23_ = 0;
		sqlite3* _tmp24_ = NULL;
		const gchar* _tmp25_ = NULL;
		_tmp21_ = stderr;
		_tmp22_ = sql_client_db;
		_tmp23_ = sqlite3_errcode (_tmp22_);
		_tmp24_ = sql_client_db;
		_tmp25_ = sqlite3_errmsg (_tmp24_);
		fprintf (_tmp21_, "Can't open database: %d: %s\n", _tmp23_, _tmp25_);
	}
	sql_client_add_tables (self);
	sql_client_refresh (self);
	_g_free0 (conffile);
	_g_object_unref0 (dir);
	_g_free0 (confbase);
}


static gint _sqlite3_exec (sqlite3* self, const gchar* sql, sqlite3_callback callback, void* callback_target, gchar** errmsg) {
	gchar* _vala_errmsg = NULL;
	gint result = 0;
	const gchar* sqlite_errmsg = NULL;
	gint ec = 0;
	const gchar* _tmp0_ = NULL;
	sqlite3_callback _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	const gchar* _tmp6_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (sql != NULL, 0);
	_tmp0_ = sql;
	_tmp1_ = callback;
	_tmp1__target = callback_target;
	_tmp3_ = sqlite3_exec (self, _tmp0_, _tmp1_, _tmp1__target, (char**) (&_tmp2_));
	sqlite_errmsg = _tmp2_;
	ec = _tmp3_;
	if ((&_vala_errmsg) != NULL) {
		const gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		_tmp4_ = sqlite_errmsg;
		_tmp5_ = g_strdup (_tmp4_);
		_g_free0 (_vala_errmsg);
		_vala_errmsg = _tmp5_;
	}
	_tmp6_ = sqlite_errmsg;
	sqlite3_free ((void*) _tmp6_);
	result = ec;
	if (errmsg) {
		*errmsg = _vala_errmsg;
	} else {
		_g_free0 (_vala_errmsg);
	}
	return result;
}


static gint _sql_client_refresh_callback_sqlite3_callback (gpointer self, gint n_columns, gchar** values, gchar** column_names) {
	gint result;
	result = sql_client_refresh_callback ((SqlClient*) self, n_columns, values, -1, column_names, -1);
	return result;
}


static gint _sql_client_refresh_callback_channel_sqlite3_callback (gpointer self, gint n_columns, gchar** values, gchar** column_names) {
	gint result;
	result = sql_client_refresh_callback_channel ((SqlClient*) self, n_columns, values, -1, column_names, -1);
	return result;
}


void sql_client_refresh (SqlClient* self) {
	GeeHashMap* _tmp0_ = NULL;
	sqlite3* _tmp1_ = NULL;
	sqlite3* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = sql_client_servers;
	gee_abstract_map_clear ((GeeAbstractMap*) _tmp0_);
	_tmp1_ = sql_client_db;
	_sqlite3_exec (_tmp1_, "SELECT * from servers ORDER BY servers.host", _sql_client_refresh_callback_sqlite3_callback, self, NULL);
	_tmp2_ = sql_client_db;
	_sqlite3_exec (_tmp2_, "SELECT * from channels ORDER BY channels.channel", _sql_client_refresh_callback_channel_sqlite3_callback, self, NULL);
}


static gpointer _sql_client_server_ref0 (gpointer self) {
	return self ? sql_client_server_ref (self) : NULL;
}


SqlClientServer* sql_client_get_server (SqlClient* self, const gchar* name) {
	SqlClientServer* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		GeeIterator* _svr_it = NULL;
		GeeHashMap* _tmp0_ = NULL;
		GeeSet* _tmp1_ = NULL;
		GeeSet* _tmp2_ = NULL;
		GeeSet* _tmp3_ = NULL;
		GeeIterator* _tmp4_ = NULL;
		GeeIterator* _tmp5_ = NULL;
		_tmp0_ = sql_client_servers;
		_tmp1_ = gee_abstract_map_get_entries ((GeeMap*) _tmp0_);
		_tmp2_ = _tmp1_;
		_tmp3_ = _tmp2_;
		_tmp4_ = gee_iterable_iterator ((GeeIterable*) _tmp3_);
		_tmp5_ = _tmp4_;
		_g_object_unref0 (_tmp3_);
		_svr_it = _tmp5_;
		while (TRUE) {
			GeeIterator* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			GeeMapEntry* svr = NULL;
			GeeIterator* _tmp8_ = NULL;
			gpointer _tmp9_ = NULL;
			GeeMapEntry* _tmp10_ = NULL;
			gconstpointer _tmp11_ = NULL;
			SqlClientServer* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
			_tmp6_ = _svr_it;
			_tmp7_ = gee_iterator_next (_tmp6_);
			if (!_tmp7_) {
				break;
			}
			_tmp8_ = _svr_it;
			_tmp9_ = gee_iterator_get (_tmp8_);
			svr = (GeeMapEntry*) _tmp9_;
			_tmp10_ = svr;
			_tmp11_ = gee_map_entry_get_value (_tmp10_);
			_tmp12_ = _tmp11_;
			_tmp13_ = ((SqlClientServer*) _tmp12_)->host;
			_tmp14_ = name;
			if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
				GeeMapEntry* _tmp15_ = NULL;
				gconstpointer _tmp16_ = NULL;
				SqlClientServer* _tmp17_ = NULL;
				SqlClientServer* _tmp18_ = NULL;
				_tmp15_ = svr;
				_tmp16_ = gee_map_entry_get_value (_tmp15_);
				_tmp17_ = _tmp16_;
				_tmp18_ = _sql_client_server_ref0 ((SqlClientServer*) _tmp17_);
				result = _tmp18_;
				_g_object_unref0 (svr);
				_g_object_unref0 (_svr_it);
				return result;
			}
			_g_object_unref0 (svr);
		}
		_g_object_unref0 (_svr_it);
	}
	result = NULL;
	return result;
}


SqlClientServer* sql_client_get_server_id (SqlClient* self, gint id) {
	SqlClientServer* result = NULL;
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = sql_client_servers;
	_tmp1_ = id;
	_tmp2_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp0_, (gpointer) ((gintptr) _tmp1_));
	if (_tmp2_) {
		GeeHashMap* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gpointer _tmp5_ = NULL;
		_tmp3_ = sql_client_servers;
		_tmp4_ = id;
		_tmp5_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp3_, (gpointer) ((gintptr) _tmp4_));
		result = (SqlClientServer*) _tmp5_;
		return result;
	}
	result = NULL;
	return result;
}


SqlClientChannel* sql_client_find_channel (SqlClientServer* current_server, const gchar* name) {
	SqlClientChannel* result = NULL;
	g_return_val_if_fail (current_server != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		GeeLinkedList* _chan_list = NULL;
		SqlClientServer* _tmp0_ = NULL;
		GeeLinkedList* _tmp1_ = NULL;
		GeeLinkedList* _tmp2_ = NULL;
		gint _chan_size = 0;
		GeeLinkedList* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _chan_index = 0;
		_tmp0_ = current_server;
		_tmp1_ = _tmp0_->channels;
		_tmp2_ = _g_object_ref0 (_tmp1_);
		_chan_list = _tmp2_;
		_tmp3_ = _chan_list;
		_tmp4_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		_chan_size = _tmp5_;
		_chan_index = -1;
		while (TRUE) {
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			SqlClientChannel* chan = NULL;
			GeeLinkedList* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gpointer _tmp11_ = NULL;
			gboolean _tmp12_ = FALSE;
			SqlClientChannel* _tmp13_ = NULL;
			gint _tmp14_ = 0;
			SqlClientServer* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			_tmp6_ = _chan_index;
			_chan_index = _tmp6_ + 1;
			_tmp7_ = _chan_index;
			_tmp8_ = _chan_size;
			if (!(_tmp7_ < _tmp8_)) {
				break;
			}
			_tmp9_ = _chan_list;
			_tmp10_ = _chan_index;
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
			chan = (SqlClientChannel*) _tmp11_;
			_tmp13_ = chan;
			_tmp14_ = _tmp13_->server_id;
			_tmp15_ = current_server;
			_tmp16_ = _tmp15_->id;
			if (_tmp14_ == _tmp16_) {
				SqlClientChannel* _tmp17_ = NULL;
				const gchar* _tmp18_ = NULL;
				const gchar* _tmp19_ = NULL;
				_tmp17_ = chan;
				_tmp18_ = _tmp17_->channel;
				_tmp19_ = name;
				_tmp12_ = g_strcmp0 (_tmp18_, _tmp19_) == 0;
			} else {
				_tmp12_ = FALSE;
			}
			if (_tmp12_) {
				result = chan;
				_g_object_unref0 (_chan_list);
				return result;
			}
			_sql_client_channel_unref0 (chan);
		}
		_g_object_unref0 (_chan_list);
	}
	result = NULL;
	return result;
}


gint sql_client_refresh_callback (SqlClient* self, gint n_columns, gchar** values, int values_length1, gchar** column_names, int column_names_length1) {
	gint result = 0;
	SqlClientServer* server = NULL;
	SqlClientServer* _tmp0_ = NULL;
	GeeHashMap* _tmp76_ = NULL;
	SqlClientServer* _tmp77_ = NULL;
	gint _tmp78_ = 0;
	SqlClientServer* _tmp79_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = sql_client_server_new ();
	server = _tmp0_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_ = 0;
				gint _tmp4_ = 0;
				gchar** _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				const gchar* _tmp7_ = NULL;
				const gchar* _tmp8_ = NULL;
				GQuark _tmp10_ = 0U;
				static GQuark _tmp9_label0 = 0;
				static GQuark _tmp9_label1 = 0;
				static GQuark _tmp9_label2 = 0;
				static GQuark _tmp9_label3 = 0;
				static GQuark _tmp9_label4 = 0;
				static GQuark _tmp9_label5 = 0;
				static GQuark _tmp9_label6 = 0;
				static GQuark _tmp9_label7 = 0;
				static GQuark _tmp9_label8 = 0;
				static GQuark _tmp9_label9 = 0;
				static GQuark _tmp9_label10 = 0;
				static GQuark _tmp9_label11 = 0;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = n_columns;
				if (!(_tmp3_ < _tmp4_)) {
					break;
				}
				_tmp5_ = column_names;
				_tmp5__length1 = column_names_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = _tmp7_;
				_tmp10_ = (NULL == _tmp8_) ? 0 : g_quark_from_string (_tmp8_);
				if (_tmp10_ == ((0 != _tmp9_label0) ? _tmp9_label0 : (_tmp9_label0 = g_quark_from_static_string ("id")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp11_ = NULL;
							gchar** _tmp12_ = NULL;
							gint _tmp12__length1 = 0;
							gint _tmp13_ = 0;
							const gchar* _tmp14_ = NULL;
							gint _tmp15_ = 0;
							_tmp11_ = server;
							_tmp12_ = values;
							_tmp12__length1 = values_length1;
							_tmp13_ = i;
							_tmp14_ = _tmp12_[_tmp13_];
							_tmp15_ = atoi (_tmp14_);
							_tmp11_->id = _tmp15_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label1) ? _tmp9_label1 : (_tmp9_label1 = g_quark_from_static_string ("host")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp16_ = NULL;
							gchar** _tmp17_ = NULL;
							gint _tmp17__length1 = 0;
							gint _tmp18_ = 0;
							const gchar* _tmp19_ = NULL;
							gchar* _tmp20_ = NULL;
							_tmp16_ = server;
							_tmp17_ = values;
							_tmp17__length1 = values_length1;
							_tmp18_ = i;
							_tmp19_ = _tmp17_[_tmp18_];
							_tmp20_ = g_strdup (_tmp19_);
							_g_free0 (_tmp16_->host);
							_tmp16_->host = _tmp20_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label2) ? _tmp9_label2 : (_tmp9_label2 = g_quark_from_static_string ("port")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp21_ = NULL;
							gchar** _tmp22_ = NULL;
							gint _tmp22__length1 = 0;
							gint _tmp23_ = 0;
							const gchar* _tmp24_ = NULL;
							gint _tmp25_ = 0;
							_tmp21_ = server;
							_tmp22_ = values;
							_tmp22__length1 = values_length1;
							_tmp23_ = i;
							_tmp24_ = _tmp22_[_tmp23_];
							_tmp25_ = atoi (_tmp24_);
							_tmp21_->port = _tmp25_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label3) ? _tmp9_label3 : (_tmp9_label3 = g_quark_from_static_string ("nickname")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp26_ = NULL;
							gchar** _tmp27_ = NULL;
							gint _tmp27__length1 = 0;
							gint _tmp28_ = 0;
							const gchar* _tmp29_ = NULL;
							gchar* _tmp30_ = NULL;
							_tmp26_ = server;
							_tmp27_ = values;
							_tmp27__length1 = values_length1;
							_tmp28_ = i;
							_tmp29_ = _tmp27_[_tmp28_];
							_tmp30_ = g_strdup (_tmp29_);
							_g_free0 (_tmp26_->nickname);
							_tmp26_->nickname = _tmp30_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label4) ? _tmp9_label4 : (_tmp9_label4 = g_quark_from_static_string ("realname")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp31_ = NULL;
							gchar** _tmp32_ = NULL;
							gint _tmp32__length1 = 0;
							gint _tmp33_ = 0;
							const gchar* _tmp34_ = NULL;
							gchar* _tmp35_ = NULL;
							_tmp31_ = server;
							_tmp32_ = values;
							_tmp32__length1 = values_length1;
							_tmp33_ = i;
							_tmp34_ = _tmp32_[_tmp33_];
							_tmp35_ = g_strdup (_tmp34_);
							_g_free0 (_tmp31_->realname);
							_tmp31_->realname = _tmp35_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label5) ? _tmp9_label5 : (_tmp9_label5 = g_quark_from_static_string ("username")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp36_ = NULL;
							gchar** _tmp37_ = NULL;
							gint _tmp37__length1 = 0;
							gint _tmp38_ = 0;
							const gchar* _tmp39_ = NULL;
							gchar* _tmp40_ = NULL;
							_tmp36_ = server;
							_tmp37_ = values;
							_tmp37__length1 = values_length1;
							_tmp38_ = i;
							_tmp39_ = _tmp37_[_tmp38_];
							_tmp40_ = g_strdup (_tmp39_);
							_g_free0 (_tmp36_->username);
							_tmp36_->username = _tmp40_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label6) ? _tmp9_label6 : (_tmp9_label6 = g_quark_from_static_string ("password")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp41_ = NULL;
							gchar** _tmp42_ = NULL;
							gint _tmp42__length1 = 0;
							gint _tmp43_ = 0;
							const gchar* _tmp44_ = NULL;
							gchar* _tmp45_ = NULL;
							_tmp41_ = server;
							_tmp42_ = values;
							_tmp42__length1 = values_length1;
							_tmp43_ = i;
							_tmp44_ = _tmp42_[_tmp43_];
							_tmp45_ = g_strdup (_tmp44_);
							_g_free0 (_tmp41_->password);
							_tmp41_->password = _tmp45_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label7) ? _tmp9_label7 : (_tmp9_label7 = g_quark_from_static_string ("on_connect")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp46_ = NULL;
							gchar** _tmp47_ = NULL;
							gint _tmp47__length1 = 0;
							gint _tmp48_ = 0;
							const gchar* _tmp49_ = NULL;
							gchar* _tmp50_ = NULL;
							_tmp46_ = server;
							_tmp47_ = values;
							_tmp47__length1 = values_length1;
							_tmp48_ = i;
							_tmp49_ = _tmp47_[_tmp48_];
							_tmp50_ = g_strdup (_tmp49_);
							_g_free0 (_tmp46_->on_connect);
							_tmp46_->on_connect = _tmp50_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label8) ? _tmp9_label8 : (_tmp9_label8 = g_quark_from_static_string ("encryption")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp51_ = NULL;
							gchar** _tmp52_ = NULL;
							gint _tmp52__length1 = 0;
							gint _tmp53_ = 0;
							const gchar* _tmp54_ = NULL;
							gboolean _tmp55_ = FALSE;
							_tmp51_ = server;
							_tmp52_ = values;
							_tmp52__length1 = values_length1;
							_tmp53_ = i;
							_tmp54_ = _tmp52_[_tmp53_];
							_tmp55_ = sql_client_to_bool (_tmp54_);
							_tmp51_->encryption = _tmp55_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label9) ? _tmp9_label9 : (_tmp9_label9 = g_quark_from_static_string ("validate_server")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp56_ = NULL;
							gchar** _tmp57_ = NULL;
							gint _tmp57__length1 = 0;
							gint _tmp58_ = 0;
							const gchar* _tmp59_ = NULL;
							gboolean _tmp60_ = FALSE;
							_tmp56_ = server;
							_tmp57_ = values;
							_tmp57__length1 = values_length1;
							_tmp58_ = i;
							_tmp59_ = _tmp57_[_tmp58_];
							_tmp60_ = sql_client_to_bool (_tmp59_);
							_tmp56_->validate_server = _tmp60_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label10) ? _tmp9_label10 : (_tmp9_label10 = g_quark_from_static_string ("autoconnect")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp61_ = NULL;
							gchar** _tmp62_ = NULL;
							gint _tmp62__length1 = 0;
							gint _tmp63_ = 0;
							const gchar* _tmp64_ = NULL;
							gboolean _tmp65_ = FALSE;
							_tmp61_ = server;
							_tmp62_ = values;
							_tmp62__length1 = values_length1;
							_tmp63_ = i;
							_tmp64_ = _tmp62_[_tmp63_];
							_tmp65_ = sql_client_to_bool (_tmp64_);
							_tmp61_->autoconnect = _tmp65_;
							break;
						}
					}
				} else if (_tmp10_ == ((0 != _tmp9_label11) ? _tmp9_label11 : (_tmp9_label11 = g_quark_from_static_string ("connect_cmds")))) {
					switch (0) {
						default:
						{
							SqlClientServer* _tmp66_ = NULL;
							gchar** _tmp67_ = NULL;
							gint _tmp67__length1 = 0;
							gint _tmp68_ = 0;
							const gchar* _tmp69_ = NULL;
							gchar* _tmp70_ = NULL;
							_tmp66_ = server;
							_tmp67_ = values;
							_tmp67__length1 = values_length1;
							_tmp68_ = i;
							_tmp69_ = _tmp67_[_tmp68_];
							_tmp70_ = g_strdup (_tmp69_);
							_g_free0 (_tmp66_->connect_cmds);
							_tmp66_->connect_cmds = _tmp70_;
							break;
						}
					}
				} else {
					switch (0) {
						default:
						{
							gchar** _tmp71_ = NULL;
							gint _tmp71__length1 = 0;
							gint _tmp72_ = 0;
							const gchar* _tmp73_ = NULL;
							gchar* _tmp74_ = NULL;
							gchar* _tmp75_ = NULL;
							_tmp71_ = column_names;
							_tmp71__length1 = column_names_length1;
							_tmp72_ = i;
							_tmp73_ = _tmp71_[_tmp72_];
							_tmp74_ = g_strconcat ("Not able to handle col: ", _tmp73_, NULL);
							_tmp75_ = _tmp74_;
							g_warning ("sqlclient.vala:138: %s", _tmp75_);
							_g_free0 (_tmp75_);
							break;
						}
					}
				}
			}
		}
	}
	_tmp76_ = sql_client_servers;
	_tmp77_ = server;
	_tmp78_ = _tmp77_->id;
	_tmp79_ = server;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp76_, (gpointer) ((gintptr) _tmp78_), _tmp79_);
	result = 0;
	_sql_client_server_unref0 (server);
	return result;
}


gint sql_client_refresh_callback_channel (SqlClient* self, gint n_columns, gchar** values, int values_length1, gchar** column_names, int column_names_length1) {
	gint result = 0;
	SqlClientServer* svr = NULL;
	SqlClientServer* _tmp12_ = NULL;
	SqlClientChannel* chn = NULL;
	SqlClientChannel* _tmp13_ = NULL;
	SqlClientServer* _tmp44_ = NULL;
	GeeLinkedList* _tmp45_ = NULL;
	SqlClientChannel* _tmp46_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	svr = NULL;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				gint _tmp3_ = 0;
				gchar** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp5_ = 0;
				const gchar* _tmp6_ = NULL;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = n_columns;
				if (!(_tmp2_ < _tmp3_)) {
					break;
				}
				_tmp4_ = column_names;
				_tmp4__length1 = column_names_length1;
				_tmp5_ = i;
				_tmp6_ = _tmp4_[_tmp5_];
				if (g_strcmp0 (_tmp6_, "server_id") == 0) {
					gchar** _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					gint _tmp8_ = 0;
					const gchar* _tmp9_ = NULL;
					gint _tmp10_ = 0;
					SqlClientServer* _tmp11_ = NULL;
					_tmp7_ = values;
					_tmp7__length1 = values_length1;
					_tmp8_ = i;
					_tmp9_ = _tmp7_[_tmp8_];
					_tmp10_ = atoi (_tmp9_);
					_tmp11_ = sql_client_get_server_id (self, _tmp10_);
					_sql_client_server_unref0 (svr);
					svr = _tmp11_;
				}
			}
		}
	}
	_tmp12_ = svr;
	if (_tmp12_ == NULL) {
		result = 0;
		_sql_client_server_unref0 (svr);
		return result;
	}
	_tmp13_ = sql_client_channel_new ();
	chn = _tmp13_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp14_ = FALSE;
			_tmp14_ = TRUE;
			while (TRUE) {
				gint _tmp16_ = 0;
				gint _tmp17_ = 0;
				gchar** _tmp18_ = NULL;
				gint _tmp18__length1 = 0;
				gint _tmp19_ = 0;
				const gchar* _tmp20_ = NULL;
				const gchar* _tmp21_ = NULL;
				GQuark _tmp23_ = 0U;
				static GQuark _tmp22_label0 = 0;
				static GQuark _tmp22_label1 = 0;
				static GQuark _tmp22_label2 = 0;
				static GQuark _tmp22_label3 = 0;
				if (!_tmp14_) {
					gint _tmp15_ = 0;
					_tmp15_ = i;
					i = _tmp15_ + 1;
				}
				_tmp14_ = FALSE;
				_tmp16_ = i;
				_tmp17_ = n_columns;
				if (!(_tmp16_ < _tmp17_)) {
					break;
				}
				_tmp18_ = column_names;
				_tmp18__length1 = column_names_length1;
				_tmp19_ = i;
				_tmp20_ = _tmp18_[_tmp19_];
				_tmp21_ = _tmp20_;
				_tmp23_ = (NULL == _tmp21_) ? 0 : g_quark_from_string (_tmp21_);
				if (_tmp23_ == ((0 != _tmp22_label0) ? _tmp22_label0 : (_tmp22_label0 = g_quark_from_static_string ("id")))) {
					switch (0) {
						default:
						{
							SqlClientChannel* _tmp24_ = NULL;
							gchar** _tmp25_ = NULL;
							gint _tmp25__length1 = 0;
							gint _tmp26_ = 0;
							const gchar* _tmp27_ = NULL;
							gint _tmp28_ = 0;
							_tmp24_ = chn;
							_tmp25_ = values;
							_tmp25__length1 = values_length1;
							_tmp26_ = i;
							_tmp27_ = _tmp25_[_tmp26_];
							_tmp28_ = atoi (_tmp27_);
							_tmp24_->id = _tmp28_;
							break;
						}
					}
				} else if (_tmp23_ == ((0 != _tmp22_label1) ? _tmp22_label1 : (_tmp22_label1 = g_quark_from_static_string ("server_id")))) {
					switch (0) {
						default:
						{
							SqlClientChannel* _tmp29_ = NULL;
							gchar** _tmp30_ = NULL;
							gint _tmp30__length1 = 0;
							gint _tmp31_ = 0;
							const gchar* _tmp32_ = NULL;
							gint _tmp33_ = 0;
							_tmp29_ = chn;
							_tmp30_ = values;
							_tmp30__length1 = values_length1;
							_tmp31_ = i;
							_tmp32_ = _tmp30_[_tmp31_];
							_tmp33_ = atoi (_tmp32_);
							_tmp29_->server_id = _tmp33_;
							break;
						}
					}
				} else if (_tmp23_ == ((0 != _tmp22_label2) ? _tmp22_label2 : (_tmp22_label2 = g_quark_from_static_string ("channel")))) {
					switch (0) {
						default:
						{
							SqlClientChannel* _tmp34_ = NULL;
							gchar** _tmp35_ = NULL;
							gint _tmp35__length1 = 0;
							gint _tmp36_ = 0;
							const gchar* _tmp37_ = NULL;
							gchar* _tmp38_ = NULL;
							_tmp34_ = chn;
							_tmp35_ = values;
							_tmp35__length1 = values_length1;
							_tmp36_ = i;
							_tmp37_ = _tmp35_[_tmp36_];
							_tmp38_ = g_strdup (_tmp37_);
							_g_free0 (_tmp34_->channel);
							_tmp34_->channel = _tmp38_;
							break;
						}
					}
				} else if (_tmp23_ == ((0 != _tmp22_label3) ? _tmp22_label3 : (_tmp22_label3 = g_quark_from_static_string ("autoconnect")))) {
					switch (0) {
						default:
						{
							SqlClientChannel* _tmp39_ = NULL;
							gchar** _tmp40_ = NULL;
							gint _tmp40__length1 = 0;
							gint _tmp41_ = 0;
							const gchar* _tmp42_ = NULL;
							gboolean _tmp43_ = FALSE;
							_tmp39_ = chn;
							_tmp40_ = values;
							_tmp40__length1 = values_length1;
							_tmp41_ = i;
							_tmp42_ = _tmp40_[_tmp41_];
							_tmp43_ = sql_client_to_bool (_tmp42_);
							_tmp39_->autoconnect = _tmp43_;
							break;
						}
					}
				}
			}
		}
	}
	_tmp44_ = svr;
	_tmp45_ = _tmp44_->channels;
	_tmp46_ = chn;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp45_, _tmp46_);
	result = 0;
	_sql_client_channel_unref0 (chn);
	_sql_client_server_unref0 (svr);
	return result;
}


gboolean sql_client_to_bool (const gchar* input) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	_tmp0_ = input;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	}
	_tmp1_ = input;
	result = g_strcmp0 (_tmp1_, "1") == 0;
	return result;
}


gint sql_client_bool_to (gboolean b) {
	gint result = 0;
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	_tmp1_ = b;
	if (_tmp1_) {
		_tmp0_ = 1;
	} else {
		_tmp0_ = 0;
	}
	result = _tmp0_;
	return result;
}


static void sql_client_add_tables (SqlClient* self) {
	gchar* sql = NULL;
	gchar* _tmp0_ = NULL;
	sqlite3* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("\n" \
"\t\tCREATE TABLE IF NOT EXISTS \"servers\" (\n" \
"\t\t\"id\" INTEGER PRIMARY KEY AUTOINCREMENT,\n" \
"\t\t\"host\" TEXT NOT NULL,\n" \
"\t\t\"port\" INTEGER NOT NULL,\n" \
"\t\t\"nickname\" TEXT,\n" \
"\t\t\"realname\" TEXT,\n" \
"\t\t\"username\" TEXT,\n" \
"\t\t\"password\" TEXT,\n" \
"\t\t\"on_connect\" TEXT,\n" \
"\t\t\"connect_cmds\" TEXT,\n" \
"\t\t\"encryption\" BOOL,\n" \
"\t\t\"autoconnect\" BOOL,\n" \
"\t\t\"validate_server\" BOOL\n" \
"\t\t);\n" \
"\n" \
"\t\tCREATE TABLE IF NOT EXISTS \"channels\" (\n" \
"\t\t\"id\" INTEGER PRIMARY KEY AUTOINCREMENT,\n" \
"\t\t\"server_id\" INTEGER,\n" \
"\t\t\"channel\" TEXT,\n" \
"\t\t\"autoconnect\" BOOL\n" \
"\t\t);\n" \
"\t\t");
	sql = _tmp0_;
	_tmp1_ = sql_client_db;
	_sqlite3_exec (_tmp1_, sql, NULL, NULL, NULL);
	_g_free0 (sql);
}


gint sql_client_server_add_server_empty (SqlClientServer* self) {
	gint result = 0;
	gchar* sql = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	sqlite3* _tmp6_ = NULL;
	sqlite3* _tmp7_ = NULL;
	gint64 _tmp8_ = 0LL;
	GeeHashMap* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint _tmp11_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = g_strdup_printf ("%hu", CONNECTION_DEFAULT_PORT);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat ("INSERT INTO servers (host, port) VALUES('', ", _tmp1_, NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat (_tmp3_, ")", NULL);
	_tmp5_ = _tmp4_;
	_g_free0 (_tmp3_);
	_g_free0 (_tmp1_);
	sql = _tmp5_;
	_tmp6_ = sql_client_db;
	_sqlite3_exec (_tmp6_, sql, NULL, NULL, NULL);
	_tmp7_ = sql_client_db;
	_tmp8_ = sqlite3_last_insert_rowid (_tmp7_);
	self->id = (gint) _tmp8_;
	_tmp9_ = sql_client_servers;
	_tmp10_ = self->id;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp9_, (gpointer) ((gintptr) _tmp10_), self);
	_tmp11_ = self->id;
	result = _tmp11_;
	_g_free0 (sql);
	return result;
}


gint sql_client_server_add_server (SqlClientServer* self) {
	gint result = 0;
	gint _tmp0_ = 0;
	GeeHashMap* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = sql_client_server_add_server_empty (self);
	self->id = _tmp0_;
	_tmp1_ = sql_client_servers;
	_tmp2_ = self->id;
	gee_abstract_map_set ((GeeAbstractMap*) _tmp1_, (gpointer) ((gintptr) _tmp2_), self);
	sql_client_server_update (self);
	_tmp3_ = self->id;
	result = _tmp3_;
	return result;
}


SqlClientChannel* sql_client_server_find_channel_by_name (SqlClientServer* self, const gchar* name) {
	SqlClientChannel* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	{
		GeeLinkedList* _chan_list = NULL;
		GeeLinkedList* _tmp0_ = NULL;
		GeeLinkedList* _tmp1_ = NULL;
		gint _chan_size = 0;
		GeeLinkedList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _chan_index = 0;
		_tmp0_ = self->channels;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_chan_list = _tmp1_;
		_tmp2_ = _chan_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_chan_size = _tmp4_;
		_chan_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			SqlClientChannel* chan = NULL;
			GeeLinkedList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			SqlClientChannel* _tmp11_ = NULL;
			const gchar* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			_tmp5_ = _chan_index;
			_chan_index = _tmp5_ + 1;
			_tmp6_ = _chan_index;
			_tmp7_ = _chan_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _chan_list;
			_tmp9_ = _chan_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			chan = (SqlClientChannel*) _tmp10_;
			_tmp11_ = chan;
			_tmp12_ = _tmp11_->channel;
			_tmp13_ = name;
			if (g_strcmp0 (_tmp12_, _tmp13_) == 0) {
				result = chan;
				_g_object_unref0 (_chan_list);
				return result;
			}
			_sql_client_channel_unref0 (chan);
		}
		_g_object_unref0 (_chan_list);
	}
	result = NULL;
	return result;
}


GeeLinkedList* sql_client_server_get_autoconnect_channels (SqlClientServer* self) {
	GeeLinkedList* result = NULL;
	GeeLinkedList* returns = NULL;
	GeeLinkedList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gee_linked_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL);
	returns = _tmp0_;
	{
		GeeLinkedList* _channel_list = NULL;
		GeeLinkedList* _tmp1_ = NULL;
		GeeLinkedList* _tmp2_ = NULL;
		gint _channel_size = 0;
		GeeLinkedList* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _channel_index = 0;
		_tmp1_ = self->channels;
		_tmp2_ = _g_object_ref0 (_tmp1_);
		_channel_list = _tmp2_;
		_tmp3_ = _channel_list;
		_tmp4_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		_channel_size = _tmp5_;
		_channel_index = -1;
		while (TRUE) {
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			gint _tmp8_ = 0;
			SqlClientChannel* channel = NULL;
			GeeLinkedList* _tmp9_ = NULL;
			gint _tmp10_ = 0;
			gpointer _tmp11_ = NULL;
			SqlClientChannel* _tmp12_ = NULL;
			gboolean _tmp13_ = FALSE;
			_tmp6_ = _channel_index;
			_channel_index = _tmp6_ + 1;
			_tmp7_ = _channel_index;
			_tmp8_ = _channel_size;
			if (!(_tmp7_ < _tmp8_)) {
				break;
			}
			_tmp9_ = _channel_list;
			_tmp10_ = _channel_index;
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
			channel = (SqlClientChannel*) _tmp11_;
			_tmp12_ = channel;
			_tmp13_ = _tmp12_->autoconnect;
			if (_tmp13_) {
				GeeLinkedList* _tmp14_ = NULL;
				SqlClientChannel* _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				_tmp14_ = returns;
				_tmp15_ = channel;
				_tmp16_ = _tmp15_->channel;
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, _tmp16_);
			}
			_sql_client_channel_unref0 (channel);
		}
		_g_object_unref0 (_channel_list);
	}
	result = returns;
	return result;
}


static Block9Data* block9_data_ref (Block9Data* _data9_) {
	g_atomic_int_inc (&_data9_->_ref_count_);
	return _data9_;
}


static void block9_data_unref (void * _userdata_) {
	Block9Data* _data9_;
	_data9_ = (Block9Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data9_->_ref_count_)) {
		SqlClientServer* self;
		self = _data9_->self;
		_sql_client_server_unref0 (self);
		g_slice_free (Block9Data, _data9_);
	}
}


static gint __lambda25_ (Block9Data* _data9_, gint n_columns, gchar** values, int values_length1, gchar** column_names, int column_names_length1) {
	SqlClientServer* self;
	gint result = 0;
	self = _data9_->self;
	_data9_->exists = TRUE;
	result = 0;
	return result;
}


static gint ___lambda25__sqlite3_callback (gpointer self, gint n_columns, gchar** values, gchar** column_names) {
	gint result;
	result = __lambda25_ (self, n_columns, values, -1, column_names, -1);
	return result;
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	g_return_val_if_fail (_tmp8_, NULL);
	_tmp13_ = end;
	if (_tmp13_ >= ((glong) 0)) {
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
		_tmp14_ = end;
		_tmp15_ = string_length;
		_tmp12_ = _tmp14_ <= _tmp15_;
	} else {
		_tmp12_ = FALSE;
	}
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp16_ = start;
	_tmp17_ = end;
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	_tmp20_ = start;
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
	result = _tmp21_;
	return result;
}


gint sql_client_server_update (SqlClientServer* self) {
	gint result = 0;
	Block9Data* _data9_;
	SqlClientServer* svr = NULL;
	SqlClientServer* _tmp0_ = NULL;
	sqlite3_stmt* stmt = NULL;
	gint ok = 0;
	gchar* sql = NULL;
	SqlClientServer* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	sqlite3* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gchar* keys = NULL;
	gchar* _tmp9_ = NULL;
	const gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gboolean _tmp25_ = FALSE;
	g_return_val_if_fail (self != NULL, 0);
	_data9_ = g_slice_new0 (Block9Data);
	_data9_->_ref_count_ = 1;
	_data9_->self = sql_client_server_ref (self);
	_tmp0_ = _sql_client_server_ref0 (self);
	svr = _tmp0_;
	_tmp1_ = svr;
	_tmp2_ = _tmp1_->id;
	_tmp3_ = g_strdup_printf ("%i", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat ("SELECT id FROM servers WHERE id = ", _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_g_free0 (_tmp4_);
	sql = _tmp6_;
	_data9_->exists = FALSE;
	_tmp7_ = sql_client_db;
	_tmp8_ = sql;
	_sqlite3_exec (_tmp7_, _tmp8_, ___lambda25__sqlite3_callback, _data9_, NULL);
	_tmp9_ = g_strdup ("");
	keys = _tmp9_;
	{
		const gchar** i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = SQL_CLIENT_SERVER_keys;
		i_collection_length1 = G_N_ELEMENTS (SQL_CLIENT_SERVER_keys);
		for (i_it = 0; i_it < G_N_ELEMENTS (SQL_CLIENT_SERVER_keys); i_it = i_it + 1) {
			gchar* _tmp10_ = NULL;
			gchar* i = NULL;
			_tmp10_ = g_strdup (i_collection[i_it]);
			i = _tmp10_;
			{
				const gchar* _tmp11_ = NULL;
				const gchar* _tmp13_ = NULL;
				const gchar* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				gchar* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				_tmp11_ = keys;
				if (g_strcmp0 (_tmp11_, "") == 0) {
					gchar* _tmp12_ = NULL;
					_tmp12_ = g_strdup (" ");
					_g_free0 (keys);
					keys = _tmp12_;
				}
				_tmp13_ = keys;
				_tmp14_ = i;
				_tmp15_ = g_strconcat (_tmp14_, "=$", NULL);
				_tmp16_ = _tmp15_;
				_tmp17_ = i;
				_tmp18_ = g_strconcat (_tmp16_, _tmp17_, NULL);
				_tmp19_ = _tmp18_;
				_tmp20_ = g_strconcat (_tmp19_, ", ", NULL);
				_tmp21_ = _tmp20_;
				_tmp22_ = g_strconcat (_tmp13_, _tmp21_, NULL);
				_g_free0 (keys);
				keys = _tmp22_;
				_g_free0 (_tmp21_);
				_g_free0 (_tmp19_);
				_g_free0 (_tmp16_);
				_g_free0 (i);
			}
		}
	}
	_tmp23_ = keys;
	_tmp24_ = string_slice (_tmp23_, (glong) 0, (glong) -2);
	_g_free0 (keys);
	keys = _tmp24_;
	_tmp25_ = _data9_->exists;
	if (_tmp25_) {
		const gchar* _tmp26_ = NULL;
		gchar* _tmp27_ = NULL;
		gchar* _tmp28_ = NULL;
		gchar* _tmp29_ = NULL;
		gchar* _tmp30_ = NULL;
		SqlClientServer* _tmp31_ = NULL;
		gint _tmp32_ = 0;
		gchar* _tmp33_ = NULL;
		gchar* _tmp34_ = NULL;
		gchar* _tmp35_ = NULL;
		sqlite3* _tmp36_ = NULL;
		const gchar* _tmp37_ = NULL;
		const gchar* _tmp38_ = NULL;
		gint _tmp39_ = 0;
		gint _tmp40_ = 0;
		sqlite3_stmt* _tmp41_ = NULL;
		gint _tmp42_ = 0;
		gint _tmp43_ = 0;
		sqlite3_stmt* _tmp46_ = NULL;
		SqlClientServer* _tmp47_ = NULL;
		const gchar* _tmp48_ = NULL;
		gchar* _tmp49_ = NULL;
		GDestroyNotify _tmp50_ = NULL;
		sqlite3_stmt* _tmp51_ = NULL;
		SqlClientServer* _tmp52_ = NULL;
		gint _tmp53_ = 0;
		sqlite3_stmt* _tmp54_ = NULL;
		SqlClientServer* _tmp55_ = NULL;
		const gchar* _tmp56_ = NULL;
		gchar* _tmp57_ = NULL;
		GDestroyNotify _tmp58_ = NULL;
		sqlite3_stmt* _tmp59_ = NULL;
		SqlClientServer* _tmp60_ = NULL;
		const gchar* _tmp61_ = NULL;
		gchar* _tmp62_ = NULL;
		GDestroyNotify _tmp63_ = NULL;
		sqlite3_stmt* _tmp64_ = NULL;
		SqlClientServer* _tmp65_ = NULL;
		const gchar* _tmp66_ = NULL;
		gchar* _tmp67_ = NULL;
		GDestroyNotify _tmp68_ = NULL;
		sqlite3_stmt* _tmp69_ = NULL;
		SqlClientServer* _tmp70_ = NULL;
		const gchar* _tmp71_ = NULL;
		gchar* _tmp72_ = NULL;
		GDestroyNotify _tmp73_ = NULL;
		sqlite3_stmt* _tmp74_ = NULL;
		SqlClientServer* _tmp75_ = NULL;
		const gchar* _tmp76_ = NULL;
		gchar* _tmp77_ = NULL;
		GDestroyNotify _tmp78_ = NULL;
		sqlite3_stmt* _tmp79_ = NULL;
		SqlClientServer* _tmp80_ = NULL;
		gboolean _tmp81_ = FALSE;
		gint _tmp82_ = 0;
		sqlite3_stmt* _tmp83_ = NULL;
		SqlClientServer* _tmp84_ = NULL;
		gboolean _tmp85_ = FALSE;
		gint _tmp86_ = 0;
		sqlite3_stmt* _tmp87_ = NULL;
		SqlClientServer* _tmp88_ = NULL;
		gboolean _tmp89_ = FALSE;
		gint _tmp90_ = 0;
		sqlite3_stmt* _tmp91_ = NULL;
		SqlClientServer* _tmp92_ = NULL;
		const gchar* _tmp93_ = NULL;
		gchar* _tmp94_ = NULL;
		GDestroyNotify _tmp95_ = NULL;
		sqlite3_stmt* _tmp96_ = NULL;
		GeeHashMap* _tmp97_ = NULL;
		SqlClientServer* _tmp98_ = NULL;
		gint _tmp99_ = 0;
		SqlClientServer* _tmp100_ = NULL;
		_tmp26_ = keys;
		_tmp27_ = g_strconcat ("UPDATE servers SET ", _tmp26_, NULL);
		_tmp28_ = _tmp27_;
		_tmp29_ = g_strconcat (_tmp28_, " WHERE id = ", NULL);
		_tmp30_ = _tmp29_;
		_tmp31_ = svr;
		_tmp32_ = _tmp31_->id;
		_tmp33_ = g_strdup_printf ("%i", _tmp32_);
		_tmp34_ = _tmp33_;
		_tmp35_ = g_strconcat (_tmp30_, _tmp34_, NULL);
		_g_free0 (sql);
		sql = _tmp35_;
		_g_free0 (_tmp34_);
		_g_free0 (_tmp30_);
		_g_free0 (_tmp28_);
		_tmp36_ = sql_client_db;
		_tmp37_ = sql;
		_tmp38_ = sql;
		_tmp39_ = strlen (_tmp38_);
		_tmp40_ = _tmp39_;
		_tmp42_ = sqlite3_prepare_v2 (_tmp36_, _tmp37_, _tmp40_, &_tmp41_, NULL);
		_sqlite3_finalize0 (stmt);
		stmt = _tmp41_;
		ok = _tmp42_;
		_tmp43_ = ok;
		if (_tmp43_ != SQLITE_OK) {
			sqlite3* _tmp44_ = NULL;
			const gchar* _tmp45_ = NULL;
			_tmp44_ = sql_client_db;
			_tmp45_ = sqlite3_errmsg (_tmp44_);
			g_critical ("sqlclient.vala:271: %s", _tmp45_);
			result = -1;
			_g_free0 (keys);
			_g_free0 (sql);
			_sqlite3_finalize0 (stmt);
			_sql_client_server_unref0 (svr);
			block9_data_unref (_data9_);
			_data9_ = NULL;
			return result;
		}
		_tmp46_ = stmt;
		_tmp47_ = svr;
		_tmp48_ = _tmp47_->host;
		_tmp49_ = g_strdup (_tmp48_);
		_tmp50_ = g_free;
		sqlite3_bind_text (_tmp46_, 1, _tmp49_, -1, _tmp50_);
		_tmp51_ = stmt;
		_tmp52_ = svr;
		_tmp53_ = _tmp52_->port;
		sqlite3_bind_int (_tmp51_, 2, _tmp53_);
		_tmp54_ = stmt;
		_tmp55_ = svr;
		_tmp56_ = _tmp55_->nickname;
		_tmp57_ = g_strdup (_tmp56_);
		_tmp58_ = g_free;
		sqlite3_bind_text (_tmp54_, 3, _tmp57_, -1, _tmp58_);
		_tmp59_ = stmt;
		_tmp60_ = svr;
		_tmp61_ = _tmp60_->realname;
		_tmp62_ = g_strdup (_tmp61_);
		_tmp63_ = g_free;
		sqlite3_bind_text (_tmp59_, 4, _tmp62_, -1, _tmp63_);
		_tmp64_ = stmt;
		_tmp65_ = svr;
		_tmp66_ = _tmp65_->username;
		_tmp67_ = g_strdup (_tmp66_);
		_tmp68_ = g_free;
		sqlite3_bind_text (_tmp64_, 5, _tmp67_, -1, _tmp68_);
		_tmp69_ = stmt;
		_tmp70_ = svr;
		_tmp71_ = _tmp70_->password;
		_tmp72_ = g_strdup (_tmp71_);
		_tmp73_ = g_free;
		sqlite3_bind_text (_tmp69_, 6, _tmp72_, -1, _tmp73_);
		_tmp74_ = stmt;
		_tmp75_ = svr;
		_tmp76_ = _tmp75_->on_connect;
		_tmp77_ = g_strdup (_tmp76_);
		_tmp78_ = g_free;
		sqlite3_bind_text (_tmp74_, 7, _tmp77_, -1, _tmp78_);
		_tmp79_ = stmt;
		_tmp80_ = svr;
		_tmp81_ = _tmp80_->encryption;
		_tmp82_ = sql_client_bool_to (_tmp81_);
		sqlite3_bind_int (_tmp79_, 8, _tmp82_);
		_tmp83_ = stmt;
		_tmp84_ = svr;
		_tmp85_ = _tmp84_->validate_server;
		_tmp86_ = sql_client_bool_to (_tmp85_);
		sqlite3_bind_int (_tmp83_, 9, _tmp86_);
		_tmp87_ = stmt;
		_tmp88_ = svr;
		_tmp89_ = _tmp88_->autoconnect;
		_tmp90_ = sql_client_bool_to (_tmp89_);
		sqlite3_bind_int (_tmp87_, 10, _tmp90_);
		_tmp91_ = stmt;
		_tmp92_ = svr;
		_tmp93_ = _tmp92_->connect_cmds;
		_tmp94_ = g_strdup (_tmp93_);
		_tmp95_ = g_free;
		sqlite3_bind_text (_tmp91_, 11, _tmp94_, -1, _tmp95_);
		_tmp96_ = stmt;
		sqlite3_step (_tmp96_);
		_tmp97_ = sql_client_servers;
		_tmp98_ = svr;
		_tmp99_ = _tmp98_->id;
		_tmp100_ = svr;
		gee_abstract_map_set ((GeeAbstractMap*) _tmp97_, (gpointer) ((gintptr) _tmp99_), _tmp100_);
	}
	result = 0;
	_g_free0 (keys);
	_g_free0 (sql);
	_sqlite3_finalize0 (stmt);
	_sql_client_server_unref0 (svr);
	block9_data_unref (_data9_);
	_data9_ = NULL;
	return result;
}


void sql_client_server_remove_server (SqlClientServer* self) {
	GeeHashMap* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gchar* sql = NULL;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	sqlite3* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	sqlite3* _tmp13_ = NULL;
	const gchar* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = sql_client_servers;
	_tmp1_ = self->id;
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp0_, (gpointer) ((gintptr) _tmp1_), NULL);
	_tmp2_ = self->id;
	_tmp3_ = g_strdup_printf ("%i", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat ("DELETE FROM servers WHERE id=", _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_g_free0 (_tmp4_);
	sql = _tmp6_;
	_tmp7_ = sql_client_db;
	_tmp8_ = sql;
	_sqlite3_exec (_tmp7_, _tmp8_, NULL, NULL, NULL);
	_tmp9_ = self->id;
	_tmp10_ = g_strdup_printf ("%i", _tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat ("DELETE FROM channels WHERE server_id=", _tmp11_, NULL);
	_g_free0 (sql);
	sql = _tmp12_;
	_g_free0 (_tmp11_);
	_tmp13_ = sql_client_db;
	_tmp14_ = sql;
	_sqlite3_exec (_tmp13_, _tmp14_, NULL, NULL, NULL);
	_g_free0 (sql);
}


SqlClientServer* sql_client_server_construct (GType object_type) {
	SqlClientServer* self = NULL;
	self = (SqlClientServer*) g_type_create_instance (object_type);
	return self;
}


SqlClientServer* sql_client_server_new (void) {
	return sql_client_server_construct (SQL_CLIENT_TYPE_SERVER);
}


static void sql_client_value_server_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void sql_client_value_server_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		sql_client_server_unref (value->data[0].v_pointer);
	}
}


static void sql_client_value_server_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = sql_client_server_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer sql_client_value_server_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* sql_client_value_server_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SqlClientServer* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = sql_client_server_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* sql_client_value_server_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SqlClientServer** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = sql_client_server_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* sql_client_param_spec_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SqlClientParamSpecServer* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SQL_CLIENT_TYPE_SERVER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer sql_client_value_get_server (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SQL_CLIENT_TYPE_SERVER), NULL);
	return value->data[0].v_pointer;
}


void sql_client_value_set_server (GValue* value, gpointer v_object) {
	SqlClientServer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SQL_CLIENT_TYPE_SERVER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SQL_CLIENT_TYPE_SERVER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		sql_client_server_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		sql_client_server_unref (old);
	}
}


void sql_client_value_take_server (GValue* value, gpointer v_object) {
	SqlClientServer* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SQL_CLIENT_TYPE_SERVER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SQL_CLIENT_TYPE_SERVER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		sql_client_server_unref (old);
	}
}


static void sql_client_server_class_init (SqlClientServerClass * klass) {
	sql_client_server_parent_class = g_type_class_peek_parent (klass);
	((SqlClientServerClass *) klass)->finalize = sql_client_server_finalize;
}


static void sql_client_server_instance_init (SqlClientServer * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	GeeLinkedList* _tmp7_ = NULL;
	self->id = -1;
	_tmp0_ = g_strdup ("");
	self->host = _tmp0_;
	self->port = (gint) CONNECTION_DEFAULT_PORT;
	_tmp1_ = g_strdup ("");
	self->nickname = _tmp1_;
	_tmp2_ = g_strdup ("");
	self->realname = _tmp2_;
	_tmp3_ = g_strdup ("");
	self->username = _tmp3_;
	_tmp4_ = g_strdup ("");
	self->password = _tmp4_;
	_tmp5_ = g_strdup ("");
	self->on_connect = _tmp5_;
	self->encryption = FALSE;
	self->autoconnect = FALSE;
	self->validate_server = FALSE;
	_tmp6_ = g_strdup ("");
	self->connect_cmds = _tmp6_;
	_tmp7_ = gee_linked_list_new (SQL_CLIENT_TYPE_CHANNEL, (GBoxedCopyFunc) sql_client_channel_ref, sql_client_channel_unref, NULL, NULL, NULL);
	self->channels = _tmp7_;
	self->ref_count = 1;
}


static void sql_client_server_finalize (SqlClientServer* obj) {
	SqlClientServer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SQL_CLIENT_TYPE_SERVER, SqlClientServer);
	g_signal_handlers_destroy (self);
	_g_free0 (self->host);
	_g_free0 (self->nickname);
	_g_free0 (self->realname);
	_g_free0 (self->username);
	_g_free0 (self->password);
	_g_free0 (self->on_connect);
	_g_free0 (self->connect_cmds);
	_g_object_unref0 (self->channels);
}


GType sql_client_server_get_type (void) {
	static volatile gsize sql_client_server_type_id__volatile = 0;
	if (g_once_init_enter (&sql_client_server_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { sql_client_value_server_init, sql_client_value_server_free_value, sql_client_value_server_copy_value, sql_client_value_server_peek_pointer, "p", sql_client_value_server_collect_value, "p", sql_client_value_server_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SqlClientServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sql_client_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SqlClientServer), 0, (GInstanceInitFunc) sql_client_server_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType sql_client_server_type_id;
		sql_client_server_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SqlClientServer", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&sql_client_server_type_id__volatile, sql_client_server_type_id);
	}
	return sql_client_server_type_id__volatile;
}


gpointer sql_client_server_ref (gpointer instance) {
	SqlClientServer* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void sql_client_server_unref (gpointer instance) {
	SqlClientServer* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SQL_CLIENT_SERVER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


void sql_client_channel_delete_channel (SqlClientChannel* self) {
	gchar* sql = NULL;
	gint _tmp0_ = 0;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	GeeHashMap* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gboolean _tmp10_ = FALSE;
	GeeHashMap* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	gpointer _tmp18_ = NULL;
	SqlClientServer* _tmp19_ = NULL;
	GeeLinkedList* _tmp20_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->server_id;
	_tmp1_ = g_strdup_printf ("%i", _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat ("DELETE FROM channels WHERE server_id=", _tmp2_, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp4_, " AND channel=$NAME", NULL);
	_tmp6_ = _tmp5_;
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	sql = _tmp6_;
	_tmp7_ = sql;
	sql_client_channel_channel_query (self, _tmp7_);
	_tmp8_ = sql_client_servers;
	_tmp9_ = self->server_id;
	_tmp10_ = gee_abstract_map_has_key ((GeeAbstractMap*) _tmp8_, (gpointer) ((gintptr) _tmp9_));
	if (!_tmp10_) {
		gint _tmp11_ = 0;
		gchar* _tmp12_ = NULL;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		_tmp11_ = self->server_id;
		_tmp12_ = g_strdup_printf ("%i", _tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = g_strconcat ("No server with key ", _tmp13_, NULL);
		_tmp15_ = _tmp14_;
		g_warning ("sqlclient.vala:316: %s", _tmp15_);
		_g_free0 (_tmp15_);
		_g_free0 (_tmp13_);
		_g_free0 (sql);
		return;
	}
	_tmp16_ = sql_client_servers;
	_tmp17_ = self->server_id;
	_tmp18_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp16_, (gpointer) ((gintptr) _tmp17_));
	_tmp19_ = (SqlClientServer*) _tmp18_;
	_tmp20_ = _tmp19_->channels;
	gee_abstract_collection_remove ((GeeAbstractCollection*) _tmp20_, self);
	_sql_client_server_unref0 (_tmp19_);
	_g_free0 (sql);
}


void sql_client_channel_add_channel (SqlClientChannel* self) {
	gint _tmp0_ = 0;
	gchar* sql = NULL;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GeeHashMap* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gpointer _tmp11_ = NULL;
	SqlClientServer* _tmp12_ = NULL;
	GeeLinkedList* _tmp13_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->server_id;
	if (_tmp0_ < 0) {
		return;
	}
	_tmp1_ = self->server_id;
	_tmp2_ = g_strdup_printf ("%i", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat ("INSERT INTO channels (server_id, channel) VALUES(", _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, ", $CHANNEL)", NULL);
	_tmp7_ = _tmp6_;
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	sql = _tmp7_;
	_tmp8_ = sql;
	sql_client_channel_channel_query (self, _tmp8_);
	_tmp9_ = sql_client_servers;
	_tmp10_ = self->server_id;
	_tmp11_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp9_, (gpointer) ((gintptr) _tmp10_));
	_tmp12_ = (SqlClientServer*) _tmp11_;
	_tmp13_ = _tmp12_->channels;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp13_, self);
	_sql_client_server_unref0 (_tmp12_);
	_g_free0 (sql);
}


gboolean sql_client_channel_update_autoconnect (SqlClientChannel* self, gboolean state) {
	gboolean result = FALSE;
	gchar* sql = NULL;
	gboolean _tmp0_ = FALSE;
	gint _tmp1_ = 0;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gboolean _tmp15_ = FALSE;
	gboolean _tmp16_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = state;
	_tmp1_ = sql_client_bool_to (_tmp0_);
	_tmp2_ = g_strdup_printf ("%i", _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strconcat ("UPDATE channels SET autoconnect = ", _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, " WHERE server_id = ", NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = self->server_id;
	_tmp9_ = g_strdup_printf ("%i", _tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = g_strconcat (_tmp7_, _tmp10_, NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat (_tmp12_, " AND channel = $NAME", NULL);
	_tmp14_ = _tmp13_;
	_g_free0 (_tmp12_);
	_g_free0 (_tmp10_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp3_);
	sql = _tmp14_;
	sql_client_channel_channel_query (self, sql);
	_tmp15_ = state;
	self->autoconnect = _tmp15_;
	_tmp16_ = self->autoconnect;
	result = _tmp16_;
	_g_free0 (sql);
	return result;
}


static void sql_client_channel_channel_query (SqlClientChannel* self, const gchar* sql) {
	sqlite3_stmt* stmt = NULL;
	gint ok = 0;
	sqlite3* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	sqlite3_stmt* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	sqlite3_stmt* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	GDestroyNotify _tmp13_ = NULL;
	sqlite3_stmt* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sql != NULL);
	_tmp0_ = sql_client_db;
	_tmp1_ = sql;
	_tmp2_ = sql;
	_tmp3_ = strlen (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp6_ = sqlite3_prepare_v2 (_tmp0_, _tmp1_, _tmp4_, &_tmp5_, NULL);
	_sqlite3_finalize0 (stmt);
	stmt = _tmp5_;
	ok = _tmp6_;
	_tmp7_ = ok;
	if (_tmp7_ == SQLITE_ERROR) {
		sqlite3* _tmp8_ = NULL;
		const gchar* _tmp9_ = NULL;
		_tmp8_ = sql_client_db;
		_tmp9_ = sqlite3_errmsg (_tmp8_);
		g_critical ("sqlclient.vala:341: %s", _tmp9_);
		_sqlite3_finalize0 (stmt);
		return;
	}
	_tmp10_ = stmt;
	_tmp11_ = self->channel;
	_tmp12_ = g_strdup (_tmp11_);
	_tmp13_ = g_free;
	sqlite3_bind_text (_tmp10_, 1, _tmp12_, -1, _tmp13_);
	_tmp14_ = stmt;
	sqlite3_step (_tmp14_);
	_sqlite3_finalize0 (stmt);
}


SqlClientChannel* sql_client_channel_construct (GType object_type) {
	SqlClientChannel* self = NULL;
	self = (SqlClientChannel*) g_type_create_instance (object_type);
	return self;
}


SqlClientChannel* sql_client_channel_new (void) {
	return sql_client_channel_construct (SQL_CLIENT_TYPE_CHANNEL);
}


static void sql_client_value_channel_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void sql_client_value_channel_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		sql_client_channel_unref (value->data[0].v_pointer);
	}
}


static void sql_client_value_channel_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = sql_client_channel_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer sql_client_value_channel_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* sql_client_value_channel_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SqlClientChannel* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = sql_client_channel_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* sql_client_value_channel_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SqlClientChannel** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = sql_client_channel_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* sql_client_param_spec_channel (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SqlClientParamSpecChannel* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SQL_CLIENT_TYPE_CHANNEL), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer sql_client_value_get_channel (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SQL_CLIENT_TYPE_CHANNEL), NULL);
	return value->data[0].v_pointer;
}


void sql_client_value_set_channel (GValue* value, gpointer v_object) {
	SqlClientChannel* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SQL_CLIENT_TYPE_CHANNEL));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SQL_CLIENT_TYPE_CHANNEL));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		sql_client_channel_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		sql_client_channel_unref (old);
	}
}


void sql_client_value_take_channel (GValue* value, gpointer v_object) {
	SqlClientChannel* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SQL_CLIENT_TYPE_CHANNEL));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SQL_CLIENT_TYPE_CHANNEL));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		sql_client_channel_unref (old);
	}
}


static void sql_client_channel_class_init (SqlClientChannelClass * klass) {
	sql_client_channel_parent_class = g_type_class_peek_parent (klass);
	((SqlClientChannelClass *) klass)->finalize = sql_client_channel_finalize;
}


static void sql_client_channel_instance_init (SqlClientChannel * self) {
	self->id = -1;
	self->ref_count = 1;
}


static void sql_client_channel_finalize (SqlClientChannel* obj) {
	SqlClientChannel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SQL_CLIENT_TYPE_CHANNEL, SqlClientChannel);
	g_signal_handlers_destroy (self);
	_g_free0 (self->channel);
}


GType sql_client_channel_get_type (void) {
	static volatile gsize sql_client_channel_type_id__volatile = 0;
	if (g_once_init_enter (&sql_client_channel_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { sql_client_value_channel_init, sql_client_value_channel_free_value, sql_client_value_channel_copy_value, sql_client_value_channel_peek_pointer, "p", sql_client_value_channel_collect_value, "p", sql_client_value_channel_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SqlClientChannelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sql_client_channel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SqlClientChannel), 0, (GInstanceInitFunc) sql_client_channel_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType sql_client_channel_type_id;
		sql_client_channel_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SqlClientChannel", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&sql_client_channel_type_id__volatile, sql_client_channel_type_id);
	}
	return sql_client_channel_type_id__volatile;
}


gpointer sql_client_channel_ref (gpointer instance) {
	SqlClientChannel* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void sql_client_channel_unref (gpointer instance) {
	SqlClientChannel* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SQL_CLIENT_CHANNEL_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void sql_client_class_init (SqlClientClass * klass) {
	GeeHashMap* _tmp0_ = NULL;
	sql_client_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = sql_client_finalize;
	_tmp0_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, SQL_CLIENT_TYPE_SERVER, (GBoxedCopyFunc) sql_client_server_ref, sql_client_server_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	sql_client_servers = _tmp0_;
}


static void sql_client_instance_init (SqlClient * self) {
}


static void sql_client_finalize (GObject* obj) {
	SqlClient * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SQL_CLIENT, SqlClient);
	G_OBJECT_CLASS (sql_client_parent_class)->finalize (obj);
}


GType sql_client_get_type (void) {
	static volatile gsize sql_client_type_id__volatile = 0;
	if (g_once_init_enter (&sql_client_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SqlClientClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sql_client_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SqlClient), 0, (GInstanceInitFunc) sql_client_instance_init, NULL };
		GType sql_client_type_id;
		sql_client_type_id = g_type_register_static (G_TYPE_OBJECT, "SqlClient", &g_define_type_info, 0);
		g_once_init_leave (&sql_client_type_id__volatile, sql_client_type_id);
	}
	return sql_client_type_id__volatile;
}



